import { describe, expect, it, vi } from "vitest";
import fs from "node:fs";
import path from "node:path";

import init, {
    PublicDoenetMLCore as PublicDoenetMLCoreRust,
    DastRoot as DastRootInCore,
    RefResolution,
    PathToCheck,
    FlatFragment,
    IndexResolution,
    ContentVector,
    NodeList,
} from "@doenet/doenetml-worker-rust";
import { PublicDoenetMLCore as PublicDoenetMLCoreJavascript } from "@doenet/doenetml-worker-javascript";
import {
    expandExternalReferences,
    lezerToDast,
    normalizeDocumentDast,
} from "@doenet/parser";
import { resolvePathImmediatelyToNodeIdx } from "@doenet/debug-hooks";

import { defaultFlags } from "../../doenetml/src/flags";
import type { ComponentInstruction, UpdateInstruction } from "./flatDastFromJS";
import { flatDastFromJS } from "./flatDastFromJS";
import {
    collectInstructionMaps,
    flatDastUpdateFromJS,
    seedInstructionMaps,
} from "./flatDastUpdateFromJS";
import { translateJsCoreActionName } from "./jsCoreActionNames";

// The JS core posts diagnostics; silence it so test output stays readable.
vi.stubGlobal("postMessage", vi.fn());

// The rust resolver WASM is generated by `wasm-pack` and may be absent if the
// Rust worker has not been built. Skip this suite (rather than failing at
// runtime) when it is unavailable, so `npm test` stays reliable without
// requiring a prior Rust build — mirroring
// `packages/lsp-tools/test/rust-resolver-integration.test.ts`.
const wasmPath = path.resolve(
    import.meta.dirname,
    "../../doenetml-worker-rust/lib-js-wasm-binding/pkg/lib_doenetml_worker_bg.wasm",
);
const wasmAvailable = fs.existsSync(wasmPath);
if (!wasmAvailable) {
    console.warn(
        `Skipping live JS-core integration test — WASM not found at ${wasmPath}. Build @doenet/doenetml-worker-rust to enable it.`,
    );
}

/**
 * Stand up a real JavaScript core (backed by the rust resolver, exactly as
 * `CoreWorker` wires it) with a renderer callback that captures every pushed
 * batch. This mirrors the setup in
 * `doenetml-worker-javascript/src/test/utils/test-core.ts`, except the
 * `updateRenderersCallback` records the batches instead of discarding them, so
 * the test can feed authentic JS-core output through `flatDastUpdateFromJS`.
 *
 * Returns the live `core`, a `resolvePathToNodeIdx` helper, the
 * `componentIdx -> name` / `doenetId -> componentIdx` maps seeded from the
 * initial render (just like `CoreWorker.returnFlatDastFromJS`), and a
 * `drainBatches` accessor for the post-init pushes.
 */
async function createCapturingCore(doenetML: string) {
    const wasmBuffer = fs.readFileSync(wasmPath);
    await init({ module_or_path: wasmBuffer });

    const rustCore = PublicDoenetMLCoreRust.new();

    const dast = normalizeDocumentDast(
        await expandExternalReferences(lezerToDast(doenetML), async (uri) => {
            throw Error(`No external DoenetML available for "${uri}".`);
        }),
        true,
    );
    rustCore.set_source(dast as DastRootInCore, doenetML);

    const normalizedRoot = rustCore.return_normalized_dast_root();

    function calculateRootNames() {
        return rustCore.calculate_root_names();
    }
    function resolvePath(
        pathToCheck: PathToCheck,
        origin: number,
        skipParentSearch: boolean,
    ): RefResolution {
        return rustCore.resolve_path(pathToCheck, origin, skipParentSearch);
    }
    function addNodesToResolver(
        flatFragment: FlatFragment,
        indexResolution: IndexResolution,
    ) {
        rustCore.add_nodes_to_resolver(flatFragment, indexResolution);
    }
    function replaceIndexResolutionsInResolver(
        components: ContentVector,
        indexResolution: IndexResolution,
    ) {
        rustCore.replace_index_resolutions_in_resolver(
            components,
            indexResolution,
        );
    }
    function deleteNodesFromResolver(nodeList: NodeList) {
        rustCore.delete_nodes_from_resolver(nodeList);
    }

    const core = new PublicDoenetMLCoreJavascript();
    core.setSource(doenetML);
    core.setFlags({ ...defaultFlags });

    await core.initializeWorker({
        activityId: "a",
        docId: "a",
        requestedVariantIndex: 1,
        attemptNumber: 1,
        normalizedRoot,
        addNodesToResolver,
        replaceIndexResolutionsInResolver,
        deleteNodesFromResolver,
        resolvePath,
        calculateRootNames,
    });

    // The initial render arrives once as `{ init: true }`; every later batch is
    // buffered, exactly as `CoreWorker` does.
    let initialUpdateInstructions: UpdateInstruction[] | null = null;
    let buffer: UpdateInstruction[] = [];
    const updateRenderersCallback = (args: any) => {
        if (args.init) {
            initialUpdateInstructions = args.updateInstructions;
        } else if (args.updateInstructions) {
            buffer.push(...args.updateInstructions);
        }
    };

    const coreResult = await core.createCoreGenerateDast(
        { coreId: "a", cid: null, initializeCounters: {} },
        updateRenderersCallback,
        () => {},
        () => {},
        () => {},
        () => {},
        () => {},
        async () => ({ allowView: true }),
    );

    if (!coreResult.success) {
        throw Error(coreResult.errMsg);
    }
    if (initialUpdateInstructions === null) {
        throw Error("Did not receive initial render before dast.");
    }

    const documentToRender: ComponentInstruction =
        coreResult.coreInfo.documentToRender;

    // Seed the lookup maps the same way `CoreWorker.returnFlatDastFromJS` does.
    const { componentIdxToName, doenetIdToComponentIdx } = seedInstructionMaps(
        documentToRender,
        initialUpdateInstructions,
    );

    function resolvePathToNodeIdx(name: string, origin = 0) {
        return resolvePathImmediatelyToNodeIdx(name, rustCore, core, origin);
    }

    function drainBatches() {
        const batches = buffer;
        buffer = [];
        return batches;
    }

    // Build the initial FlatDast root the same way `CoreWorker` does, so tests
    // can assert on the initial-render props the prototype renderers consume.
    const flatDastRoot = flatDastFromJS(
        documentToRender,
        initialUpdateInstructions,
    );

    return {
        core,
        resolvePathToNodeIdx,
        componentIdxToName,
        doenetIdToComponentIdx,
        drainBatches,
        flatDastRoot,
    };
}

describe.skipIf(!wasmAvailable)(
    "flatDastUpdateFromJS against a live JavaScript core",
    () => {
        it("turns a textInput action into a FlatDast update map", async () => {
            const {
                core,
                resolvePathToNodeIdx,
                componentIdxToName,
                doenetIdToComponentIdx,
                drainBatches,
            } = await createCapturingCore(
                `<textInput name="ti" prefill="hello" />`,
            );

            const tiIdx = await resolvePathToNodeIdx("ti");

            // Dispatch a real action that mutates a `forRenderer` state value,
            // then run the exact conversion that
            // `CoreWorker.dispatchActionJavascriptFlat` performs on the drained
            // batches.
            await core.requestAction({
                componentIdx: tiIdx,
                actionName: "updateImmediateValue",
                args: { text: "world" },
            });

            const batches = drainBatches();
            expect(batches.length).toBeGreaterThan(0);

            collectInstructionMaps(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );
            const updates = flatDastUpdateFromJS(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );

            // The update map is keyed by `componentIdx` and the textInput's
            // `immediateValue` forRenderer prop reached `changedState` — exactly
            // what the prototype's `processElementUpdates` reducer consumes.
            expect(updates[tiIdx]).toBeDefined();
            expect(updates[tiIdx].changedState?.immediateValue).toBe("world");
        });

        it("translates the prototype `move` action to the JS core's `movePoint` and updates referencing components", async () => {
            const {
                core,
                resolvePathToNodeIdx,
                componentIdxToName,
                doenetIdToComponentIdx,
                drainBatches,
            } = await createCapturingCore(
                `<graph><point name="P">(3,4)</point></graph>
<p>x is <number name="n">$P.x</number></p>`,
            );

            const pIdx = await resolvePathToNodeIdx("P");
            const nIdx = await resolvePathToNodeIdx("n");

            // Exercise the exact lookup `CoreWorker.dispatchActionJavascriptFlat`
            // performs: resolve the component type from the map seeded during the
            // initial render, then translate. The prototype's graph-point
            // renderer dispatches the rust action name `move`; the JS core
            // registers it as `movePoint`. Without the translation the JS core
            // silently no-ops and nothing updates.
            expect(componentIdxToName[pIdx]).toBe("point");
            const movePointAction = translateJsCoreActionName(
                componentIdxToName[pIdx],
                "move",
            );
            expect(movePointAction).toBe("movePoint");

            await core.requestAction({
                componentIdx: pIdx,
                actionName: movePointAction,
                args: { x: 7, y: 9 },
            });

            const batches = drainBatches();
            expect(batches.length).toBeGreaterThan(0);

            collectInstructionMaps(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );
            const updates = flatDastUpdateFromJS(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );

            // The moved point's new x-coordinate reached the referencing
            // `number`'s `changedState`, so the prototype's `$P.x` echo updates.
            expect(updates[nIdx]).toBeDefined();
            expect(updates[nIdx].changedState?.text).toBe("7");
        });

        it("translates the prototype `changeBoundingBox` action and propagates back to a bound number", async () => {
            const {
                core,
                resolvePathToNodeIdx,
                componentIdxToName,
                doenetIdToComponentIdx,
                drainBatches,
            } = await createCapturingCore(
                `<number name="xmax">10</number>
<graph name="g" xmax="$xmax"><point name="P">(1,2)</point></graph>`,
            );

            const gIdx = await resolvePathToNodeIdx("g");
            const xmaxIdx = await resolvePathToNodeIdx("xmax");

            // Mirror the bridge's lookup: resolve the component type from the
            // seeded map, then translate. The prototype's graph renderer
            // dispatches the rust action name `changeBoundingBox`; the JS core
            // registers it as `changeAxisLimits`.
            expect(componentIdxToName[gIdx]).toBe("graph");
            const changeBoundingBoxAction = translateJsCoreActionName(
                componentIdxToName[gIdx],
                "changeBoundingBox",
            );
            expect(changeBoundingBoxAction).toBe("changeAxisLimits");

            // Panning/zooming the graph in the renderer changes its bounding box.
            // Because `xmax` is the source of the graph's `xMax`, the new value
            // must flow back to the `number` so its `$xmax` display updates.
            await core.requestAction({
                componentIdx: gIdx,
                actionName: changeBoundingBoxAction,
                args: { xMin: -5, xMax: 25, yMin: -5, yMax: 5 },
            });

            const batches = drainBatches();
            expect(batches.length).toBeGreaterThan(0);

            collectInstructionMaps(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );
            const updates = flatDastUpdateFromJS(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );

            // The bound `number`'s rendered `text` reflects the new x-max (25).
            expect(updates[xmaxIdx]).toBeDefined();
            expect(updates[xmaxIdx].changedState?.text).toBe("25");
        });

        it("updates a point's `coordsLatex` after a move, so a `$P` point-in-text echo re-renders", async () => {
            const {
                core,
                resolvePathToNodeIdx,
                componentIdxToName,
                doenetIdToComponentIdx,
                drainBatches,
            } = await createCapturingCore(
                `<graph><point name="P">(3,4)</point></graph>
<p>pt: $P</p>`,
            );

            const pIdx = await resolvePathToNodeIdx("P");

            await core.requestAction({
                componentIdx: pIdx,
                actionName: translateJsCoreActionName("point", "move"),
                args: { x: 7, y: 8 },
            });

            const batches = drainBatches();
            expect(batches.length).toBeGreaterThan(0);

            collectInstructionMaps(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );
            const updates = flatDastUpdateFromJS(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );

            // `$P` rendered in text is the prototype's `PointInText`, which reads
            // `coordsLatex`. The `pointJsToRust` fixup must produce it on the
            // update path so the echo shows the moved coordinates.
            expect(updates[pIdx]).toBeDefined();
            expect(updates[pIdx].changedState?.coordsLatex).toBe(
                "\\left( 7, 8 \\right)",
            );
        });

        it("updates a `<math>$P.x</math>`'s latex after the referenced point moves", async () => {
            const {
                core,
                resolvePathToNodeIdx,
                componentIdxToName,
                doenetIdToComponentIdx,
                drainBatches,
            } = await createCapturingCore(
                `<graph><point name="P">(3,4)</point></graph>
<p>x: <math name="mx">$P.x</math></p>`,
            );

            const pIdx = await resolvePathToNodeIdx("P");
            const mxIdx = await resolvePathToNodeIdx("mx");

            await core.requestAction({
                componentIdx: pIdx,
                actionName: translateJsCoreActionName("point", "move"),
                args: { x: 7, y: 8 },
            });

            const batches = drainBatches();
            expect(batches.length).toBeGreaterThan(0);

            collectInstructionMaps(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );
            const updates = flatDastUpdateFromJS(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );

            // The prototype's `Math` renderer reads `latex`; after the point
            // moves, `$P.x` is `7`.
            expect(updates[mxIdx]).toBeDefined();
            expect(updates[mxIdx].changedState?.latex).toBe("7");
        });

        it("populates a `<m>`'s latex prop so the renderer can show it (initial render + value-commit update)", async () => {
            const {
                core,
                resolvePathToNodeIdx,
                componentIdxToName,
                doenetIdToComponentIdx,
                drainBatches,
                flatDastRoot,
            } = await createCapturingCore(
                `<textInput name="ti" prefill="abc" />
<m name="mm">$ti</m>`,
            );

            const tiIdx = await resolvePathToNodeIdx("ti");
            const mmIdx = await resolvePathToNodeIdx("mm");

            // The JS core (like production doenetml) carries `<m>`'s content in a
            // `latex` prop with no children; the prototype `M` renderer reads it.
            const mmElement = flatDastRoot.elements[mmIdx];
            expect(mmElement.type).toBe("element");
            expect((mmElement as any).data.props.latex).toBe("abc");

            // Commit a new value (`<m>$ti</m>` references `value`, which updates
            // on commit rather than per-keystroke), then convert the batches.
            await core.requestAction({
                componentIdx: tiIdx,
                actionName: "updateImmediateValue",
                args: { text: "xyz" },
            });
            await core.requestAction({
                componentIdx: tiIdx,
                actionName: "updateValue",
                args: {},
            });

            const batches = drainBatches();
            collectInstructionMaps(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );
            const updates = flatDastUpdateFromJS(
                batches,
                componentIdxToName,
                doenetIdToComponentIdx,
            );

            expect(updates[mmIdx]).toBeDefined();
            expect(updates[mmIdx].changedState?.latex).toBe("xyz");
        });
    },
);
