/**
 * Exposes MathJax's speech strings to assistive technology as *text*.
 *
 * MathJax 4 renders each expression as a visual `<mjx-math aria-hidden="true">`
 * plus an empty `<mjx-speech role="img" aria-label="…">` carrying the speech
 * string generated by the Speech Rule Engine. So the only thing a screen reader
 * sees for a formula is a labelled graphic with no content of its own.
 *
 * VoiceOver handles that badly. MathJax's own accessibility documentation
 * records it: "VoiceOver skips the ARIA labels"; in read-all mode it "might stop
 * at an equation"; in read-next mode it "might jump back to a preceding element
 * after reading the ARIA label on each expression". A reader working through a
 * page therefore loses formulas outright — see issue #1456, where three of six
 * formulas laid out in a `<sideBySide>` were never spoken, because the jump
 * after the first one landed in the neighbouring column.
 *
 * This module rewrites each expression into the shape screen readers read
 * reliably: the same speech string, moved out of the label and into a visually
 * hidden span *inside* `<mjx-speech>`, with the label and the `img` role
 * dropped. Nothing visual changes and no information is lost. `<mjx-speech>`
 * then takes its accessible name from that text, which matters because it is
 * also the element MathJax focuses when a reader opens the expression explorer:
 * hiding it, or leaving it named but empty, would break exploring an expression
 * to fix reading it. Its braille label stays where it is and keeps applying,
 * since the element still has a name.
 *
 * The rewrite runs from a `MutationObserver` rather than from each place Doenet
 * typesets, for three reasons: math reaches the page through many call sites
 * (`<m>`, every math-bearing input, choice options, buttons, the virtual
 * keyboard); the speech string is attached *asynchronously*, some time after the
 * typeset that created the element resolves; and the explorer rewrites the label
 * as a reader walks into a subexpression, which this then follows.
 */

/** Marks the span this module adds, so a rescan can find and update it. */
const SPEECH_TEXT_ATTR = "data-doenet-math-speech";

/**
 * Keeps the added text out of sight without hiding it from assistive
 * technology. Written as an inline style so that the rewrite stays
 * self-contained: it is installed from the MathJax loader, which has no
 * stylesheet of its own and runs in host pages that never load Doenet's CSS.
 */
const VISUALLY_HIDDEN_STYLE = [
    "position:absolute",
    "width:1px",
    "height:1px",
    "margin:-1px",
    "padding:0",
    "border:0",
    "clip-path:inset(50%)",
    "overflow:hidden",
    "white-space:nowrap",
].join(";");

/**
 * Rewrites every MathJax expression under `root` whose speech string has been
 * attached but not yet turned into text.
 *
 * Safe to call repeatedly, and self-limiting: moving the string out of
 * `aria-label` is what takes an expression out of the selector below, so a
 * rescan triggered by this function's own DOM writes finds nothing to do. The
 * explorer putting a fresh label on an element is what brings it back.
 */
export function exposeMathSpeechAsText(root: ParentNode): void {
    for (const speech of root.querySelectorAll("mjx-speech[aria-label]")) {
        const label = speech.getAttribute("aria-label")?.trim();
        if (!label) {
            // MathJax creates `<mjx-speech>` during the typeset and fills in
            // its label once the speech engine has run, so an empty label just
            // means "not ready yet". Leave the attribute in place: the change
            // that fills it in is what schedules the next pass.
            continue;
        }

        let text = speech.querySelector(`[${SPEECH_TEXT_ATTR}]`);
        if (!text) {
            text = speech.ownerDocument.createElement("span");
            text.setAttribute(SPEECH_TEXT_ATTR, "true");
            text.setAttribute("style", VISUALLY_HIDDEN_STYLE);
            speech.append(text);
        }
        text.textContent = label;

        // With the name now coming from the text, the `img` role would suppress
        // it, and the role description that went with it describes a role that
        // is no longer there.
        speech.removeAttribute("aria-label");
        speech.removeAttribute("role");
        speech.removeAttribute("aria-roledescription");
        speech.removeAttribute("aria-brailleroledescription");
    }
}

/**
 * The installed observer, held both as the "already started" flag and as a
 * reference keeping it alive for the life of the page.
 */
let observer: MutationObserver | null = null;
/** Set between scheduling a pass and running it, so bursts collapse into one. */
let scanScheduled = false;

/**
 * Starts exposing MathJax speech as text across the page, and keeps doing it as
 * math is typeset, retypeset, and as speech strings arrive. Calling it again is
 * a no-op, so at most one observer runs per copy of this module — and in
 * practice one per realm, since the only caller is `loadMathJax`, whose single
 * memoized promise per realm means only the first copy loaded gets that far.
 *
 * Does nothing outside a browser, which is what keeps it inert under the
 * loader's Node-environment unit tests.
 */
export function startExposingMathSpeechAsText(): void {
    if (observer || typeof MutationObserver === "undefined") {
        return;
    }
    const root = document.body ?? document.documentElement;
    if (!root) {
        return;
    }

    exposeMathSpeechAsText(root);

    observer = new MutationObserver(() => scheduleScan(root));
    observer.observe(root, {
        subtree: true,
        childList: true,
        // MathJax attaches the speech string by setting this attribute, well
        // after the typeset that created the element. Filtering to it keeps the
        // observer off the far busier attribute traffic of a dragged graph.
        attributes: true,
        attributeFilter: ["aria-label"],
    });
}

/**
 * Coalesces a typeset's worth of mutations into a single pass, run from a task
 * of its own so that the writes it makes are delivered to the observer as an
 * ordinary later batch. That batch finds every expression already up to date
 * and writes nothing, so the cycle settles rather than feeding itself.
 */
function scheduleScan(root: ParentNode) {
    if (scanScheduled) {
        return;
    }
    scanScheduled = true;
    setTimeout(() => {
        scanScheduled = false;
        exposeMathSpeechAsText(root);
    }, 0);
}
