/**
 * Exposes MathJax's speech strings to assistive technology as *text*.
 *
 * MathJax 4 renders each expression as a visual `<mjx-math aria-hidden="true">`
 * plus an empty `<mjx-speech role="img" aria-label="…">` carrying the speech
 * string generated by the Speech Rule Engine. So the only thing a screen reader
 * sees for a formula is a labelled graphic with no content of its own.
 *
 * VoiceOver handles that badly. MathJax's own accessibility documentation
 * records it: "VoiceOver skips the ARIA labels"; in read-all mode it "might stop
 * at an equation"; in read-next mode it "might jump back to a preceding element
 * after reading the ARIA label on each expression". A reader working through a
 * page therefore loses formulas outright — see issue #1456, where three of six
 * formulas laid out in a `<sideBySide>` were never spoken, because the jump
 * after the first one landed in the neighbouring column.
 *
 * This module rewrites each expression into the shape screen readers read
 * reliably: the same speech string, moved out of the label and into a visually
 * hidden span *inside* `<mjx-speech>`, with the label and the `img` role
 * dropped. Nothing visual changes. Stripped of its role, `<mjx-speech>` is an
 * ordinary generic container, which is the point: a generic container is not
 * named and not a leaf, so a reader meets the words themselves, as text in
 * document order, instead of a graphic whose name it may skip. The element
 * stays visible to assistive technology, because MathJax focuses it when a
 * reader opens the expression explorer, and hiding a focusable element would
 * trade exploring an expression for reading one.
 *
 * The words live in a shadow root on that span rather than directly in it, so
 * that they reach a reader without joining the page's text. A browser flattens
 * a shadow tree into the accessibility tree — the added text is a `StaticText`
 * node either way — but leaves it out of `textContent` and out of a selection,
 * so copying a paragraph does not paste "sine theta equals two fifths" beside
 * the formula, and anything reading the rendered text of an expression still
 * reads the formula rather than a sentence describing it.
 *
 * The rewrite runs from a `MutationObserver` rather than from each place Doenet
 * typesets, for three reasons: math reaches the page through many call sites
 * (`<m>`, every math-bearing input, choice options, buttons, the virtual
 * keyboard); the speech string is attached *asynchronously*, some time after the
 * typeset that created the element resolves; and the explorer swaps in a freshly
 * labelled element as a reader walks into a subexpression, which this follows.
 */

/** Marks the span this module adds, so a later pass can find and update it. */
const SPEECH_TEXT_ATTR = "data-doenet-math-speech";

/** Matches an expression whose speech string is still only a label. */
const LABELLED_SPEECH_SELECTOR = "mjx-speech[aria-label]";

/**
 * Keeps the added text out of sight without hiding it from assistive
 * technology. Written as an inline style so that the rewrite stays
 * self-contained: it is installed from the MathJax loader, which has no
 * stylesheet of its own and runs in host pages that never load Doenet's CSS.
 */
const VISUALLY_HIDDEN_STYLE = [
    "position:absolute",
    "width:1px",
    "height:1px",
    "margin:-1px",
    "padding:0",
    "border:0",
    "clip-path:inset(50%)",
    "overflow:hidden",
    "white-space:nowrap",
].join(";");

/**
 * Moves one expression's speech string out of the `aria-label` on its
 * `<mjx-speech>` and into a visually hidden span inside it. Any other element —
 * one with no label, or any of the many that carry a label of their own — is
 * left untouched, so this can be handed whatever element a mutation reports.
 *
 * Safe to call repeatedly, and self-limiting: moving the string out of
 * `aria-label` is what takes an expression out of
 * {@link LABELLED_SPEECH_SELECTOR}, so revisiting a rewritten one finds nothing
 * to do. A freshly labelled element from the explorer is what brings one back.
 */
function rewriteSpeechElement(speech: Element): void {
    if (!speech.matches(LABELLED_SPEECH_SELECTOR)) {
        return;
    }
    const label = speech.getAttribute("aria-label")?.trim();
    if (!label) {
        // An empty label carries no speech string to expose. Leave the element
        // as MathJax made it; should a labelled one arrive later, the mutation
        // that brings it drives the pass that handles it.
        return;
    }

    let text = speech.querySelector(`[${SPEECH_TEXT_ATTR}]`);
    if (!text) {
        text = speech.ownerDocument.createElement("span");
        text.setAttribute(SPEECH_TEXT_ATTR, "true");
        text.setAttribute("style", VISUALLY_HIDDEN_STYLE);
        speech.append(text);
    }
    // The words go in the shadow tree, which the host's clipping still hides and
    // the page's text still excludes. `attachShadow` throws on a second call, so
    // reuse the root a previous pass opened.
    const shadow = text.shadowRoot ?? text.attachShadow({ mode: "open" });
    shadow.textContent = label;

    // The words are now content, which the `img` role would hide again by
    // making the element a leaf named by its label. The role descriptions went
    // with that role, so they describe one the element no longer has.
    // `aria-braillelabel` stays as MathJax wrote it: ARIA exposes it only
    // alongside an accessible name, so on a nameless element it is inert and a
    // braille display renders the text added above instead.
    speech.removeAttribute("aria-label");
    speech.removeAttribute("role");
    speech.removeAttribute("aria-roledescription");
    speech.removeAttribute("aria-brailleroledescription");
}

/**
 * Rewrites every MathJax expression at or under `node` whose speech string has
 * been attached but not yet turned into text. `node` itself is considered,
 * because MathJax appends the `<mjx-speech>` straight to the expression's
 * container: it is often the added node a mutation record reports, with no
 * subtree to search.
 */
function rewriteSpeechTree(node: Element): void {
    rewriteSpeechElement(node);
    for (const speech of node.querySelectorAll(LABELLED_SPEECH_SELECTOR)) {
        rewriteSpeechElement(speech);
    }
}

/**
 * Rewrites what a batch of mutations actually touched, rather than rescanning
 * the page: the work is then proportional to a page's churn instead of to its
 * size, which matters because this observes the whole document and a dragged
 * graph re-renders continuously.
 *
 * A rewrite's own writes come back as a later batch — an appended span, its
 * text, a removed `aria-label` — and none of them match, so the cycle settles
 * rather than feeding itself.
 */
function handleMutations(records: MutationRecord[]): void {
    for (const record of records) {
        if (record.type === "attributes") {
            // A label written onto an element already in the page. Only that
            // one element gained a label, so there is no subtree to walk.
            rewriteSpeechElement(record.target as Element);
            continue;
        }
        // MathJax labels an `<mjx-speech>` before putting it in the page, and
        // replaces the whole element to change what it says, so an added node —
        // the speech element itself, or a container holding it — is what this
        // mostly sees.
        for (const added of record.addedNodes) {
            if (added.nodeType === Node.ELEMENT_NODE) {
                rewriteSpeechTree(added as Element);
            }
        }
    }
}

/**
 * The installed observer, held both as the "already started" flag and as a
 * reference keeping it alive for the life of the page.
 */
let observer: MutationObserver | null = null;

/**
 * Starts exposing MathJax speech as text across the page, and keeps doing it as
 * math is typeset, retypeset, and as speech strings arrive. Calling it again is
 * a no-op, so at most one observer runs per copy of this module — and in
 * practice one per realm, since the only caller is `loadMathJax`, whose single
 * memoized promise per realm means only the first copy loaded gets that far.
 *
 * Does nothing outside a browser, which is what keeps it inert under the
 * loader's Node-environment unit tests.
 */
export function startExposingMathSpeechAsText(): void {
    if (observer || typeof MutationObserver === "undefined") {
        return;
    }
    const root = document.body ?? document.documentElement;
    if (!root) {
        return;
    }

    rewriteSpeechTree(root);

    observer = new MutationObserver(handleMutations);
    observer.observe(root, {
        subtree: true,
        childList: true,
        attributes: true,
        // Filtering to the one attribute keeps the observer off the far busier
        // attribute traffic of a dragged graph.
        attributeFilter: ["aria-label"],
    });
}
