import type { StylePalette } from "./types";

/**
 * A cool-hued palette of blues, teals, and greens. Light-mode anchor colors
 * were tuned with a CVD-simulation + CIEDE2000 analysis so that no two
 * styles fall below dE 9 for typical vision; because the palette is
 * deliberately a single hue family, red-green color vision deficiencies
 * compress it further, and the varied marker shapes and line styles carry
 * the distinction there (colorblind readers may prefer the `okabeito`
 * palette, whose hues are chosen for CVD separation).
 *
 * Dark-mode colors are pinned rather than derived: the automatic derivation
 * lightens every color to just past the contrast threshold, which flattens
 * the lightness ladder the light-mode anchors were tuned for. Each pinned
 * value keeps the style's hue, clears WCAG AA for text (4.5:1 on the dark
 * canvas), and restores the lightness spread. `*Word` descriptors are
 * derived at expansion time, except where the nearest-anchor word matcher
 * misnames a color (it has no notion of teal, for instance); those styles pin
 * explicit words.
 */
export const oceanPalette: StylePalette = {
    name: "ocean",
    description:
        "Cool blues, teals, and greens with varied marker shapes and line styles.",
    styles: {
        1: {
            lineColor: "#1c3fae",
            markerColor: "#1c3fae",
            fillColor: "#1c3fae",
            textColor: "#1c3fae",
            highContrastColor: "#1c3fae",
            textColorDarkMode: "#5879e4",
            lineWidth: 4,
            markerStyle: "circle",
        },
        2: {
            lineColor: "#00695f",
            markerColor: "#00695f",
            fillColor: "#00695f",
            textColor: "#00695f",
            highContrastColor: "#00695f",
            lineColorWord: "teal",
            markerColorWord: "teal",
            fillColorWord: "teal",
            textColorWord: "teal",
            highContrastColorWord: "teal",
            lineColorDarkMode: "#00b3a1",
            markerColorDarkMode: "#00b3a1",
            fillColorDarkMode: "#00b3a1",
            textColorDarkMode: "#00b3a1",
            lineColorWordDarkMode: "teal",
            markerColorWordDarkMode: "teal",
            fillColorWordDarkMode: "teal",
            textColorWordDarkMode: "teal",
            highContrastColorWordDarkMode: "teal",
            lineWidth: 2,
            markerStyle: "square",
        },
        3: {
            lineColor: "#1e7145",
            markerColor: "#1e7145",
            fillColor: "#1e7145",
            textColor: "#1e7145",
            highContrastColor: "#1e7145",
            lineColorDarkMode: "#37a568",
            markerColorDarkMode: "#37a568",
            fillColorDarkMode: "#37a568",
            textColorDarkMode: "#37a568",
            lineWidth: 3,
            markerStyle: "triangle",
        },
        4: {
            lineColor: "#00648f",
            markerColor: "#00648f",
            fillColor: "#00648f",
            textColor: "#00648f",
            highContrastColor: "#00648f",
            lineColorWord: "cyan",
            markerColorWord: "cyan",
            fillColorWord: "cyan",
            textColorWord: "cyan",
            highContrastColorWord: "cyan",
            lineColorDarkMode: "#53c1f0",
            markerColorDarkMode: "#53c1f0",
            fillColorDarkMode: "#53c1f0",
            textColorDarkMode: "#53c1f0",
            lineColorWordDarkMode: "cyan",
            markerColorWordDarkMode: "cyan",
            fillColorWordDarkMode: "cyan",
            textColorWordDarkMode: "cyan",
            highContrastColorWordDarkMode: "cyan",
            lineWidth: 2,
            markerStyle: "diamond",
        },
        5: {
            lineColor: "#6a5fdd",
            markerColor: "#6a5fdd",
            fillColor: "#6a5fdd",
            textColor: "#6a5fdd",
            highContrastColor: "#6a5fdd",
            lineColorDarkMode: "#a89df0",
            markerColorDarkMode: "#a89df0",
            fillColorDarkMode: "#a89df0",
            textColorDarkMode: "#a89df0",
            lineWidth: 2,
            markerStyle: "plus",
        },
        6: {
            lineColor: "#4a5e77",
            markerColor: "#4a5e77",
            fillColor: "#4a5e77",
            textColor: "#4a5e77",
            highContrastColor: "#4a5e77",
            lineColorWord: "slategray",
            markerColorWord: "slategray",
            fillColorWord: "slategray",
            textColorWord: "slategray",
            highContrastColorWord: "slategray",
            lineColorDarkMode: "#8fa3bd",
            markerColorDarkMode: "#8fa3bd",
            fillColorDarkMode: "#8fa3bd",
            textColorDarkMode: "#8fa3bd",
            lineColorWordDarkMode: "slategray",
            markerColorWordDarkMode: "slategray",
            fillColorWordDarkMode: "slategray",
            textColorWordDarkMode: "slategray",
            highContrastColorWordDarkMode: "slategray",
            lineWidth: 2,
            markerStyle: "cross",
        },
        7: {
            lineColor: "#1d4655",
            markerColor: "#1d4655",
            fillColor: "#1d4655",
            textColor: "#1d4655",
            highContrastColor: "#1d4655",
            lineColorWord: "steelblue",
            markerColorWord: "steelblue",
            fillColorWord: "steelblue",
            textColorWord: "steelblue",
            highContrastColorWord: "steelblue",
            lineColorDarkMode: "#4f92b8",
            markerColorDarkMode: "#4f92b8",
            fillColorDarkMode: "#4f92b8",
            textColorDarkMode: "#4f92b8",
            lineColorWordDarkMode: "steelblue",
            markerColorWordDarkMode: "steelblue",
            fillColorWordDarkMode: "steelblue",
            textColorWordDarkMode: "steelblue",
            highContrastColorWordDarkMode: "steelblue",
            lineWidth: 3,
            lineStyle: "dashed",
            markerStyle: "circle",
        },
        8: {
            lineColor: "#6b7480",
            markerColor: "#6b7480",
            fillColor: "#6b7480",
            textColor: "#6b7480",
            highContrastColor: "#6b7480",
            lineColorDarkMode: "#d5dce2",
            markerColorDarkMode: "#d5dce2",
            fillColorDarkMode: "#d5dce2",
            textColorDarkMode: "#d5dce2",
            lineWidth: 1,
            lineStyle: "dotted",
            markerStyle: "square",
        },
    },
};
