import type { StylePalette } from "./types";

/**
 * Paul Tol's "muted" qualitative palette (https://personal.sron.nl/~pault/),
 * the largest of the built-in colorblind-aware sets (nine styles). Its three
 * yellow-green members (green, olive, sand) compress under red-green CVD
 * more than the okabeito or tolbright hues do; the lightness ladder and the
 * marker-shape variation carry the distinction there.
 *
 * Light-mode anchors are the canonical colors wherever they meet Doenet's
 * contrast thresholds on white (3:1 as a graphic, 4.5:1 as text) and are
 * darkened chromaticity-preserving where they do not, with further-darkened
 * text variants where a graphic anchor sits below 4.5:1. Dark mode pins the
 * canonical colors wherever they clear the thresholds on the dark canvas.
 * Verified with a Machado-model CVD simulation + CIEDE2000 analysis; marker
 * shapes and line styles vary across styles so distinctions never rest on
 * color alone.
 */
export const tolMutedPalette: StylePalette = {
    name: "tolmuted",
    description:
        "Nine colorblind-friendly muted styles from Paul Tol's muted palette, with varied marker shapes and line styles.",
    styles: {
        1: {
            lineColor: "#332288",
            markerColor: "#332288",
            fillColor: "#332288",
            highContrastColor: "#332288",
            lineColorWord: "indigo",
            markerColorWord: "indigo",
            fillColorWord: "indigo",
            highContrastColorWord: "indigo",
            lineColorDarkMode: "#8a86e8",
            markerColorDarkMode: "#8a86e8",
            fillColorDarkMode: "#8a86e8",
            lineColorWordDarkMode: "indigo",
            markerColorWordDarkMode: "indigo",
            fillColorWordDarkMode: "indigo",
            highContrastColorWordDarkMode: "indigo",
            lineWidth: 4,
            markerStyle: "circle",
        },
        2: {
            lineColor: "#669ab5",
            markerColor: "#669ab5",
            fillColor: "#669ab5",
            textColor: "#507a90",
            highContrastColor: "#507a90",
            lineColorDarkMode: "#88ccee",
            markerColorDarkMode: "#88ccee",
            fillColorDarkMode: "#88ccee",
            textColorDarkMode: "#88ccee",
            lineWidth: 2,
            markerStyle: "square",
        },
        3: {
            lineColor: "#41a393",
            markerColor: "#41a393",
            fillColor: "#41a393",
            textColor: "#328175",
            highContrastColor: "#328175",
            lineColorWord: "teal",
            markerColorWord: "teal",
            fillColorWord: "teal",
            textColorWord: "teal",
            highContrastColorWord: "teal",
            lineColorDarkMode: "#44aa99",
            markerColorDarkMode: "#44aa99",
            fillColorDarkMode: "#44aa99",
            textColorDarkMode: "#44aa99",
            lineColorWordDarkMode: "teal",
            markerColorWordDarkMode: "teal",
            fillColorWordDarkMode: "teal",
            textColorWordDarkMode: "teal",
            highContrastColorWordDarkMode: "teal",
            lineWidth: 3,
            markerStyle: "triangle",
        },
        4: {
            lineColor: "#117733",
            markerColor: "#117733",
            fillColor: "#117733",
            textColor: "#117733",
            highContrastColor: "#117733",
            lineColorDarkMode: "#117733",
            markerColorDarkMode: "#117733",
            fillColorDarkMode: "#117733",
            textColorDarkMode: "#548a5f",
            lineWidth: 2,
            markerStyle: "diamond",
        },
        5: {
            lineColor: "#989833",
            markerColor: "#989833",
            fillColor: "#989833",
            textColor: "#787827",
            highContrastColor: "#787827",
            lineColorWord: "olive",
            markerColorWord: "olive",
            fillColorWord: "olive",
            textColorWord: "olive",
            highContrastColorWord: "olive",
            lineColorDarkMode: "#999933",
            markerColorDarkMode: "#999933",
            fillColorDarkMode: "#999933",
            textColorDarkMode: "#999933",
            lineColorWordDarkMode: "olive",
            markerColorWordDarkMode: "olive",
            fillColorWordDarkMode: "olive",
            textColorWordDarkMode: "olive",
            highContrastColorWordDarkMode: "olive",
            lineWidth: 2,
            markerStyle: "triangleDown",
        },
        6: {
            lineColor: "#867c46",
            markerColor: "#867c46",
            fillColor: "#867c46",
            textColor: "#7f7542",
            highContrastColor: "#7f7542",
            lineColorWord: "tan",
            markerColorWord: "tan",
            fillColorWord: "tan",
            textColorWord: "tan",
            highContrastColorWord: "tan",
            lineColorDarkMode: "#ddcc77",
            markerColorDarkMode: "#ddcc77",
            fillColorDarkMode: "#ddcc77",
            textColorDarkMode: "#ddcc77",
            lineColorWordDarkMode: "tan",
            markerColorWordDarkMode: "tan",
            fillColorWordDarkMode: "tan",
            textColorWordDarkMode: "tan",
            highContrastColorWordDarkMode: "tan",
            lineWidth: 2,
            markerStyle: "triangleLeft",
        },
        7: {
            lineColor: "#cc6677",
            markerColor: "#cc6677",
            fillColor: "#cc6677",
            textColor: "#b35968",
            highContrastColor: "#b35968",
            lineColorWord: "pink",
            markerColorWord: "pink",
            fillColorWord: "pink",
            textColorWord: "pink",
            highContrastColorWord: "pink",
            lineColorDarkMode: "#cc6677",
            markerColorDarkMode: "#cc6677",
            fillColorDarkMode: "#cc6677",
            textColorDarkMode: "#cc6677",
            lineColorWordDarkMode: "pink",
            markerColorWordDarkMode: "pink",
            fillColorWordDarkMode: "pink",
            textColorWordDarkMode: "pink",
            highContrastColorWordDarkMode: "pink",
            lineWidth: 3,
            lineStyle: "dashed",
            markerStyle: "triangleRight",
        },
        8: {
            lineColor: "#882255",
            markerColor: "#882255",
            fillColor: "#882255",
            textColor: "#882255",
            highContrastColor: "#882255",
            lineColorWord: "maroon",
            markerColorWord: "maroon",
            fillColorWord: "maroon",
            textColorWord: "maroon",
            highContrastColorWord: "maroon",
            lineColorDarkMode: "#924b69",
            markerColorDarkMode: "#924b69",
            fillColorDarkMode: "#924b69",
            textColorDarkMode: "#a17083",
            lineColorWordDarkMode: "maroon",
            markerColorWordDarkMode: "maroon",
            fillColorWordDarkMode: "maroon",
            textColorWordDarkMode: "maroon",
            highContrastColorWordDarkMode: "maroon",
            lineWidth: 1,
            lineStyle: "dotted",
            markerStyle: "circle",
        },
        9: {
            lineColor: "#aa4499",
            markerColor: "#aa4499",
            fillColor: "#aa4499",
            textColor: "#aa4499",
            highContrastColor: "#aa4499",
            lineColorDarkMode: "#aa4499",
            markerColorDarkMode: "#aa4499",
            fillColorDarkMode: "#aa4499",
            textColorDarkMode: "#b262a3",
            lineWidth: 2,
            lineStyle: "dashed",
            markerStyle: "square",
        },
    },
};
