/**
 * Build the `web`-target math-expressions WASM from the `vendor/math-expressions`
 * submodule and inline it into `src/generated/wasm-bytes.ts` as base64.
 *
 * Inlining (rather than shipping a sibling `.wasm` asset) mirrors what
 * `packages/doenetml-worker/src/CoreWorker.ts` does for
 * `lib_doenetml_worker_bg.wasm`: the bytes travel inside the JS bundle, so the
 * module instantiates with `WebAssembly.instantiate(buffer, imports)` and needs
 * no `fetch` at all. That matters because `fetch` is blocked for blob/data URLs
 * in the VS Code web-worker extension host (DoenetML issue #1375), and because
 * one inlined artifact behaves identically under Vitest/node and in the browser.
 *
 * There is only one engine, so this always runs and a Rust toolchain is required
 * to build the repo (`rustup target add wasm32-unknown-unknown` plus a
 * `wasm-bindgen-cli` matching the submodule's pinned `wasm-bindgen`).
 */
import { execFileSync } from "node:child_process";
import {
    copyFileSync,
    existsSync,
    mkdirSync,
    readFileSync,
    writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, "..");
const REPO = resolve(PKG, "../..");
const SUBMODULE = resolve(REPO, "vendor/math-expressions");
const RS_WASM = resolve(SUBMODULE, "packages/math-expressions-rs-wasm");
const PKG_OUT = resolve(RS_WASM, "pkg");
const GENERATED = resolve(PKG, "src/generated");
const OUT_FILE = resolve(GENERATED, "wasm-bytes.ts");

const HEADER = `// GENERATED by scripts/build-wasm.mjs — do not edit, do not commit.\n`;

if (!existsSync(resolve(SUBMODULE, "Cargo.toml"))) {
    throw new Error(
        "@doenet/math: the vendor/math-expressions submodule is not checked out. " +
            "Run `git submodule update --init --recursive`.",
    );
}

// Single source of truth for the wasm build lives in the submodule; we only
// choose the target. `web` (not `nodejs`) because the web target emits ESM with
// both an async `default()` and a synchronous `initSync()`, and we drive it from
// bytes in every realm.
execFileSync("bash", [resolve(RS_WASM, "build-wasm.sh"), "web", "pkg"], {
    stdio: "inherit",
    cwd: RS_WASM,
});

const wasm = readFileSync(resolve(PKG_OUT, "math_expressions_wasm_bg.wasm"));
mkdirSync(GENERATED, { recursive: true });

// Copy the wasm-bindgen glue in rather than aliasing straight into the
// submodule's `pkg/`. wireit refuses to track an output outside the package, so
// leaving it there made this script — and therefore every downstream build in
// the repo — uncacheable. The glue is self-contained (no relative imports), so
// a copy is all it takes. `vite.config.ts` aliases `math-expressions-wasm-glue`
// here.
for (const name of ["math_expressions_wasm.js", "math_expressions_wasm.d.ts"]) {
    copyFileSync(resolve(PKG_OUT, name), resolve(GENERATED, name));
}

writeFileSync(
    OUT_FILE,
    HEADER +
        `// ${wasm.byteLength} bytes of wasm, base64-encoded.\n` +
        // The `: string` annotation is load-bearing. Without it TypeScript
        // infers a string-literal type holding all ~2.2 million base64
        // characters, and materializes it on every type-check and in every
        // editor session that touches this package.
        `export const WASM_BASE64: string =\n    "${wasm.toString("base64")}";\n` +
        `export const WASM_BYTE_LENGTH = ${wasm.byteLength};\n`,
);

console.log(
    `@doenet/math: inlined ${(wasm.byteLength / 1024 / 1024).toFixed(2)} MiB of wasm ` +
        `into src/generated/wasm-bytes.ts`,
);
