/**
 * Inline the `web`-target math-expressions WASM into
 * `src/generated/wasm-bytes.ts` as base64, and copy the wasm-bindgen glue
 * beside it.
 *
 * The binary and the glue are read out of the published `math-expressions`
 * package (a dependency of this one), which ships both wasm-bindgen targets in
 * its tarball. Nothing is compiled here: this package needs no Rust toolchain,
 * and the bytes every build inlines are the ones the lockfile pins, so a local
 * bundle and a CI bundle carry the same core. They did not before — this
 * script used to run `cargo` against a git submodule, and two machines could
 * produce binaries of different sizes from the same source.
 *
 * Inlining (rather than referencing the `.wasm` the package ships) mirrors what
 * `packages/doenetml-worker/src/CoreWorker.ts` does for
 * `lib_doenetml_worker_bg.wasm`: the bytes travel inside the JS bundle, so the
 * module instantiates with `WebAssembly.instantiate(buffer, imports)` and needs
 * no `fetch` at all. That matters because `fetch` is blocked for blob/data URLs
 * in the VS Code web-worker extension host (DoenetML issue #1375), and because
 * one inlined artifact behaves identically under Vitest/node and in the
 * browser. A consumer of the published `@doenet/doenetml` gets the other
 * arrangement — the `.wasm` fetched as an ordinary asset — and
 * `packages/doenetml/src/utils/mathWasm.ts` is where that difference lives.
 *
 * `web`, not `nodejs`: the web target emits ESM with both an async `default()`
 * and a synchronous `initSync()`, and we drive it from bytes in every realm.
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, "..");
const GENERATED = resolve(PKG, "src/generated");
const OUT_FILE = resolve(GENERATED, "wasm-bytes.ts");

const HEADER = `// GENERATED by scripts/build-wasm.mjs — do not edit, do not commit.\n`;

// Resolved through the package's own `exports` map rather than by joining a
// path into `node_modules`: npm may hoist `math-expressions` to the workspace
// root or nest it here depending on what else in the tree wants it, and the
// root copy is a symlink to *this* package (every consumer declares
// `"math-expressions": "file:../math"`, which is the whole point of the seam).
// `createRequire` anchored here follows the same rules node will, so it finds
// the registry package this one depends on rather than the alias.
const require = createRequire(import.meta.url);
const wasmPath =
    require.resolve("math-expressions/wasm-web/math_expressions_wasm_bg.wasm");
const gluePath =
    require.resolve("math-expressions/wasm-web/math_expressions_wasm.js");

const wasm = readFileSync(wasmPath);
// The wasm magic number, so a truncated or wrong file fails here rather than
// as an unreadable error inside `WebAssembly.instantiate` at run time.
if (wasm.byteLength < 4 || wasm.readUInt32BE(0) !== 0x0061736d) {
    throw new Error(
        `@doenet/math: ${wasmPath} does not start with WebAssembly's magic ` +
            `number, so it is not a wasm module. Reinstall math-expressions.`,
    );
}

mkdirSync(GENERATED, { recursive: true });

// Copy the glue in rather than aliasing straight into `node_modules`. wireit
// refuses to track an output outside the package, so leaving it there made this
// script — and therefore every downstream build in the repo — uncacheable. The
// glue is self-contained (no relative imports), so a copy is all it takes.
// `vite.config.ts` aliases `math-expressions-wasm-glue` here.
copyFileSync(gluePath, resolve(GENERATED, "math_expressions_wasm.js"));
copyFileSync(
    gluePath.replace(/\.js$/, ".d.ts"),
    resolve(GENERATED, "math_expressions_wasm.d.ts"),
);

writeFileSync(
    OUT_FILE,
    HEADER +
        `// ${wasm.byteLength} bytes of wasm, base64-encoded.\n` +
        // The `: string` annotation is load-bearing. Without it TypeScript
        // infers a string-literal type holding all ~2.2 million base64
        // characters, and materializes it on every type-check and in every
        // editor session that touches this package.
        `export const WASM_BASE64: string =\n    "${wasm.toString("base64")}";\n` +
        `export const WASM_BYTE_LENGTH = ${wasm.byteLength};\n`,
);

console.log(
    `@doenet/math: inlined ${(wasm.byteLength / 1024 / 1024).toFixed(2)} MiB of wasm ` +
        `into src/generated/wasm-bytes.ts`,
);
