// @ts-ignore
import LSPWorker from "@doenet/lsp/language-server.js?worker";
import { initWorker } from "./utils/init-message-connection";
import {
    Diagnostic,
    Position,
    CompletionContext,
} from "vscode-languageserver-protocol/browser";

/**
 * Create a promise with its resolver.
 */
function withResolver<T>() {
    let resolve: (value: T) => void;
    const promise = new Promise<T>((res) => {
        resolve = res;
    });
    return { resolve: resolve!, promise };
}

export class LSP {
    worker?: Worker;
    lspConn?: Awaited<ReturnType<typeof initWorker>>["lspConn"];
    workerConn?: Awaited<ReturnType<typeof initWorker>>["workerConn"];
    versionCounter: Record<string, number> = {};
    diagnosticsSubscribers = new Set<
        (params: { uri: string; diagnostics: Diagnostic[] }) => void
    >();
    diagnosticsHandlerRegistered = false;
    initPromise = withResolver<void>();
    initStatus: "uninitialized" | "initializing" | "initialized" =
        "uninitialized";
    completionTriggers: string[] = [];

    ensureDiagnosticsHandlerRegistered() {
        if (!this.lspConn || this.diagnosticsHandlerRegistered) {
            return;
        }
        this.lspConn.onDiagnostics((params) => {
            for (const subscriber of this.diagnosticsSubscribers) {
                subscriber(params);
            }
        });
        this.diagnosticsHandlerRegistered = true;
    }

    async init() {
        if (this.lspConn) {
            return;
        }
        if (this.initStatus === "uninitialized") {
            this.initStatus = "initializing";
            this.worker = new LSPWorker();
            const { lspConn, workerConn } = await initWorker(this.worker!);
            this.lspConn = lspConn;
            this.workerConn = workerConn;
            this.completionTriggers = this.lspConn.completionTriggers;
            this.ensureDiagnosticsHandlerRegistered();
            this.initPromise.resolve();
            this.initStatus = "initialized";
        }
        if (this.initStatus === "initializing") {
            await this.initPromise.promise;
        }
    }

    onDiagnostics(
        callback: (params: { uri: string; diagnostics: Diagnostic[] }) => void,
    ) {
        this.diagnosticsSubscribers.add(callback);
        this.init()
            .then(() => {
                this.ensureDiagnosticsHandlerRegistered();
            })
            .catch((error) => {
                console.error(
                    "Failed to initialize diagnostics handler",
                    error,
                );
            });
        return () => {
            this.diagnosticsSubscribers.delete(callback);
        };
    }

    async initDocument(uri: string, text: string) {
        if (!this.lspConn) {
            await this.init();
            await this.initDocument(uri, text);
            return;
        }
        this.versionCounter[uri] = 1;
        await this.lspConn.textDocumentOpened({
            textDocument: {
                uri,
                languageId: "doenet",
                version: 1,
                text,
            },
        });
    }

    async closeDocument(uri: string) {
        if (!this.lspConn) {
            await this.init();
            await this.closeDocument(uri);
            return;
        }
        await this.lspConn.textDocumentClosed({
            textDocument: {
                uri,
            },
        });
    }

    async updateDocument(uri: string, text: string) {
        if (!this.lspConn || !this.versionCounter[uri]) {
            await this.initDocument(uri, text);
            return;
        }
        this.versionCounter[uri] += 1;
        await this.lspConn.textDocumentChanged({
            textDocument: {
                uri,
                version: this.versionCounter[uri],
            },
            contentChanges: [
                {
                    text,
                },
            ],
        });
    }

    async getCompletionItems(
        uri: string,
        position: Position,
        context: CompletionContext,
    ) {
        await this.initPromise.promise;
        if (!this.lspConn) {
            console.warn("Cannot get completion items without lspConn");
            return [];
        }
        return await this.lspConn.getCompletion({
            textDocument: { uri },
            position,
            context,
        });
    }

    /**
     * This is a special function just for the Doenet LSP.
     * It allows the client to send additional diagnostics that are not generated by the LSP itself.
     * For example, messages generated by an external instance of Core may be sent here and then delivered
     * by the LSP back to the client.
     */
    async sendAdditionalDiagnostics(
        uri: string,
        additionalDiagnostics: Diagnostic[],
    ): Promise<void> {
        await this.initPromise.promise;
        if (!this.workerConn) {
            console.warn("Cannot send additional diagnostics without lspConn");
            return;
        }
        await this.workerConn.sendRequest("doenet/setAdditionalDiagnostics", {
            uri,
            additionalDiagnostics,
        });
    }
}
