export default {
    componentIndex: "Alphabetical Index",
    componentTypes: "Index by Component Type",
    Sample_Component: {
        display: "hidden",
    },
    archive: {
        display: "hidden",
    },
    ol: { title: "ol" },
    select: { title: "select" },
    selectFromSequence: { title: "selectFromSequence" },
    selectRandomNumbers: { title: "selectRandomNumbers" },
    setup: { title: "setup" },
    sideBySide: { title: "sideBySide" },
    solution: { title: "solution" },
    sort: { title: "sort" },
    styleDefinition: { title: "styleDefinition" },
    subsetOfReals: { title: "subsetOfReals" },
    substitute: { title: "substitute" },
    table: { title: "table" },
    tabular: { title: "tabular" },
    template: { title: "template" },
    title: { title: "title" },
    ul: { title: "ul" },
};
