"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true,
});
exports.mismatchedStartCloseTag =
    exports.incompleteStartCloseTag =
    exports.commentContent =
    exports.Text =
    exports.TagName =
    exports.StartTag =
    exports.StartCloseTag =
    exports.SelfClosingTag =
    exports.OpenTag =
    exports.MissingCloseTag =
    exports.MismatchedCloseTag =
    exports.Is =
    exports.Element =
    exports.Document =
    exports.Comment =
    exports.CloseTag =
    exports.AttributeValue =
    exports.AttributeName =
    exports.Attribute =
        void 0;
// This file was generated by lezer-generator. You probably shouldn't edit it.
const StartTag = 1,
    StartCloseTag = 2,
    MissingCloseTag = 3,
    mismatchedStartCloseTag = 4,
    incompleteStartCloseTag = 5,
    commentContent = 27,
    Document = 6,
    Text = 7,
    Comment = 8,
    Element = 9,
    OpenTag = 10,
    TagName = 11,
    Attribute = 12,
    AttributeName = 13,
    Is = 14,
    AttributeValue = 15,
    MismatchedCloseTag = 16,
    CloseTag = 17,
    SelfClosingTag = 18;
exports.SelfClosingTag = SelfClosingTag;
exports.CloseTag = CloseTag;
exports.MismatchedCloseTag = MismatchedCloseTag;
exports.AttributeValue = AttributeValue;
exports.Is = Is;
exports.AttributeName = AttributeName;
exports.Attribute = Attribute;
exports.TagName = TagName;
exports.OpenTag = OpenTag;
exports.Element = Element;
exports.Comment = Comment;
exports.Text = Text;
exports.Document = Document;
exports.commentContent = commentContent;
exports.incompleteStartCloseTag = incompleteStartCloseTag;
exports.mismatchedStartCloseTag = mismatchedStartCloseTag;
exports.MissingCloseTag = MissingCloseTag;
exports.StartCloseTag = StartCloseTag;
exports.StartTag = StartTag;
