export interface ParseOptions {
    filename?: string;
    startRule?: "start";
    tracer?: any;
    [key: string]: any;
}
export type ParseFunction = <Options extends ParseOptions>(
    input: string,
    options?: Options,
) => Options extends { startRule: infer StartRule }
    ? StartRule extends "start"
        ? Top
        : Top
    : Top;

// These types were autogenerated by ts-pegjs
export type Top = (Macro | FunctionMacro | Text)[];
export type Ident = string;
export type ScopedIdent = string;
export type PathPart = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & { type: "pathPart"; name: Ident; index: PropIndex[] };
export type ScopedPathPart = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & { type: "pathPart"; name: ScopedIdent; index: PropIndex[] };
export type EmptyPathPart = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & { type: "pathPart"; name: ""; index: [] };
export type FullPath =
  | [EmptyPathPart, ...ScopedPathPartOrDD[]]
  | [ScopedPathPartOrDD, ...ScopedPathPartOrDD[]];
export type ScopedPathPartOrDD =
  | ScopedPathPart
  | ({
      position: {
        start: { offset: number; line: number; column: number };
        end: { offset: number; line: number; column: number };
      };
    } & { type: "pathPart"; name: ".."; index: [] });
export type PropAccess = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & Omit<PartialPathMacro, "type"> & { type: "propAccess" };
export type ScopedPropAccess = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & Omit<ScopedPartialPathMacro, "type"> & { type: "propAccess" };
export type Macro = FullPathMacro | PartialPathMacro;
export type PartialPathMacro = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & {
  type: "macro";
  path: [PathPart];
  attributes: PropAttrs | null;
  accessedProp: PropAccess | null;
};
export type ScopedPartialPathMacro = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & {
  type: "macro";
  path: [ScopedPathPart];
  attributes: PropAttrs | null;
  accessedProp: ScopedPropAccess | null;
};
export type FullPathMacro = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & {
  type: "macro";
  path: FullPath;
  attributes: PropAttrs | null;
  accessedProp: ScopedPropAccess | null;
};
export type FunctionMacro =
  | ({
      position: {
        start: { offset: number; line: number; column: number };
        end: { offset: number; line: number; column: number };
      };
    } & { type: "function"; path: FullPath; input: FunctionInput | null })
  | ({
      position: {
        start: { offset: number; line: number; column: number };
        end: { offset: number; line: number; column: number };
      };
    } & { type: "function"; path: [PathPart]; input: FunctionInput | null });
export type FunctionInput = FunctionArgumentList;
export type FunctionArgumentList = [FunctionArgument, ...FunctionArgument[]];
export type FunctionArgument =
  | Macro
  | FunctionMacro
  | TextWithoutClosingParenOrComma
  | EmptyString;
export type PropAttrs = Attr[];
export type PropIndex = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & { type: "index"; value: Macro | TextWithoutClosingSquareBrace };
export type Attr =
  | ({
      position: {
        start: { offset: number; line: number; column: number };
        end: { offset: number; line: number; column: number };
      };
    } & { type: "attribute"; name: AttrName; children: AttrValue })
  | ({
      position: {
        start: { offset: number; line: number; column: number };
        end: { offset: number; line: number; column: number };
      };
    } & { type: "attribute"; name: AttrName; children: [] });
export type AttrName = string;
export type AttrValue =
  | (Macro | FunctionMacro | TextWithoutDoubleQuote)[]
  | (Macro | FunctionMacro | TextWithoutQuote)[];
export type Text = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & { type: "text"; value: string };
export type EmptyString = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & {
  type: "text";
  value: "";
  position: {
    source: string | undefined;
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
};
export type TextWithoutClosingParenOrComma = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & { type: "text"; value: string };
export type TextWithoutQuote = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & { type: "text"; value: string };
export type TextWithoutClosingSquareBrace = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & { type: "text"; value: string };
export type TextWithoutDoubleQuote = {
  position: {
    start: { offset: number; line: number; column: number };
    end: { offset: number; line: number; column: number };
  };
} & { type: "text"; value: string };
export type _ = string;
export type EOF = undefined;