# Bavarian (Boarisch) viewer chrome. Translated from `locales/en/chrome.ftl`,
# which is the source of truth: `lint:i18n` rejects a key that does not exist
# there, and reports a key that exists there but not here as missing coverage.
#
# Message ids are never translated — only the text to the right of `=`.
#
# UNREVIEWED SEED. Machine-generated, pending review by a speaker (#1521).
# Correct anything here freely; nothing in it was written by a translator.
#
# **Script and orthography.** Latin script, German-based spelling. **Bavarian
# has no codified standard**: there is no orthography board, no official
# dictionary and no agreed norm, and every writer spells a little differently.
# This file follows the practice of the **Bavarian Wikipedia (bar.wikipedia)**,
# which is the largest body of written Bavarian there is, in its **Central
# Bavarian / Austro-Bavarian** register — the Munich–Vienna belt, not Northern
# Bavarian of the Oberpfalz and not the Alemannic-influenced far west. A
# reviewer from another valley will want other spellings; that is expected, and
# the fix is a `localeResources` catalog of their own rather than a file that
# ends up in two varieties at once. Unlike `locales/gsw`, **ß is used**: it is
# part of the German-based spelling both Bavaria and Austria write.
#
# **Do not edit this file toward Standard German.** The differing words are the
# catalog, not mistakes: «ned» for «nicht», «is» for «ist», «san» for «sind»,
# «hod» for «hat», «ko» for «kann», «kenna» for «können», «muaß» for «muss»,
# «koa» for «kein», «nix» for «nichts», «vo» for «von», «wia» for «wie», «wei»
# for «weil», «oda» for «oder», «zruck» for «zurück», «weida» for «weiter»,
# «Fehla» for «Fehler», «Seitn» for «Seite», «Zeiln» for «Zeile», «Antwuat»
# for «Antwort», «zoagn» for «zeigen», «foisch» for «falsch». A reviewer who
# normalizes these has produced a second copy of `locales/de`.
#
# **There is no simple past.** Bavarian lost the preterite entirely and uses
# the perfect throughout, which is why every English past tense comes out here
# as a perfect: «hod ned gladn wern kina», never a preterite.
#
# **What is borrowed.** The everyday words — colours, buttons, connectives,
# the copula and the negator — are Bavarian. The technical nouns are Standard
# German, lightly respelled («Komponentn», «Attribut», «Dokument»,
# «Barrierefreiheit»), because Standard German is the language a Bavarian
# speaker is schooled in and there is no Bavarian technical register to draw
# on. «Guadschrift» for *credit* is the one place a German word («Gutschrift»)
# was preferred to the schoolroom «Anrechnung», because it is the form actually
# said aloud.
#
# **Counts.** CLDR has **no plural data for `bar` at all**, so no plural
# category can be selected here: this catalog writes **no** `[zero]`, `[one]`,
# `[two]`, `[few]` or `[many]` branch anywhere in any of its four files, and
# every count reads with a single form. The numeric literal `[0]` in
# `attempts-remaining` is a different
# mechanism — an exact-value match, not a plural category — and stays.
#
# **Digits.** Every number renders in Latin digits, so the digits written into
# prose here are Latin digits too.
#
# **Weakest first.** A reviewer should attack the technical nouns first: they
# are German with a Bavarian coat of paint and a speaker will have better
# words for several of them. After that, the verb forms in the long error
# sentences, where a written Bavarian periphrastic perfect is easy to get
# subtly wrong.
#
# Register: impersonal throughout — infinitives and bare nouns, no «du» and no
# «Sie» form, the same policy `locales/de` and `locales/gsw` follow.


## Answer submission

answer-checking = Wead prüaft …
answer-submitting = Wead gschickt …
answer-checking-status = D Antwuat wead prüaft
answer-submitting-status = D Antwuat wead gschickt
answer-correct = Richtig
answer-incorrect = Foisch
answer-response-saved = Antwuat gspeichat
answer-percent-credit = { $percent } % Guadschrift
answer-percent-correct = { $percent } % richtig
answer-percent-short = { $percent } %
max-credit-available = Am moastn zum Hoin: { $percent } %
# CLDR has no plural rules for `bar`, so there is no category branch: one form
# for every count. The `[0]` key is an exact numeric match, not a category, and
# stays as it is.
attempts-remaining =
    { $count ->
        [0] koa Versuach mehr übri
       *[other] no { $count } Versuach übri
    }
validation-correct = (Richtig)
validation-incorrect = (Foisch)
validation-partially-correct = (Teuweis richtig)
answer-show-responses = { $count } Antwuatn auf { $answerId } zoagn

## Disclosure panels

feedback-heading = Rückmeldung
collapsible-click-to-open = (zum Aufmacha klickn)
collapsible-click-to-close = (zum Zuamacha klickn)
collapsible-initializing = Wead gstart …
footnote-show = D Fuaßnotn zoagn
footnote-hide = D Fuaßnotn ausblendn
description-more-information = mehr Informationa

## Controls

slider-previous = Zruck
slider-next = Weida
keyboard-open = Tastatur aufmacha
keyboard-close = Tastatur zuamacha
choice-input-remove-choice = { $choice } wegnehma
matrix-remove-row = Zeiln wegnehma
matrix-add-row = Zeiln dazuadoa
matrix-remove-column = Spoitn wegnehma
matrix-add-column = Spoitn dazuadoa
subset-add-remove-points = Punkt dazuadoa / wegnehma
subset-toggle-points-intervals = Zwischn Punkt und Intervoi wechsln
subset-move-points = Punkt verschiam
subset-clear = Leam
# A `box` here is one orbital, drawn as a square: «Kastl».
orbital-add-row = Zeiln dazuadoa
orbital-remove-row = Zeiln wegnehma
orbital-add-box = Kastl dazuadoa
orbital-remove-box = Kastl wegnehma
orbital-add-up-arrow = Pfeu auffi dazuadoa
orbital-add-down-arrow = Pfeu owi dazuadoa
orbital-remove-arrow = Pfeu wegnehma
orbital-row-label = Beschriftung fia d Zeiln { $row }
pretzel-answer = Antwuat

## Math input

math-input-preview-region = Vorschau vom mathematischn Ausdruck
math-input-preview = Vorschau
math-input-invalid-expression = Ungüitiga Ausdruck:

## Document status

viewer-initializing = Wead gstart …

## Errors

error-heading = Fehla
error-found-at =
    { $span ->
        [line] Gfundn auf da Zeiln { $startLine }.
       *[lines] Gfundn auf de Zeiln { $startLine }–{ $endLine }.
    }
document-contains-errors = Des Dokument hod Fehla drin!
diagnostic-heading-error = Fehla
diagnostic-heading-warning = Woarnung
diagnostic-heading-information = Info
diagnostic-heading-hint = Hiweis
# `WCAG AA` is the name of the standard and is not translated.
accessibility-heading-level-1 = Verstoß gegn WCAG AA (Barrierefreiheit)
accessibility-heading-level-2 = Hiweis zua Barrierefreiheit
something-went-wrong = Do is ebbas schiafganga.
renderer-load-failed = a Ozeigmodul hod ned gladn wern kina. Bittschee d Seitn nei ladn.
core-start-failed = Des Dokument hod ned gstart wern kina. Bittschee d Seitn nei ladn.
core-start-failed-busy = Des Dokument hod ned gstart wern kina. Es san mehrare Dokument auf oamoi gstart worn, und auf am langsamarn Gerät ko des länga dauan. D Seitn nei ladn ko heifa, sobois de andan Dokument fertig san.
core-start-failed-retry = Des Dokument hod ned gstart wern kina.
core-start-failed-busy-retry = Des Dokument hod ned gstart wern kina. Es san mehrare Dokument auf oamoi gstart worn, und auf am langsamarn Gerät ko des länga dauan.
core-start-retry = Nomoi probian
saved-state-unavailable = Dei gspeichate Arbat hod ned gladn wern kina.
