# Bavarian (Boarisch) content catalog: the prose the core computes into the
# document. Selected by `documentLocale` — the language the activity was
# written in.
#
# UNREVIEWED SEED. Machine-generated, pending review by a speaker (#1521).
# Correct anything here freely; nothing in it was written by a translator.
#
# **Script and orthography.** Latin script, German-based spelling, following
# the practice of the **Bavarian Wikipedia (bar.wikipedia)** in its **Central
# Bavarian / Austro-Bavarian** register. **Bavarian has no codified standard**
# — no orthography board, no official dictionary, no agreed norm — so this is
# one written variety among several rather than *the* spelling. Unlike
# `locales/gsw`, **ß is used**: it belongs to the German-based spelling both
# Bavaria and Austria write. See `chrome.ftl` for the full note.
#
# **Do not edit this file toward Standard German**: «ned», «is», «san», «hod»,
# «ko», «koa», «nix», «oda», «Kroas» for «Kreis», «Zoi» for «Zahl» are the
# catalog, not typos.
#
# **What is borrowed.** The colour words, the connectives and the everyday
# nouns are Bavarian. The geometry and chemistry vocabulary is Standard
# German, lightly respelled — that is the register a Bavarian speaker is
# schooled in, and there is no Bavarian mathematical tradition to draw on.
#
# **Counts.** CLDR has **no plural data for `bar`**, so no plural category can
# be selected: there is **no** `[zero]`, `[one]`, `[two]`, `[few]` or `[many]`
# branch anywhere in this file. Nothing here counts, so nothing is lost.
#
# **Digits.** Every number renders in Latin digits.
#
# **Adjective order and agreement.** Bavarian inflects the way German does:
# the attributive adjective goes **before** the noun and takes an ending that
# depends on the noun's gender and on the case its position governs. So the
# adjectives here are really agreed, not invariant. Every one selects on
# `$role` first and then, where it matters, on `$gender`:
#
#   standalone          no article, so the strong endings: `-a` m, `-e` f,
#                       `-s` n («a dicka Strich», «a dicke Linie»,
#                       «a dicks Quadrat»)
#   border-clause       after «mit am» / «und am», which govern the dative:
#                       `-n`, the same for every gender
#   background-clause   after «auf am», dative again: `-n`
#   text-clause         predicative, where nothing is inflected at all: the
#                       bare stem, «rod auf am gäibn Hintagrund»
#
# As in `locales/gsw`, the strong dative `-em` that Standard German writes
# («mit dickem Rand») is not available: the article is used instead, «mit am
# dickn Rand», so the dative ending is a flat `-n` and the article is written
# into the composition message.
#
# **The periodic table is left to fall back to English.** `element-name` and
# `element-anion-name` are deliberately absent. There is no published Bavarian
# list of the 118 elements, and there will not be one: chemistry in Bavaria
# and Austria is taught in Standard German out of Standard German textbooks,
# so the table a pupil actually meets is `locales/de`'s. A reviewer who wants
# these filled in should copy `locales/de` deliberately rather than have this
# seed invent dialect element names nobody writes.


## Style vocabulary

color =
    .black =
        { $role ->
            [border-clause] schwoazn
            [background-clause] schwoazn
            [text-clause] schwoaz
           *[standalone]
                { $gender ->
                    [f] schwoaze
                    [n] schwoazs
                   *[m] schwoaza
                }
        }
    .white =
        { $role ->
            [border-clause] weißn
            [background-clause] weißn
            [text-clause] weiß
           *[standalone]
                { $gender ->
                    [f] weiße
                    [n] weißes
                   *[m] weißa
                }
        }
    .gray =
        { $role ->
            [border-clause] graun
            [background-clause] graun
            [text-clause] grau
           *[standalone]
                { $gender ->
                    [f] graue
                    [n] graus
                   *[m] graua
                }
        }
    .red =
        { $role ->
            [border-clause] rodn
            [background-clause] rodn
            [text-clause] rod
           *[standalone]
                { $gender ->
                    [f] rode
                    [n] rods
                   *[m] roda
                }
        }
    .orange =
        { $role ->
            [border-clause] orangefarbign
            [background-clause] orangefarbign
            [text-clause] orangefarbig
           *[standalone]
                { $gender ->
                    [f] orangefarbige
                    [n] orangefarbigs
                   *[m] orangefarbiga
                }
        }
    .yellow =
        { $role ->
            [border-clause] gäibn
            [background-clause] gäibn
            [text-clause] gäib
           *[standalone]
                { $gender ->
                    [f] gäibe
                    [n] gäibs
                   *[m] gäiba
                }
        }
    .green =
        { $role ->
            [border-clause] grean
            [background-clause] grean
            [text-clause] grea
           *[standalone]
                { $gender ->
                    [f] greane
                    [n] greans
                   *[m] greana
                }
        }
    .cyan =
        { $role ->
            [border-clause] cyanfarbign
            [background-clause] cyanfarbign
            [text-clause] cyanfarbig
           *[standalone]
                { $gender ->
                    [f] cyanfarbige
                    [n] cyanfarbigs
                   *[m] cyanfarbiga
                }
        }
    .blue =
        { $role ->
            [border-clause] blaun
            [background-clause] blaun
            [text-clause] blau
           *[standalone]
                { $gender ->
                    [f] blaue
                    [n] blaus
                   *[m] blaua
                }
        }
    .purple =
        { $role ->
            [border-clause] violettn
            [background-clause] violettn
            [text-clause] violett
           *[standalone]
                { $gender ->
                    [f] violette
                    [n] violetts
                   *[m] violetta
                }
        }
    .pink =
        { $role ->
            [border-clause] rosafarbign
            [background-clause] rosafarbign
            [text-clause] rosafarbig
           *[standalone]
                { $gender ->
                    [f] rosafarbige
                    [n] rosafarbigs
                   *[m] rosafarbiga
                }
        }
    .brown =
        { $role ->
            [border-clause] braunan
            [background-clause] braunan
            [text-clause] braun
           *[standalone]
                { $gender ->
                    [f] braune
                    [n] brauns
                   *[m] brauna
                }
        }
line-width =
    .thick =
        { $role ->
            [border-clause] dickn
            [background-clause] dickn
            [text-clause] dick
           *[standalone]
                { $gender ->
                    [f] dicke
                    [n] dicks
                   *[m] dicka
                }
        }
    .thin =
        { $role ->
            [border-clause] dünnan
            [background-clause] dünnan
            [text-clause] dünn
           *[standalone]
                { $gender ->
                    [f] dünne
                    [n] dünns
                   *[m] dünna
                }
        }
line-style =
    .dashed =
        { $role ->
            [border-clause] gstrichltn
            [background-clause] gstrichltn
            [text-clause] gstrichlt
           *[standalone]
                { $gender ->
                    [f] gstrichlte
                    [n] gstrichlts
                   *[m] gstrichlta
                }
        }
    .dotted =
        { $role ->
            [border-clause] gpunktltn
            [background-clause] gpunktltn
            [text-clause] gpunktlt
           *[standalone]
                { $gender ->
                    [f] gpunktlte
                    [n] gpunktlts
                   *[m] gpunktlta
                }
        }
# Noun phrases in the dative plural: they follow «mit» and agree with nothing.
fill-style =
    .horizontal = waagrechte Linien
    .vertical = senkrechte Linien
    .diagonal = diagonale Linien
    .backdiagonal = gegnläufige diagonale Linien
    .dots = Punkterl
    .diamonds = Rautn
noun =
    .line = Linie
    .line-segment = Streckn
    .ray = Strahl
    .vector = Vektor
    .curve = Kurvn
    .function = Funktion
    .slope-field = Steigungsfeid
    .vector-field = Vektorfeid
    .parabola = Parabl
    .polyline = Streckenzug
    .polygon = Vieleck
    .triangle = Dreieck
    .rectangle = Rechteck
    .circle = Kroas
    .region = Beroach
    .point = Punkt
    .square = Quadrat
    .diamond = Rautn
    .cross = Kreiz
    .plus = Pluszeichn
# Like German, Bavarian keeps the side count in front of the noun as a
# compound, so the whole thing is one head and there is no tail.
noun-regular-polygon =
    { $part ->
        [tail] { "" }
       *[head] regelmäßigs { $numSides }-Eck
    }
# Besides the nouns above, `$noun` can be `regular-polygon` (which is
# `{ $numSides }-Eck`, neuter) or the head of a phrase the description never
# names: `border` is «da Rand», masculine; `fill` is «d Füllung», feminine;
# `text` is «da Text», masculine; `background` is «da Hintagrund», masculine.
# Three of those four are masculine, which is what the default answers, so
# only `fill` needs a branch of its own.
noun-gender =
    { $noun ->
        [border] m
        [line] f
        [curve] f
        [function] f
        [parabola] f
        [diamond] f
        [fill] f
        [line-segment] f
        [polygon] n
        [triangle] n
        [rectangle] n
        [square] n
        [cross] n
        [plus] n
        [slope-field] n
        [vector-field] n
        [region] m
        [regular-polygon] n
       *[other] m
    }

## Style composition

style-stroke =
    { $parts ->
        [width-style-color] { $width } { $lineStyle } { $color }
        [width-color] { $width } { $color }
        [style-color] { $lineStyle } { $color }
        [width-style] { $width } { $lineStyle }
        [width] { $width }
        [style] { $lineStyle }
       *[color] { $color }
    }
# The adjectives lead and the noun closes the phrase, as in German and in
# English: «dicke gstrichlte rode Linie».
style-with-noun =
    { $parts ->
        [noun-tail] { $description } { $noun } { $nounTail }
       *[noun] { $description } { $noun }
    }
# Only ever said of the shape itself, so it is standalone in every description
# and takes no `$role` branch.
style-filled-word =
    { $gender ->
        [f] gfüllte
        [n] gfüllts
       *[m] gfüllta
    }
style-filled =
    { $parts ->
        [pattern] { $filled } { $color } mit { $pattern }
       *[plain] { $filled } { $color }
    }
style-filled-with-noun =
    { $parts ->
        [pattern] { $filled } { $color } { $noun } mit { $pattern }
        [plain-tail] { $filled } { $color } { $noun } { $nounTail }
        [pattern-tail] { $filled } { $color } { $noun } { $nounTail } mit { $pattern }
       *[plain] { $filled } { $color } { $noun }
    }
# «Rand» is masculine, so the border's adjectives agree with it and not with
# the shape it surrounds. «mit» and «und» govern the dative, which is the
# `border-clause` branch of every adjective — a flat `-n` here, because
# Bavarian has no strong dative `-em` and uses the article instead. Every
# branch therefore takes «am», including the two English leaves the article
# off: a bare dative is not available to write, so keeping the article in all
# four collapses the distinction rather than getting one of them wrong.
style-border-clause =
    { $parts ->
        [with-article] mit am { $border } Rand
        [and] und am { $border } Rand
        [and-article] und am { $border } Rand
       *[with] mit am { $border } Rand
    }
# The fill-pattern words are dative plurals, because their other use is the
# «mit { $pattern }» clause in `style-filled`. So this message supplies a noun
# for them to hang off — «Füllung», feminine, which is the gender `noun-gender`
# answers for `fill`, so the colour agrees with it in both variants.
style-fill =
    { $parts ->
        [pattern] { $color } Füllung mit { $pattern }
       *[plain] { $color } Füllung
    }
style-unfilled = ungfüllt
# «auf am» governs the dative, which is the `background-clause` ending; the
# text colour beside it is predicative, which here is the bare stem. So this
# reads «rod auf am gäibn Hintagrund», where the `textColor` and
# `backgroundColor` variables — the standalone side of the same two words —
# read «roda» and «gäiba».
style-text =
    { $parts ->
        [background] { $color } auf am { $background } Hintagrund
       *[plain] { $color }
    }
style-background-none = koana

## Boolean words

boolean-true = woah
boolean-false = foisch

## Answer buttons

answer-submit-label = Priafa
answer-submit-label-no-correctness = Antwuat schickn

## Sectional blocks

section-name =
    .activity = Aktivität
    .aside = Randbemerkung
    .cascade = Kaskade
    .definition = Definition
    .example = Beispui
    .exercise = Übung
    .exercises = Übunga
    .given-answer = Antwuat
    .note = Åmerkung
    .objectives = Lernzui
    .paragraphs = Absätz
    .part = Teu
    .problem = Aufgab
    .problems = Aufgam
    .proof = Beweis
    .question = Frog
    .section = Obschnitt
    .solution = Lösung
    .task = Aufgab
    .theorem = Sotz
section-title-prefix =
    { $parts ->
        [name] { $sectionName }
        [number] { $sectionNumber }
        [name-title] { $sectionName }{ ": " }
        [number-title] { $sectionNumber }{ ". " }
        [name-number-title] { $sectionName } { $sectionNumber }{ ": " }
       *[name-number] { $sectionName } { $sectionNumber }
    }
hint-title = Tipp

## Tables and figures

table-name =
    { $parts ->
        [numbered] Tabelln { $enumeration }
        [numbered-title] Tabelln { $enumeration }{ ": " }
        [unnumbered-title] Tabelln{ ": " }
       *[unnumbered] Tabelln
    }
figure-name =
    { $parts ->
        [numbered] Obbuidung { $enumeration }
        [numbered-caption] Obbuidung { $enumeration }{ ": " }
        [unnumbered-caption] Obbuidung{ ": " }
       *[unnumbered] Obbuidung
    }

## Paginator controls

paginator-previous = Zruck
paginator-next = Weida
paginator-page = Seitn
paginator-page-status = { $pageLabel } { $currentPage } vo { $numPages }

## Piecewise functions

piecewise-condition-or = oda
piecewise-condition-if = wenn
piecewise-condition-otherwise = sunst

## Chemistry
##
## `element-name` and `element-anion-name` are deliberately absent: they fall
## back to English, and `locales/de` is the parallel text a reviewer should
## copy from. See the header.

ion-name-oxidation-state = { $name } ({ $numeral })
chemistry-invalid-symbol = Ungüitigs chemischs Symbol
chemistry-invalid-ionic-compound = Ungüitige Ionenverbindung

## Inputs embedded in math

math-embedded-input-blank = Lucka
math-embedded-input-blank-ordinal = Lucka { $ordinal } vo { $total }
