# Bavarian (Boarisch) diagnostics. Translated from
# `locales/en/diagnostics.ftl`, which is the source of truth: `lint:i18n`
# rejects a key that does not exist there, and reports a key that exists there
# but not here as missing coverage.
#
# Message ids are never translated — only the text to the right of `=`.
#
# UNREVIEWED SEED. Machine-generated, pending review by a speaker (#1521).
# Correct anything here freely; nothing in it was written by a translator.
#
# **Script and orthography.** Latin script, German-based spelling, following
# the **Bavarian Wikipedia (bar.wikipedia)** in its **Central Bavarian /
# Austro-Bavarian** register. **Bavarian has no codified standard** — no
# orthography board, no official dictionary, no agreed norm — so this is one
# written variety among several. **ß is used**, unlike `locales/gsw`. See
# `chrome.ftl` for the full note.
#
# **Do not edit this file toward Standard German**: «ned» for «nicht», «is»
# for «ist», «san» for «sind», «hod» for «hat», «ko» for «kann», «kina» for
# «können», «muaß» for «muss», «koa» for «kein», «wei» for «weil», «oda» for
# «oder», «Fehla» for «Fehler», «Zoi» for «Zahl», «Kroas» for «Kreis» are the
# catalog, not mistakes.
#
# **There is no simple past.** Bavarian lost the preterite entirely and uses
# the perfect throughout, which is why every past-tense sentence here reads as
# a perfect: «hod ned bestimmt wern kina», never a preterite.
#
# **What is borrowed.** The connectives, the negator and the everyday verbs
# are Bavarian; the mathematical and computing nouns («Komponentn»,
# «Variable», «Intervoi», «Matrix», «Zuastandsvariable») are Standard German
# with a Bavarian coat of paint, because Standard German is the register a
# Bavarian speaker meets mathematics in. That is the weakest part of this
# catalog and where a reviewer should start.
#
# **Counts.** CLDR has **no plural data for `bar` at all**, so no plural
# category can be selected here. This file writes **no** `[zero]`, `[one]`,
# `[two]`, `[few]` or `[many]` branch anywhere, and the English
# singular/plural splits are collapsed into one form —
# `line-segment-attributes-ignored-*`,
# `matches-pattern-parameter-not-in-pattern`, `attribute-invalid-values`,
# `answer-attributes-need-symbolic-equality`, the two `function-*` counts. The
# **one** count branch that is kept is in `field-function-wrong-num-outputs`,
# on `$expected`: that selector is not really a plural at all but a two-way
# choice between two different components — a slope field wants one output and
# a vector field wants two, and the two branches say different things rather
# than the same thing in two numbers. Dropping it would lose the message, so it
# is written as the numeric `[1]` — an exact-value match like
# `attempts-remaining`'s `[0]`, and not a plural category some other
# language's rules would be choosing.
#
# **Digits.** Every number renders in Latin digits, so the digits written into
# prose here are Latin digits too.
#
# Attribute names, element names and every other DoenetML identifier —
# `through`, `endpoint`, `midpointOffset`, `numDimensions`, `styleNumber`,
# `selectFromSequence`, `<answer>`, `maxNumAttempts`, `sectionWideCheckWork` —
# are part of the language, not prose, and stay in English exactly as written.
# So does anything quoted back from the author's own source, and so do
# `WCAG AA`, `DoenetML`, `PreFigure`, `prefigure`, `XML`, `mathjs` and `Dast`,
# which are names. Every **symbolic** selector — `$type`, `$mode`, `$reason`,
# `$context`, `$suggestion`, `$alternative`, `$fallback`, `$expected`,
# `$labelKind`, `$isList`, `$componentType` — is kept byte for byte from
# English, keys included.


## `<lineSegment>`

line-segment-attributes-ignored-with-endpoints = { $attributes } wead ignoriert, wenn zwoa Endpunkt ogebm san

line-segment-attributes-ignored-with-endpoint-and-midpoint = { $attributes } wead ignoriert, wenn a Endpunkt und a Mittelpunkt beide ogebm san

line-segment-midpoint-offset-without-midpoint = midpointOffset hod koa Wirkung ohne an Mittelpunkt

## `<line>`

line-points-undetermined-dimensions = Grod durch Punkt mit unbestimmte Dimensiona.

line-points-too-few-dimensions = D Grod muaß durch Punkt mit mindestns zwoa Dimensiona geh.

line-points-depend-on-variables = D Grod geht durch Punkt, de wo vo Variable ohänga: { $variables }.

line-equation-invalid-format = Ungüitigs Format fia d Gleichung vo da Grod in de Variable { $variable1 } und { $variable2 }.

## `<ray>`

ray-overprescribed-through = Da Strahl is durch through, endpoint und direction festglegt.  Des ogebne through wead ignoriert.

ray-dimension-mismatch = numDimensions passt im Strahl ned zamm.

## `<vector>`

vector-overprescribed-head = Da Vektor is durch head, tail und displacement festglegt.  Des ogebne head wead ignoriert.

vector-dimension-mismatch = numDimensions passt im Vektor ned zamm.

## Attracting and constraining

attract-to-without-nearest-point = Ko ned auf a `<{ $component }>` ozogn wern, wei's koa nearestPoint-Zuastandsvariable hod.

constrain-to-without-nearest-point = Ko ned auf a `<{ $component }>` eingschränkt wern, wei's koa nearestPoint-Zuastandsvariable hod.

constrain-to-interior-without-nearest-point = Ko ned auf des Innare vo am `<{ $component }>` eingschränkt wern, wei's koa nearestPoint-Zuastandsvariable hod.

## `<choiceInput>`

choice-input-label-position-ignored = labelPosition wead bei am ned-inline choiceInput ignoriert

## Ordering children by index

choice-input-indices-count-mismatch = D Indizes fia choiceInput wern ignoriert, wei d Ozoi vo de Indizes ned zua Ozoi vo de Auswoi-Kinda passt.

pretzel-indices-count-mismatch = D Indizes fia problem wern ignoriert, wei d Ozoi vo de Indizes ned zua Ozoi vo de problem-Kinda passt.

shuffle-indices-count-mismatch = D Indizes fia shuffle wern ignoriert, wei d Ozoi vo de Indizes ned zua Ozoi vo de Komponentn passt.

indices-ignored-out-of-range = D Indizes fia { $component } wern ignoriert, wei a poar Indizes außahoib vom Beroach san.

pretzel-indices-repeated = D Indizes fia pretzel wern ignoriert, wei a poar Indizes doppelt san.

pretzel-circuit-first-index = D Indizes fia pretzel im circuit-Modus wern ignoriert, wei da erste Index 1 sei muaß.

## `<shuffle>` and `<sort>`

string-children-need-type = Damit `<{ $component }>` mit Zeichnkettn-Kinda funktioniert, muaß a `type`-Attribut ogebm sei.

invalid-type-defaulting-to-math = Ungüitiga type { $type } fia d Komponentn { $component }. Muaß oans vo math, text, number oda boolean sei. Es wead math gnumma.

string-not-valid-component-to-arrange = D Zeichnkettn "{ $value }" is koa güitige Komponentn fia { $component }. Wead ignoriert.

## Types and variables

invalid-type-defaulting-to-number = Ungüitiga type { $type }, da Typ wead auf number gsetzt.

invalid-variable-value = Ungüitiga Wert vo ana Variable: `{ $value }`

## Variants

variant-index-must-be-number = Da Variantn-Index { $index } muaß a Zoi sei

variant-index-must-be-integer = Da Variantn-Index { $index } muaß a ganze Zoi sei

## `<sideBySide>`

side-by-side-absolute-widths = `<{ $component }>` is fia absolute Maß ned umgsetzt. D Braatn wern auf relativ gsetzt.

side-by-side-absolute-margins = `<{ $component }>` is fia absolute Maß ned umgsetzt. D Ränder wern auf relativ gsetzt.

side-by-side-no-block-child = Ungüitigs `<{ $component }>`: es muaß mindestns a Block-Kind hom.

## `<label>`

label-for-ignored-on-graphical = Des `for`-Attribut an am grafischn `<label>` wead ignoriert.

label-for-must-resolve-to-one = Des `for`-Attribut an am `<label>` muaß genau oa Komponentn ergebm.

label-for-unresolved = Des `for`-Attribut an am `<label>` hod ned auf a Komponentn aufglöst wern kina.

label-for-answer-with-authored-inputs = Des `for`-Attribut an am `<label>` verweist auf a `<answer>` mit ausdrücklich gschriebne Eingom; verweis direkt auf d Eingob.

label-for-answer-without-input = Des `for`-Attribut an am `<label>` verweist auf a `<answer>` ohne Eingob zum Beschriftn.

label-for-must-reference-input-or-answer = Des `for`-Attribut an am `<label>` muaß auf a Eingob oda a answer verweisn.

## Accessibility

accessibility-short-description-or-decorative = Fia d Barrierefreiheit muaß `<{ $component }>` entweda a kurze Beschreibung hom oda ois dekorativ ogebm sei.

accessibility-video-short-description = Fia d Barrierefreiheit muaß `<video>` a kurze Beschreibung hom.

accessibility-input-short-description-or-label = Fia d Barrierefreiheit muaß `<{ $component }>` a kurze Beschreibung oda a Label hom.

accessibility-answer-input-short-description-or-label = Fia d Barrierefreiheit muaß a `<answer>`, des wo a Eingob erstellt, a kurze Beschreibung oda a Label hom.

accessibility-short-description-contains-math = Kurze Beschreibunga soitn koane Mathe-Komponentn wia `<{ $component }>` drin hom. Schreib d Mathematik mit Wörter aus.

accessibility-section-title-insufficient-contrast =
    { $mode ->
        [dark] { $colorName } hod z weng Kontrast fia an Text vom Obschnitts-Titl (dunkla Modus) ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindestns { $threshold }:1).
       *[other] { $colorName } hod z weng Kontrast fia an Text vom Obschnitts-Titl ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindestns { $threshold }:1).
    }

## `<circle>`

circle-through-points-non-numerical = A `<circle>` durch { $count } Punkt is ned umgsetzt fia an Foi, wo d Punkt koane numerischn Werte hom.

circle-too-many-through-points = A Kroas durch mehr ois 3 Punkt ko ned berechnet wern.

circle-overprescribed-radius-center-points = A Kroas mit ogebnam Radius, Mittelpunkt und Durchgangspunkt ko ned berechnet wern.

circle-center-with-multiple-points = A Kroas mit ogebnam Mittelpunkt durch mehr ois 1 Punkt ko ned berechnet wern.

circle-radius-too-small = Da Kroas ko ned berechnet wern: wei da Obstand zwischn de zwoa Punkt { $distance } is, is da ogebne Radius { $radius } z kloa.

circle-radius-with-many-points = A Kroas durch mehr ois zwoa Punkt mit am ogebna Radius ko ned erstellt wern.

circle-invalid-center-or-through-points = Ungüitiga Mittelpunkt oda ungüitige Durchgangspunkt vom Kroas.

circle-radius-center-with-multiple-points = Da Radius vo am Kroas mit ogebnam Mittelpunkt durch mehr ois 1 Punkt ko ned berechnet wern.

circle-change-radius-non-numerical = Da Radius vo am Kroas mit ned-numerischn Durchgangspunkt ko ned gändat wern

circle-radius-with-points-non-numerical = A Kroas durch mehr ois oan Punkt mit am ogebna Radius ko ned erstellt wern, wenn koane numerischn Werte do san.

circle-change-center-non-numerical = Des Ändern vom Mittelpunkt vo am Kroas durch Punkt ohne numerische Werte is ned umgsetzt.

## `<function>`

# CLDR has no plural rules for `bar`, so the two counts read with one form.
function-domain-insufficient-dimensions = Z weng Dimensiona fia an Definitionsberoach vo da Funktion. Da Beroach hod { $intervals } Intervoi, owa d Funktion hod { $inputs } Eingom.

function-domain-invalid-format = Ungüitigs Format fia an Definitionsberoach vo da Funktion.

function-ignoring-non-numerical =
    { $type ->
        [maximum] Des ned-numerische Maximum vo da Funktion wead ignoriert.
        [minimum] Des ned-numerische Minimum vo da Funktion wead ignoriert.
        [extremum] Des ned-numerische Extremum vo da Funktion wead ignoriert.
        [point] Da ned-numerische Punkt vo da Funktion wead ignoriert.
        [slope] D ned-numerische Steigung vo da Funktion wead ignoriert.
       *[other] Des ned-numerische { $type } vo da Funktion wead ignoriert.
    }

function-ignoring-empty =
    { $type ->
        [maximum] Des leere Maximum vo da Funktion wead ignoriert.
        [minimum] Des leere Minimum vo da Funktion wead ignoriert.
        [extremum] Des leere Extremum vo da Funktion wead ignoriert.
        [point] Da leere Punkt vo da Funktion wead ignoriert.
       *[other] Des leere { $type } vo da Funktion wead ignoriert.
    }

function-points-too-close = D Funktion hod zwoa Punkt, de wo z nah beinanda liegn. D Funktion ko ned definiert wern.

# One form for both counts: CLDR has no plural rules for `bar`.
function-iterates-input-output-mismatch = Iterierte vo ana Funktion san nur meglich, wenn d Ozoi vo de Eingom gleich is wia d Ozoi vo de Ausgom. De Funktion hod { $inputs } Eingom und { $outputs } Ausgom.

## `<sequence>`

sequence-invalid-length = Ungüitige Läng vo da Folg.  Muaß a ned-negative ganze Zoi sei.

sequence-invalid-step = Ungüitiga Schritt vo da Folg.  Muaß a Zoi sei fia a Folg vom Typ { $type }.

sequence-invalid-endpoint-number = Ungüitigs "{ $attribute }" vo ana Zoinfolg.  Muaß a Zoi sei.

sequence-invalid-endpoint-letters = Ungüitigs "{ $attribute }" vo ana Buachstombfolg.  Muaß a Buachstom-Kombination sei.

sequence-invalid-endpoint = Ungüitigs "{ $attribute }" vo da Folg.

select-from-sequence-coprime-not-numbers = coprime wead ignoriert, wei koane Zoin auswäit wern

select-from-sequence-coprime-with-exclude-combinations = coprime wead ignoriert, wei excludeCombinations ogebm is

## Resolving a `target`

target-not-found = Ungüitigs target fia `<{ $source }>`: des Zui ko ned gfundn wern.

target-state-variable-not-found = Ungüitigs target fia `<{ $source }>`: es gibt koa Zuastandsvariable mit am Nama "{ $property }" an am `<{ $component }>`.

## `<odeSystem>`

ode-system-variables-match-independent = D Variable vo am `<odeSystem>` miassn andare sei ois d unobhängige Variable.

ode-system-duplicate-variable-names = ODE-RHS-Funktiona mit doppelte obhängige Variablnnama kina ned definiert wern.

ode-system-rhs-function-error = D ODE-RHS-Funktion ko ned definiert wern.  Fehla beim Erstelln vo da mathjs-Funktion.

## `<angle>`, `<parabola>`, and `<intersection>`

angle-too-many-lines = A Winkl zwischn { $count } Grodn ko ned definiert wern

angle-invalid-through-point = Ungüitiga Punkt im through vo am `<angle>`

parabola-vertex-too-many-points = A Parabl mit Scheitlpunkt durch mehr ois 1 Punkt is ned umgsetzt.

parabola-too-many-points = A Parabl durch mehr ois 3 Punkt is ned umgsetzt.

intersection-too-many-items = Da Schnitt vo mehr ois zwoa Elementn is ned umgsetzt

## Other math components

ionic-compound-not-two-ions = Ionenverbindunga mit ebbas anderm ois zwoa Iona san ned umgsetzt.

ionic-compound-needs-cation-and-anion = D Ionenverbindung is nur fia a Kation und a Anion umgsetzt.

solve-equations-cannot-evaluate = D Gleichung ko ned glöst wern, wei's se ned auswertn hod lassn: { $equation }

math-operators-operand-number-required = Es muaß a operandNumber ogebm wern, wenn a Mathe-Operand rauszogn wead.

eigen-decomposition-failed = D Eigenwerte vo da Matrix hom ned berechnet wern kina

## `<matchesPattern>`

# One form for the count: CLDR has no plural rules for `bar`.
matches-pattern-parameter-not-in-pattern = `<matchesPattern>`: { $parameters } kummt im Muasta ned vor, drum passt's imma auf a Lucka.

## `<graph>`

graph-grid-invalid = `<graph>`: grid="{ $grid }" ko ned interpretiert wern. Es muaß none, medium, dense oda zwoa positive Zoin mit am Leerzeichn dazwischn sei, zum Beispui grid="1 0.5". Es wead koa Gitta zeichnet.

## `<slopeField>` and `<vectorField>`

# The `$expected` branch is kept even though CLDR has no plural rules for
# `bar`: it is not a plural but a two-way choice between two components — a
# slope field wants one output, a vector field two — and the two branches say
# different things. The `$found` count, which is a real plural, reads with one
# form.
field-function-wrong-num-outputs =
    `<{ $component }>` braucht a Funktion mit { $expected ->
        [1] oana Ausgob, da Steigung y' an jedm Punkt, zum Beispui `y - x`
       *[other] zwoa Ausgom, am Vektor an jedm Punkt, zum Beispui `(y, -x)`
    }, owa de gebne Funktion hod { $found } Ausgom. { $alternative ->
        [none] Es wead nix zeichnet.
       *[other] `<{ $alternative }>` is d Komponentn fia de Funktion. Es wead nix zeichnet.
    }

field-function-attribute-ignored-with-child = Des `function`-Attribut wead ignoriert, wei d Funktion a drin in da Komponentn gebm is; de innare wead gnumma. Gib d Funktion nur auf oana vo de zwoa Artn o.

field-variables-ignored =
    `<{ $component }>`: des `variables`-Attribut nennt d Variable vo am Ausdruck, der wo direkt drin in da Komponentn gschriebm is. { $reason ->
        [function-child] D Funktion is do ois `<function>`-Kind gebm, des wo seine eigane Variable nennt, drum wead `variables` ignoriert.
       *[no-expression] Es gibt do koan soichan Ausdruck, drum wead `variables` ignoriert.
    }

## PreFigure renderer

prefigure-x-label-position-unsupported = `<graph>`: xLabelPosition="left" wead im prefigure-Renderer ned unterstützt; es wead des Verhoitn vo da rechtn Position gnumma.

prefigure-y-label-position-unsupported = `<graph>`: yLabelPosition="bottom" wead im prefigure-Renderer ned unterstützt; es wead des Verhoitn vo da obarn Position gnumma.

prefigure-invalid-axis-bounds = `<graph>`: ungüitige Achsngrenzn fia d prefigure-Umwandlung; es wead d Standard-bbox (-10,-10,10,10) gnumma.

prefigure-invalid-width = `<graph>`: ungüitige Braatn fia d prefigure-Umwandlung; es wead d Standard-Diagrammbraatn 425 gnumma.

prefigure-invalid-aspect-ratio = `<graph>`: ungüitigs aspectRatio fia d prefigure-Umwandlung; es wead des Standard-Seitnverhältnis 1 gnumma.

prefigure-grid-spacing-too-fine = `<graph>`: d Gittaweitn is z fei fia d Achsngrenzn; des Gitta wead im prefigure-Renderer weglassn.

prefigure-annotations-not-rendered = `<graph>`: Åmerkunga wern ned dorgstellt, wenn ned da PreFigure-Renderer gnumma wead.

multiple-annotations-children = Es san mehrare `<annotations>`-Kinda im `<graph>` gfundn worn; olle außa's letzte wern ignoriert.

## Referring to other components

copy-unrecognized-component-type = A unbekannta Komponentn-Typ ko ned erweitat oda kopiert wern: { $type }.

copy-prop-not-found = Da prop { $property } is an ana Komponentn vom Typ { $component } ned gfundn worn

collect-no-source = Fia collect is koa Quelln gfundn worn.

collect-invalid-component-type = Komponentn vom Typ `<{ $component }>` kina ned gsammlt wern, wei des koa güitiga Komponentn-Typ is.

reference-index-unavailable = Da Index `{ $reference }` ko ned referenziert wern

## `<callAction>`

component-action-unavailable = { $action } ko auf da Komponentn `{ $reference }` ned aufgruafa wern

## `<dataFrame>`

data-frame-inconsistent-row-lengths = D Datn hom a ungüitige Form.  D Zeiln hom ungleiche Länga. Gfundn im componentIdx :{ $componentIdx }

data-frame-duplicate-column-names = D Datn hom doppelte Spoitnnama.  Gfundn im componentIdx :{ $componentIdx }

data-frame-missing-column-name = De Datn fäit a Spoitnnama.  Gfundn im componentIdx :{ $componentIdx }

## `<answer>` and scoring

answer-award-depends-on-own-response = A award vo dera Antwuat baut auf da eigana gschicktn Antwuat vom answer-Tag auf, wos zu unerwartetm Verhoitn füaht.

answer-max-num-attempts-in-section-wide-check-work = `maxNumAttempts` an am `<answer>` drin in am Behälta mit `sectionWideCheckWork` zum Setzn hod koa Wirkung, wei d Ozoi vo de Versuach vom Behälta gsteiat wead. Setz `maxNumAttempts` stattdessn am Behälta.

nested-section-wide-check-work-max-num-attempts = `maxNumAttempts` an am Behälta mit `sectionWideCheckWork`, der wo drin in am andan Behälta mit `sectionWideCheckWork` is, zum Setzn hod koa Wirkung, wei d Ozoi vo de Versuach vom äußarn Behälta gsteiat wead. Setz `maxNumAttempts` stattdessn am äußarn Behälta.

# One form for the count: CLDR has no plural rules for `bar`.
answer-attributes-need-symbolic-equality = { $attributes } hod koa Wirkung, wenn symbolicEquality ned gsetzt is.

answer-invalid-type = Ungüitiga Typ fia d Antwuat: { $type }

## `<module>`, `<conditionalContent>`, `<slider>`, `<pretzel>`

module-attribute-child-needs-name = Wei d Komponentn `<{ $component }>` koan Nama hod, ko's ned fia a Modul-Attribut gnumma wern

module-attribute-name-already-defined = D Komponentn `<{ $component } name="{ $name }">` ko ned ois Attribut fia a Modul gnumma wern, wei da Komponentn-Typ `<module>` scho a Attribut "{ $name }" definiert hod.

conditional-content-condition-ignored = Des Attribut `condition` wead an am `<conditionalContent>` mit case- oda else-Kinda ignoriert.

slider-markers-type-mismatch = Da Typ vo de Marker passt ned zum Typ vom Schiaba.

pretzel-problem-needs-statement-and-answer = Ungüitigs pretzel: jeds `<problem>` muaß oa `<statement>` und oa `<answer>` hom.

pretzel-circuit-first-problem-distractor = Ungüitigs pretzel: im mode="circuit" ko des erste `<problem>` koa Distraktor sei.

## Attribute values

# One form for the count: CLDR has no plural rules for `bar`.
attribute-invalid-values = Ungüitiga Wert { $values } fia des Attribut `{ $attribute }`; wead ignoriert.

attribute-must-be-references = Ungüitiga Wert `{ $value }` fia des Attribut `{ $attribute }`. Des Attribut muaß aus Referenzn bestehn, de wo mit am `$` ofanga.

math-input-invalid-function-names = <mathInput>: ungüitige Funktionsnama in { $attribute } san ignoriert worn: { $names }. Jeda Nama muaß im ozeigtn Teu mindestns 2 Zeichn hom (Buachstom oda Bindestrich); es ko a optionala `|<mathspeak alternative>`-Ohang folgn.

## Building components from the source

component-type-invalid = Ungüitiga Komponentn-Typ: `<{ $componentType }>`

attribute-repeated = Des Attribut { $attribute } ko ned wiederhoit wern.

attribute-invalid-for-component = Ungüitigs Attribut "{ $attribute }" fia a Komponentn vom Typ `<{ $componentType }>`.

## Style definition contrast

style-definition-insufficient-contrast =
    D Stuidefinition { $styleNumber } hod z weng Kontrast fia { $context ->
        [text-on-background] d Textfarb gegnüba da Hintagrundfarb
        [high-contrast] d Farb mit hohm Kontrast gegnüba da Zeichnfläch
        [line] d Linienfarb gegnüba da Zeichnfläch
        [marker] d Markerfarb gegnüba da Zeichnfläch
       *[text-on-canvas] d Textfarb gegnüba da Zeichnfläch
    }{ $mode ->
        [dark] { " (dunkla Modus)" }
       *[light] { "" }
    } ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindestns { $threshold }:1).

style-definition-dark-mode-text-background-contrast =
    A wenn d Stuidefinition { $styleNumber } Farbm ogebm hod, de wo im hellen Modus gnua Kontrast hom, hom de drausn obgleitetn Farbm fia an dunklen Modus z weng Kontrast vo da Textfarb gegnüba da Hintagrundfarb ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindestns { $threshold }:1). { $suggestion ->
        [available] Fia gnua Kontrast im dunklen Modus entweda an Kontrast im hellen Modus erhöhn (z. B. { $lightAttribute }="{ $lightColor }" setzn) oda d Farb fia an dunklen Modus überschreibm (z. B. { $darkAttribute }="{ $darkColor }" setzn).
       *[none] Fia gnua Kontrast im dunklen Modus an Kontrast im hellen Modus erhöhn oda d obgleitetn Farbm mit textColorDarkMode und/oda backgroundColorDarkMode überschreibm.
    }

style-definition-dark-mode-text-canvas-contrast =
    A wenn d Stuidefinition { $styleNumber } a Textfarb ogebm hod, de wo im hellen Modus gnua Kontrast hod, hod de drausn obgleitete Textfarb fia an dunklen Modus z weng Kontrast gegnüba da Zeichnfläch ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindestns { $threshold }:1). { $suggestion ->
        [available] Fia gnua Kontrast im dunklen Modus entweda an Kontrast im hellen Modus erhöhn (z. B. textColor="{ $lightColor }" setzn) oda d Farb fia an dunklen Modus überschreibm (z. B. textColorDarkMode="{ $darkColor }" setzn).
       *[none] Fia gnua Kontrast im dunklen Modus an Kontrast im hellen Modus erhöhn oda d obgleitete Farb mit textColorDarkMode überschreibm.
    }

section-multiple-style-palettes = A Obschnitt ko nur oa <stylePalette> auswäin; es wead de letzte gnumma.

## Unique variants

variant-num-to-select-not-non-negative-integer = de eindeutign Variantn vo { $component } kina ned bestimmt wern, wei numToSelect koa ned-negative ganze Zoi is.

variant-num-to-select-not-constant-number = de eindeutign Variantn vo { $component } kina ned bestimmt wern, wei numToSelect koa konstante Zoi is.

variant-with-replacement-not-constant-boolean = de eindeutign Variantn vo { $component } kina ned bestimmt wern, wei withReplacement koa konstanta Boolean is.

variant-select-weight-disables-unique = Eindeutige Variantn fia select san obgschoit, wenn a Option mit selectWeight oda selectForVariants ogebm is

variant-coprime-undetermined = de eindeutign Variantn vo { $component } kina ned bestimmt wern, wei se ned bestimma lasst, ob coprime imma foisch is.

variant-attribute-not-constant = de eindeutign Variantn vo { $component } kina ned bestimmt wern, wei { $attribute } koa Konstante is.

variant-attribute-not-number = de eindeutign Variantn vo { $component } kina ned bestimmt wern, wei { $attribute } koa Zoi is.

variant-attribute-wrong-type-for-sequence =
    de eindeutign Variantn vo { $component } vom Typ { $type } kina ned bestimmt wern, wei { $attribute } ned { $expected ->
        [letters-combination] a Kombination vo Buachstom
        [math-expression] a güitiga mathematischa Ausdruck
        [integer] a ganze Zoi
       *[number] a Zoi
    } is.

variant-length-not-integer = de eindeutign Variantn vo { $component } kina ned bestimmt wern, wei length koa ganze Zoi is.

variant-sort-not-implemented = eindeutige Variantn vo am { $component } mit sort san ned umgsetzt

variant-exclude-combinations-not-implemented = eindeutige Variantn vo am { $component } mit excludeCombinations san ned umgsetzt

variant-math-exclude-not-implemented = eindeutige Variantn vo am { $component } vom Typ math mit exclude san ned umgsetzt

variant-non-constant-exclude-not-implemented = eindeutige Variantn vo am { $component } mit ned-konstantm exclude san ned umgsetzt

## PreFigure conversion

prefigure-descendant-unsupported = { $subject }: wead im prefigure-Renderer vom graph ned unterstützt; da Nochfoahr wead übersprunga.

prefigure-descendant-invalid-geometry = { $subject }: ned-endliche oda unvollständige Geometrie; da Nochfoahr wead übersprunga.

prefigure-curve-label-omitted = { $subject }: Beschriftunga wern an umgwandltn Kurvn-Elementn ned unterstützt; des Label wead weglassn.

prefigure-curve-unsupported-definition-type = { $subject }: da Definitionstyp '{ $definitionType }' vo da Kurvnfunktion wead ned unterstützt; da Nochfoahr wead übersprunga.

prefigure-region-flip-functions-unsupported = { $subject }: des flipFunctions-Attribut an regionBetweenCurves wead ned unterstützt; da Nochfoahr wead übersprunga.

prefigure-region-non-formula-child = { $subject }: an regionBetweenCurves wern nur Kindfunktiona vom Typ Formln unterstützt; da Nochfoahr wead übersprunga.

prefigure-label-position-unsupported =
    { $subject }: labelPosition '{ $labelPosition }' wead fia a { $labelKind ->
        [line-family] Label aus da Grodn-Familie
       *[point] Punkt-Label
    } ned unterstützt; es wead d Standard-Ausrichtung vo PreFigure gnumma.

prefigure-fill-style-unsupported = { $subject }: da Füllstui '{ $fillStyle }' wead vo PreFigure ned unterstützt; es wead auf a volle Füllung zruckgriffa.

prefigure-line-style-unknown = { $subject }: da unbekannte Linienstui '{ $lineStyle }' wead in da PreFigure-Ausgob weglassn.

prefigure-marker-style-mapped-to-diamond = { $subject }: da Markerstui '{ $markerStyle }' is auf an PreFigure-Stui 'diamond' obbuidet worn.

prefigure-marker-style-unsupported = { $subject }: da Markerstui '{ $markerStyle }' wead vo PreFigure ned unterstützt; es wead da Standardstui gnumma.

## PreFigure annotations

annotation-ref-unresolvable = `<annotation>`: ungüitiga `ref`; des Zui ko ned aufglöst wern. D Åmerkung wead weglassn.

annotation-ref-multiple-targets = `<annotation>`: `ref` hod mehrare Zui ergebm; es wead's erste gnumma.

annotation-ref-outside-graph = `<annotation>`: ungüitiga `ref`; des Zui is außahoib vom umgebndn graph. D Åmerkung wead weglassn.

annotation-ref-unsupported-target = `<annotation>`: ungüitiga `ref`; des Zui is in da prefigure-Umwandlung koa unterstütztes grafisches Objekt. D Åmerkung wead weglassn.

annotation-text-missing = `<annotation>`: `text` fäit oda is leer; es wead leera Text ausgebm.

## Composites and references

composite-circular-dependency =
    { $componentType ->
        [none] Es is a zirkuläre Obhängigkeit gfundn worn.
       *[other] Es is a zirkuläre Obhängigkeit mit ana `<{ $componentType }>`-Komponentn gfundn worn.
    }

reference-no-referent = Koa Bezug fia d Referenz gfundn: `{ $reference }`

reference-multiple-referents = Mehrare Bezüg fia d Referenz gfundn: `{ $reference }`

## Children that do not match

children-invalid-attribute-format = Ungüitigs Format fia des Attribut { $attribute } vo am `<{ $componentType }>`.

children-invalid = Ungüitige Kinda fia `<{ $componentType }>`: ungüitige Kinda gfundn: { $children }

## Falling back to a default

attribute-value-invalid-using-default = Ungüitiga Wert `{ $value }` fia des Attribut `{ $attribute }`, es wead da Wert `{ $default }` gnumma

## Loading a DoenetML version

doenetml-version-not-found =
    { $fallback ->
        [none] D DoenetML-Version { $version } is ned gfundn worn.
       *[other] D DoenetML-Version { $version } is ned gfundn worn. Es wead auf d Version { $fallback } zruckgriffa
    }

## Reading the DoenetML

parse-invalid-doenetml = Ungüitigs DoenetML: { $content }

parse-tag-missing-close-tag = Ungüitigs DoenetML: Da Tag `{ $tag }` hod koan Schlusstag. Erwartet is a söbstschließenda Tag oda a `</{ $tagName }>`-Tag.

parse-tag-error = Ungüitigs DoenetML: Fehla im Tag `<{ $tagName }>`

parse-attribute-missing-value = Ungüitigs DoenetML: Am ungüitign Attribut `{ $attribute }` fäit scheints a Wert.

parse-attribute-invalid = Ungüitigs DoenetML: Ungüitigs Attribut `{ $attribute }`

parse-attribute-value-invalid = Ungüitigs DoenetML: Ungüitiga Attributwert `{ $value }`

parse-attribute-value-quote-mismatch = Ungüitigs DoenetML: Ungüitiga Attributwert `{ $value }`. D Ozeichnungszeichn passn ned zamm. Es fäit scheints a `{ $quote }`

parse-open-tag-name-missing = Ungüitigs DoenetML: Es is a Tag ohne Tag-Nama gfundn worn, zum Beispui `<`

parse-tag-not-closed = Ungüitigs DoenetML: Da Tag `{ $tag }` is ned gschlossn worn (a `>` fäit scheints).

parse-self-closing-tag-name-missing = Ungüitigs DoenetML: Es is a Tag ohne Tag-Nama gfundn worn `<{ $content }>`

parse-self-closing-tag-not-closed = Ungüitigs DoenetML: Da Tag `{ $tag }` is ned gschlossn worn (`/>` fäit scheints).

parse-tag-invalid-attributes = Ungüitigs DoenetML: Da Tag `{ $tag }` is ned güitig. Villeicht hom d Attribut Fehla.

parse-close-tag-name-missing = Ungüitigs DoenetML: Es is a Schlusstag ohne Tag-Nama gfundn worn, zum Beispui `</`

parse-attribute-value-unquoted = Attributwerte miassn in Ozeichnungszeichn stehn: `{ $attribute }="{ $value }"`

parse-close-tag-without-open-tag = Ungüitigs DoenetML: Da Schlusstag `{ $tag }` is gfundn worn, owa es gibt koan zuaghörign Öffnungstag

parse-close-tag-mismatched = Ungüitigs DoenetML: Da Schlusstag passt ned. Erwartet is `</{ $expected }>`. Gfundn is `{ $found }`

parser-node-unconvertible = Da Knotn { $node } hod ned in an Dast-Knotn umgwandlt wern kina.

## Names

name-attribute-invalid =
    Ungüitiga Attributnama name='{ $name }'. { $reason ->
        [characters] Nama dürfa nur Buachstom, Zoin, Unterstrich oda Bindestrich enthoitn.
       *[start] Nama miassn mit am Buachstom ofanga.
    }

component-name-invalid-start = Ungüitiga Komponentn-Nama "{ $name }". Nama miassn mit am Buachstom ofanga.

## `<answer>` sugar

answer-video-watched-missing-video = A Antwuat vom Typ videoWatched muaß a video-Attribut hom

answer-video-watched-video-not-reference = A Antwuat vom Typ videoWatched muaß a video-Attribut hom, des wo a Referenz is

answer-name-not-single-text = Des name-Attribut vo ana Antwuat muaß genau oa Text-Kind hom

## Referencing another document

external-doenetml-recursion-limit = Des externe DoenetML hod wegn z vui Rekursionsstufn ned ghoit wern kina. Gibt's do a zirkuläre Referenz?

external-doenetml-unavailable = Des DoenetML vo { $attribute }="{ $uri }" hod ned ghoit wern kina

external-doenetml-type-mismatch = Ungüitigs DoenetML vo { $attribute }="{ $uri }" ghoit: es passt ned zum Komponentn-Typ "{ $componentType }"

## Deprecated syntax

deprecated-attribute-renamed =
    { $component ->
        [none] [deprecation] Des Attribut `{ $from }` is veroit; nimm stattdessn `{ $to }`.
       *[other] [deprecation] Des Attribut `{ $from }` an `<{ $component }>` is veroit; nimm stattdessn `{ $to }`.
    }

deprecated-attribute-renamed-conflict =
    { $component ->
        [none] [deprecation] Des Attribut `{ $from }` is veroit und wead ignoriert, wei a `{ $to }` ogebm is.
       *[other] [deprecation] Des Attribut `{ $from }` an `<{ $component }>` is veroit und wead ignoriert, wei a `{ $to }` ogebm is.
    }

deprecated-attribute-ignored = [deprecation] Des Attribut `{ $attribute }` an `<{ $component }>` is veroit und wead ignoriert.

deprecated-attribute-to-child = [deprecation] Des Attribut `{ $attribute }` an `<{ $component }>` is veroit; nimm stattdessn a `<{ $child }>`-Kind.

deprecated-attribute-value-renamed = [deprecation] Da Wert `{ $value }` vom Attribut `{ $attribute }` an `<{ $component }>` is veroit; nimm stattdessn `{ $to }`.


## Language coverage

pluralize-english-only = `<pluralize>` ko nur Englisch in d Mehrzoi setzn, drum bleibt da Text in am Dokument auf { $locale } so, wia'n da Autor gschriebm hod. Schreib d Mehrzoiform direkt hi oda setz's mit am `pluralForm`-Attribut.


## Checking against the schema

schema-element-unrecognized = Des Element `<{ $tag }>` is koa bekanntes Doenet-Element.

schema-element-not-allowed-at-root = Des Element `<{ $tag }>` is an da Wurzn vom Dokument ned erlaubt.

schema-element-not-allowed-inside = Des Element `<{ $tag }>` is drin in `<{ $parent }>` ned erlaubt.

schema-attribute-unrecognized = Des Element `<{ $tag }>` hod koa Attribut mit am Nama `{ $attribute }`.

schema-attribute-value-not-allowed =
    { $isList ->
        [true] Des Attribut `{ $attribute }` vom Element `<{ $tag }>` muaß a Listn sei, wo jeds Element oans vo dene is: { $allowed }
       *[other] Des Attribut `{ $attribute }` vom Element `<{ $tag }>` muaß oans vo dene sei: { $allowed }
    }


## The `<select>` family's error boxes

select-variant-name-option-count-mismatch = Ungüitiga Variantnnama fia select.  Da Variantnnama { $variantName } kummt in { $numOptions } Optiona vor, owa d Ozoi zum Auswäin is { $numToSelect }.

select-variant-name-without-options = Fia select san Variantn ogebm, owa fia an meglichn Variantnnama { $variantName } gibt's koane Optiona.

select-variant-name-not-possible = Da Variantnnama { $variantName }, der wo fia select ogebm is, is koa meglicha Variantnnama.

select-too-few-options = { $numToSelect } Komponentn kina ned aus bloß { $numOptions } auswäit wern.

select-from-sequence-too-few-values = { $numToSelect } Werte kina ned aus ana Folg vo da Läng { $length } auswäit wern.

select-from-sequence-indices-count-mismatch = D Ozoi vo de fia select ogebna Indizes muaß zua Ozoi zum Auswäin passn

select-from-sequence-indices-not-integers = Olle fia select ogebna Indizes miassn ganze Zoin sei

select-from-sequence-index-excluded = Es is a Index vo selectfromsequence ogebm, der wo ausgschlossn is

select-from-sequence-indices-excluded-combination = Es san Indizes vo selectfromsequence ogebm, de wo a ausgschlossne Kombination san

select-from-sequence-coprime-not-positive-integers = Teilafremde Kombinationa kina ned auswäit wern, wei koane positivn ganzn Zoin auswäit wern.

select-from-sequence-coprime-common-factor = Teilafremde Zoin kina ned auswäit wern. Olle meglichn Werte hom an gmeinsamen Teila. (D ogebna Werte vo "from" oda "to" miassn teilafremd zu "step" sei.)

select-from-sequence-coprime-single-number = Teilafremde Kombinationa kina ned aus ana einzign Zoi auswäit wern, de wo ned 1 is.

select-from-sequence-excluded-too-many-combinations = Über 70 % vo de Kombinationa in selectFromSequence san ausgschlossn

select-from-sequence-coprime-none-found = Teilafremde Zoin hom ned auswäit wern kina. Olle meglichn Werte hom an gmeinsamen Teila.

select-from-sequence-too-few-unique-values = { $numToSelect } eindeutige Werte kina ned aus ana Folg vo da Läng { $numPossibleValues } auswäit wern

select-prime-numbers-too-few-values = { $numToSelect } Werte kina ned aus ana Listn vo Primzoin vo da Läng { $numValues } auswäit wern

select-prime-numbers-values-count-mismatch = D Ozoi vo de fia select ogebna Werte muaß zua Ozoi zum Auswäin passn

select-prime-numbers-values-not-prime = Olle Werte, de wo fia select prime number ogebm san, miassn in da Listn vo de Primzoin sei

select-prime-numbers-values-excluded-combination = De ogebna Werte vo selectPrimeNumbers san a ausgschlossne Kombination

select-prime-numbers-excluded-too-many-combinations = Über 70 % vo de Kombinationa in selectPrimeNumbers san ausgschlossn

select-random-combination-fluke = Durch an außaordentlich unwahrscheinlichn Zufoi hod koa Kombination vo zufälligne Werte auswäit wern kina

select-random-value-fluke = Durch an außaordentlich unwahrscheinlichn Zufoi hod koa zufälliga Wert auswäit wern kina

## Inputs embedded in math

math-embedded-input-shape-unsuitable =
    { $reason ->
        [not-inline] Des `<{ $component }>` wead ned ozeigt, wei's drin in da Mathematik is und ned `inline` is. Gib `inline` dazua, dass draus a Auswoiliste wead, de wo drin in am Ausdruck Platz hod.
        [expanded] Des `<{ $component }>` wead ned ozeigt, wei's drin in da Mathematik is und `expanded` is. Nimm `expanded` weg; a mehrzeiligs Feid hod drin in am Ausdruck koan Platz.
        [on-graph] Des `<{ $component }>` wead ned ozeigt, wei's drin in ana Mathematik is, de wo auf am Graph zeichnet wead und koan Platz fia a Eingob hod.
       *[relative-width] Des `<{ $component }>` wead ned ozeigt, wei's drin in da Mathematik is und a relative Braatn hod. Gib d Braatn in absolute Einheitn o, zum Beispui `px`.
    }
