# Bavarian (Boarisch) editor and language-server surfaces: the footer, the
# diagnostics panel, the variant picker, the accessibility button and the
# context-help panel. Selected by `uiLocale`.
#
# Translated from `locales/en/editor.ftl`, which is the source of truth.
# Message ids are never translated — only the text to the right of `=`.
#
# UNREVIEWED SEED. Machine-generated, pending review by a speaker (#1521).
# Correct anything here freely; nothing in it was written by a translator.
#
# **Script and orthography.** Latin script, German-based spelling, following
# the **Bavarian Wikipedia (bar.wikipedia)** in its **Central Bavarian /
# Austro-Bavarian** register. **Bavarian has no codified standard** — no
# orthography board, no official dictionary, no agreed norm. **ß is used**,
# unlike `locales/gsw`. See `chrome.ftl` for the full note.
#
# **Do not edit this file toward Standard German**: «ned», «is», «san», «hod»,
# «ko», «koa», «nix», «oda», «Fehla», «Zeiln», «Seitn», «zoagn» are the
# catalog, not typos.
#
# **There is no simple past** in Bavarian — the perfect does all of that work
# — which is why the past-tense sentences here read as perfects: «es san koane
# Verstöß gfundn worn», never a preterite.
#
# **What is borrowed.** The buttons, the connectives and the everyday nouns
# are Bavarian; the editor's technical nouns («Attribut», «Referenz»,
# «Komponentn», «Dokumentation») are Standard German, the register a Bavarian
# speaker is schooled in.
#
# **Counts.** CLDR has **no plural data for `bar`**, so no plural category can
# be selected: this file writes **no** `[zero]`, `[one]`, `[two]`, `[few]` or
# `[many]` branch anywhere. `editor-accessibility-label` and `help-coordinates`
# therefore carry one form each rather than English's singular/plural split.
#
# **Digits.** Every number renders in Latin digits.
#
# **`WCAG`, `WCAG AA`, `DoenetML` and `XML` are names**, not words, and stay in
# English exactly as `locales/en` writes them. So do the DoenetML identifiers
# `styleNumber` and the attribute names in `help-reset-overrides`. Every
# symbolic selector — `$action`, `$status`, `$shortcut`, `$reason`,
# `$location`, `$allowed`, `$line`, `$perItem` — is kept byte for byte from
# English.


## The viewer's controls

editor-update-viewer =
    { $action ->
        [reset] Zrucksetzn
       *[update] Aktualisian
    }

# Bavarian puts the verb last, so the word arrives after the noun it acts on,
# the same shape `locales/de` and `locales/gsw` use.
editor-update-viewer-title =
    { $shortcut ->
        [none] D Ozeig { $word }
       *[other] D Ozeig { $word } { $shortcut }
    }


## The variant picker

editor-variant = Variantn
editor-variant-filter = Fuitern …
editor-variant-next = Nächste Variantn auswäin
editor-variant-previous = Vorherige Variantn auswäin


## The accessibility status button

editor-accessibility-title =
    { $status ->
        [violations] Es is a Verstoß gegn WCAG AA gfundn worn. Klickn, um an Bericht zua Barrierefreiheit { $action ->
            [close] zuazumacha
           *[open] aufzumacha
        }.
        [advisories] Klickn, um an Bericht zua Barrierefreiheit { $action ->
            [close] zuazumacha
           *[open] aufzumacha
        }. Es san koane WCAG-AA-Verstöß gfundn worn, owa es gibt weidare Empfehlunga zua Barrierefreiheit.
       *[clean] Klickn, um an Bericht zua Barrierefreiheit { $action ->
            [close] zuazumacha
           *[open] aufzumacha
        }. Es san koane Problem mit da Barrierefreiheit gfundn worn.
    }

# One form for the count: CLDR has no plural rules for `bar`.
editor-accessibility-label =
    { $status ->
        [violations] Es is a Verstoß gegn WCAG AA gfundn worn. Es san { $count } WCAG-AA-Verstöß gfundn worn. Klickn, um an Bericht zua Barrierefreiheit { $action ->
            [close] zuazumacha
           *[open] aufzumacha
        }.
        [advisories] Es san koane WCAG-AA-Verstöß gfundn worn. Es san { $count } weidare Empfehlunga zua Barrierefreiheit gfundn worn. Klickn, um an Bericht zua Barrierefreiheit { $action ->
            [close] zuazumacha
           *[open] aufzumacha
        }.
       *[clean] Es san koane WCAG-AA-Verstöß gfundn worn. Klickn, um an Bericht zua Barrierefreiheit { $action ->
            [close] zuazumacha
           *[open] aufzumacha
        }.
    }

editor-accessibility-badge = WCAG


## The footer

editor-version-title = DoenetML-Version { $version }

editor-tab-help = Hüif zum Kontext
editor-tab-help-short = Kontext
editor-tab-errors = Fehla
editor-tab-warnings = Woarnunga
editor-tab-info = Info
editor-tab-accessibility = Barrierefreiheit
editor-tab-responses = Gschickte Antwuatn

editor-tab-with-count = { $label }: { $count }

editor-options = Editor-Optiona
editor-format-as-doenetml = Ois DoenetML formatian
editor-format-as-xml = Ois XML formatian


## The diagnostics panel

editor-diagnostic-line = Zeiln #{ $line }

editor-no-errors = Koane Fehla
editor-no-warnings = Koane Woarnunga
editor-no-info = Koane Info-Diagnosn

editor-show-info-annotations = Info-Diagnosn im Editor zoagn
editor-show-accessibility-annotations = Diagnosn zua Barrierefreiheit im Editor zoagn

editor-accessibility-learn-more = Wia Doenet d Barrierefreiheit ogeht

editor-accessibility-violations-heading = Verstöß gegn d Barrierefreiheit ({ $standard })

editor-accessibility-other-heading = Andare Problem mit da Barrierefreiheit
editor-none-found = Nix gfundn


## Submitted responses

editor-no-responses = No koane Antwuatn gschickt
editor-response-answer-id = Antwuat-Id
editor-response-response = Antwuat
editor-response-credit = Guadschrift
editor-response-submitted = Gschickt


## The context-help panel

help-placeholder = An Cursor auf an Tag-Nama, a Attribut oda { $ref } setzn fia d Dokumentation.

help-unsupported-ref-chain = Hüif zua mehrteilign Referenzn wia { $example } gibt's no ned.

help-unresolved-ref =
    { $reason ->
        [notFound] Koa Bezug fia d Referenz gfundn: { $ref }.
        [multiple] Mehrare Bezüg fia d Referenz gfundn: { $ref }.
       *[indeterminate] A Bezug fia { $ref } hod se ned bestimma lassn.
    }

help-learn-about-references = Mehr über Referenzn erfoahrn →
help-reference-page = Referenzseitn →

help-suggestions-header =
    { $location ->
        [inside] Drin in { $element }
       *[top] Auf da obastn Ebene
    }{ $allowed ->
        [none] { " — do ghört nix hi." }
        [text] { " — do Text eingebm." }
        [text-and-components] { " — do Text eingebm, oda des probian:" }
       *[components] { " — zum Probian:" }
    }

help-suggestions-footer = { $shortcut } drucka, um olle { $total } Komponentn z'segn.

help-name-summary = { $name } — { $summary }

help-ref-is-reference =
    { $line ->
        [none] { $ref } is a Referenz auf { $target }.
       *[other] { $ref } is a Referenz auf { $target } (Zeiln { $line }).
    }

help-ref-derived-from =
    { $line ->
        [none] Eingfüaht vo { $owner } ois { $role }.
       *[other] Eingfüaht vo { $owner } auf da Zeiln { $line } ois { $role }.
    }

help-property-is-reference =
    { $line ->
        [none] { $ref } is a Referenz auf d Eigenschaft { $property } vo { $element }.
       *[other] { $ref } is a Referenz auf d Eigenschaft { $property } vo { $element } (Zeiln { $line }).
    }

help-kind-attribute = Attribut
help-kind-snippet = Textbaustoa
help-kind-array-entry = Array-Eintrog

help-default = Standardwert:
help-active-default = Aktiva Standardwert:

help-style-number-annotation = { " " }(styleNumber { $styleNumber })

help-allowed-values =
    { $perItem ->
        [true] Zualässige Werte (oana pro Element):
       *[other] Zualässige Werte:
    }

help-suggested-values = Vorgschlagane Werte:

help-inserts = Fügt ei:

# One form for the count: CLDR has no plural rules for `bar`.
help-coordinates = Koordinatn:

help-type = Typ:

help-resolved-style = Aufglösta Stui (styleNumber { $styleNumber }):

help-resolved-function-names = Aufglöste Funktionsnama:
help-reset-list = Zrucksetz-Listn bei dera Eingob:
help-added-on-input = Bei dera Eingob dazuadoa:
help-removed-on-input = Bei dera Eingob wegganumma:

help-reset-overrides = { $reset } geht vor { $additional } und { $removed }.
