# Swiss German (Schwiizertüütsch) viewer chrome. Translated from
# `locales/en/chrome.ftl`, which is the source of truth: `lint:i18n` rejects a
# key that does not exist there, and reports a key that exists there but not
# here as missing coverage.
#
# Message ids are never translated — only the text to the right of `=`.
#
# UNREVIEWED SEED. Machine-generated, pending review by a speaker (#1521).
# Correct anything here freely; nothing in it was written by a translator.
#
# **Orthography.** This file writes the **Dieth-Schreibung**, the phonetic
# convention Swiss German publishing uses: a long vowel is written double
# («Siite», «wiiss», «Fääler», «Ziile»), and **there is no ß anywhere** — the
# letter is not part of Swiss orthography at all, and «wiiss», «grüess»,
# «heissed» are spelled with «ss» in every position. That is the sharpest
# visible break from `locales/de`, and a corrector who reintroduces a ß is
# writing German, not Swiss German.
#
# **This is a written standard over a spread of dialects.** Swiss German has
# no single official spelling and no single variety; this file uses the
# Zurich-based koine, not Bernese, not Basel, not Valais. That is the trade
# `locales/sc` and `locales/rm` already record: a deployment that wants a
# particular dialect supplies its own catalog as `localeResources`, and
# correcting this file toward one dialect sentence by sentence would leave it
# in two at once.
#
# **Do not edit this file toward Standard German.** The words that differ are
# the point of the catalog, not mistakes: «nöd» for «nicht», «chan» for
# «kann», «gseh» for «sehen», «Fähler» for «Fehler», «Siite» for «Seite»,
# «Chreis» for «Kreis», «zrugg» for «zurück», «öppis» for «etwas». A reviewer
# who normalizes these has produced a second copy of `locales/de`.
#
# **There is no simple past.** Swiss German lost the preterite entirely and
# uses the perfect throughout, which is why every past-tense sentence in
# English comes out here as a perfect: «hät nöd chöne glade werde», not «wurde
# nicht geladen».
#
# **Number.** CLDR *does* have plural rules for `gsw` — `one` and `other` — so
# a category branch here is selected by Swiss German's own rules, unlike the
# seven catalogs of this batch that CLDR has no data for and where every count
# has to fall through to `other`. There is no `zero`, `two`, `few` or `many`
# category in `gsw`, so never write one. The split is written out wherever the
# noun actually changes («Antwort» / «Antworte»); where it does not («Versuech»
# is the same in both numbers) the two branches read alike, and that is
# correct rather than an omission.
#
# Register: impersonal throughout — infinitives and bare nouns, no `du` and no
# `Sie` form, the same policy `locales/de` follows.


## Answer submission

answer-checking = Wird prüeft …
answer-submitting = Wird gschickt …
answer-checking-status = D Antwort wird prüeft
answer-submitting-status = D Antwort wird gschickt
answer-correct = Richtig
answer-incorrect = Falsch
answer-response-saved = Antwort gspeicheret
answer-percent-credit = { $percent } % Aarächnig
answer-percent-correct = { $percent } % richtig
answer-percent-short = { $percent } %
max-credit-available = Am meischte z hole: { $percent } %
# «Versuech» is the same in the singular and the plural, so the two branches
# say the same thing; the `[0]` key is symbolic and stays as it is.
attempts-remaining =
    { $count ->
        [0] kei Versuech meh übrig
        [one] no { $count } Versuech übrig
       *[other] no { $count } Versuech übrig
    }
validation-correct = (Richtig)
validation-incorrect = (Falsch)
validation-partially-correct = (Teilwiis richtig)
answer-show-responses =
    { $count ->
        [one] { $count } Antwort uf { $answerId } zeige
       *[other] { $count } Antworte uf { $answerId } zeige
    }

## Disclosure panels

feedback-heading = Rückmäldig
collapsible-click-to-open = (zum Uufmache klicke)
collapsible-click-to-close = (zum Zuemache klicke)
collapsible-initializing = Wird ufgstartet …
footnote-show = D Fuessnote zeige
footnote-hide = D Fuessnote uusblände
description-more-information = meh Informatione

## Controls

slider-previous = Zrugg
slider-next = Wiiter
keyboard-open = Tastatur uufmache
keyboard-close = Tastatur zuemache
choice-input-remove-choice = { $choice } ewägnäh
matrix-remove-row = Ziile ewägnäh
matrix-add-row = Ziile zuefüege
matrix-remove-column = Spalte ewägnäh
matrix-add-column = Spalte zuefüege
subset-add-remove-points = Pünkt zuefüege / ewägnäh
subset-toggle-points-intervals = Zwüsched Pünkt und Intervall wächsle
subset-move-points = Pünkt verschiebe
subset-clear = Läere
# A `box` here is one orbital, drawn as a square: «Chäschtli».
orbital-add-row = Ziile zuefüege
orbital-remove-row = Ziile ewägnäh
orbital-add-box = Chäschtli zuefüege
orbital-remove-box = Chäschtli ewägnäh
orbital-add-up-arrow = Pfiil ufe zuefüege
orbital-add-down-arrow = Pfiil abe zuefüege
orbital-remove-arrow = Pfiil ewägnäh
orbital-row-label = Bschriftig für d Ziile { $row }
pretzel-answer = Antwort

## Math input

math-input-preview-region = Vorschau vom mathematische Uusdruck
math-input-preview = Vorschau
math-input-invalid-expression = Ungültige Uusdruck:

## Document status

viewer-initializing = Wird ufgstartet …

## Errors

error-heading = Fähler
error-found-at =
    { $span ->
        [line] Gfunde uf de Ziile { $startLine }.
       *[lines] Gfunde uf de Ziile { $startLine }–{ $endLine }.
    }
document-contains-errors = Das Dokumänt hät Fähler dinn!
diagnostic-heading-error = Fähler
diagnostic-heading-warning = Warnig
diagnostic-heading-information = Info
diagnostic-heading-hint = Hiiwiis
# `WCAG AA` is the name of the standard and is not translated.
accessibility-heading-level-1 = Verstoss gäge WCAG AA (Barrierefreiheit)
accessibility-heading-level-2 = Hiiwiis zur Barrierefreiheit
something-went-wrong = Öppis isch schief gloffe.
renderer-load-failed = en Aazeigmodul hät nöd chöne glade werde. Bitte d Siite nöi lade.
core-start-failed = Das Dokumänt hät nöd chöne gstartet werde. Bitte d Siite nöi lade.
core-start-failed-busy = Das Dokumänt hät nöd chöne gstartet werde. Es sind mehreri Dokumänt uf einisch gstartet, und uf eme langsamere Grät cha das länger duure. D Siite nöi lade cha hälfe, sobald die andere Dokumänt fertig sind.
core-start-failed-retry = Das Dokumänt hät nöd chöne gstartet werde.
core-start-failed-busy-retry = Das Dokumänt hät nöd chöne gstartet werde. Es sind mehreri Dokumänt uf einisch gstartet, und uf eme langsamere Grät cha das länger duure.
core-start-retry = Nomal probiere
saved-state-unavailable = Dini gspeicherti Arbet hät nöd chöne glade werde.
