# Swiss German (Schwiizertüütsch) content catalog: the prose the core computes
# into the document. Selected by `documentLocale` — the language the activity
# was written in.
#
# UNREVIEWED SEED. Machine-generated, pending review by a speaker (#1521).
# Correct anything here freely; nothing in it was written by a translator.
#
# **Orthography.** The Dieth-Schreibung, the phonetic convention Swiss German
# publishing uses: long vowels are written double («Siite», «wiiss», «Fääler»,
# «Ruute»), and **there is no ß anywhere** — «wiiss», «grüess», «heissed» take
# «ss» in every position. That is the sharpest visible break from `locales/de`,
# and a ß reintroduced here is German rather than Swiss German.
#
# **This is a written standard over a spread of dialects.** Swiss German has no
# single official spelling and no single variety; this file uses the
# Zurich-based koine, not Bernese, not Basel, not Valais — the trade
# `locales/sc` and `locales/rm` already record. A deployment that wants a
# particular dialect supplies its own catalog as `localeResources`; correcting
# this file toward one dialect word by word would leave it in two at once.
#
# **Do not edit this file toward Standard German.** The differing words are the
# catalog: «nöd» for «nicht», «chan» for «kann», «gseh» for «sehen», «Fähler»
# for «Fehler», «Siite» for «Seite», «lueg» for «schau», «Chreis» for «Kreis».
#
# **There is no simple past.** Swiss German lost the preterite entirely and
# uses the perfect throughout, which is why any past-tense sentence here reads
# as a perfect.
#
# **Number.** CLDR *does* have plural rules for `gsw` — `one` and `other` — so
# a category branch is selected by Swiss German's own rules, unlike the seven
# catalogs of this batch CLDR has no data for. There is no `zero`, `two`, `few`
# or `many` category, so never write one.
#
# Swiss German inflects the way German does: the attributive adjective goes
# *before* the noun and takes an ending that depends on the noun's gender and
# on the case its position governs. Every adjective below therefore selects on
# `$role` first and then, where it matters, on `$gender`:
#
#   standalone          no article, so the strong endings: `-e` m, `-i` f,
#                       `-s` n («en dicke Strich», «e dicki Linie»,
#                       «es dicks Quadraat»)
#   border-clause       after «mit eme» / «und eme», which govern the dative:
#                       `-e`, the same for every gender
#   background-clause   after «uf eme», dative again: `-e`
#   text-clause         predicative, where nothing is inflected at all: the
#                       bare stem, «rot uf eme gääle Hindergrund»
#
# The Swiss German dative is where this parts company with `locales/de` in
# grammar rather than only in spelling: the strong dative German writes as
# `-em` («mit dickem Rand», «auf gelbem Hintergrund») does not exist here. The
# article is used instead — «mit eme dicke Rand» — so the dative ending is a
# flat `-e` and the article is written into the composition message.
#
# **The periodic table is left to fall back to English.** Secondary science in
# German-speaking Switzerland is taught in Standard German out of Standard
# German textbooks, so the table a Swiss pupil actually meets is
# `locales/de`'s, which is the parallel text for anyone who wants to fill these
# in. That is a fact about a school system rather than about the language, and
# a reviewer should copy `locales/de` deliberately rather than have this seed
# invent dialect element names nobody writes.


## Style vocabulary

color =
    .black =
        { $role ->
            [border-clause] schwarze
            [background-clause] schwarze
            [text-clause] schwarz
           *[standalone]
                { $gender ->
                    [f] schwarzi
                    [n] schwarzes
                   *[m] schwarze
                }
        }
    .white =
        { $role ->
            [border-clause] wiisse
            [background-clause] wiisse
            [text-clause] wiiss
           *[standalone]
                { $gender ->
                    [f] wiissi
                    [n] wiisses
                   *[m] wiisse
                }
        }
    .gray =
        { $role ->
            [border-clause] graue
            [background-clause] graue
            [text-clause] grau
           *[standalone]
                { $gender ->
                    [f] graui
                    [n] graus
                   *[m] graue
                }
        }
    .red =
        { $role ->
            [border-clause] rote
            [background-clause] rote
            [text-clause] rot
           *[standalone]
                { $gender ->
                    [f] roti
                    [n] rots
                   *[m] rote
                }
        }
    .orange =
        { $role ->
            [border-clause] orangefarbige
            [background-clause] orangefarbige
            [text-clause] orangefarbig
           *[standalone]
                { $gender ->
                    [f] orangefarbigi
                    [n] orangefarbigs
                   *[m] orangefarbige
                }
        }
    .yellow =
        { $role ->
            [border-clause] gääle
            [background-clause] gääle
            [text-clause] gääl
           *[standalone]
                { $gender ->
                    [f] gääli
                    [n] gääls
                   *[m] gääle
                }
        }
    .green =
        { $role ->
            [border-clause] grüene
            [background-clause] grüene
            [text-clause] grüen
           *[standalone]
                { $gender ->
                    [f] grüeni
                    [n] grüens
                   *[m] grüene
                }
        }
    .cyan =
        { $role ->
            [border-clause] cyanfarbige
            [background-clause] cyanfarbige
            [text-clause] cyanfarbig
           *[standalone]
                { $gender ->
                    [f] cyanfarbigi
                    [n] cyanfarbigs
                   *[m] cyanfarbige
                }
        }
    .blue =
        { $role ->
            [border-clause] blaue
            [background-clause] blaue
            [text-clause] blau
           *[standalone]
                { $gender ->
                    [f] blaui
                    [n] blaus
                   *[m] blaue
                }
        }
    .purple =
        { $role ->
            [border-clause] violette
            [background-clause] violette
            [text-clause] violett
           *[standalone]
                { $gender ->
                    [f] violetti
                    [n] violetts
                   *[m] violette
                }
        }
    .pink =
        { $role ->
            [border-clause] rosafarbige
            [background-clause] rosafarbige
            [text-clause] rosafarbig
           *[standalone]
                { $gender ->
                    [f] rosafarbigi
                    [n] rosafarbigs
                   *[m] rosafarbige
                }
        }
    .brown =
        { $role ->
            [border-clause] bruune
            [background-clause] bruune
            [text-clause] bruun
           *[standalone]
                { $gender ->
                    [f] bruuni
                    [n] bruuns
                   *[m] bruune
                }
        }
line-width =
    .thick =
        { $role ->
            [border-clause] dicke
            [background-clause] dicke
            [text-clause] dick
           *[standalone]
                { $gender ->
                    [f] dicki
                    [n] dicks
                   *[m] dicke
                }
        }
    .thin =
        { $role ->
            [border-clause] dünne
            [background-clause] dünne
            [text-clause] dünn
           *[standalone]
                { $gender ->
                    [f] dünni
                    [n] dünns
                   *[m] dünne
                }
        }
line-style =
    .dashed =
        { $role ->
            [border-clause] gstrichlete
            [background-clause] gstrichlete
            [text-clause] gstrichlet
           *[standalone]
                { $gender ->
                    [f] gstrichleti
                    [n] gstrichlets
                   *[m] gstrichlete
                }
        }
    .dotted =
        { $role ->
            [border-clause] gpünktlete
            [background-clause] gpünktlete
            [text-clause] gpünktlet
           *[standalone]
                { $gender ->
                    [f] gpünktleti
                    [n] gpünktlets
                   *[m] gpünktlete
                }
        }
# Noun phrases in the dative plural: they follow «mit» and agree with nothing.
# «Linie» and «Ruute» do not change in the plural.
fill-style =
    .horizontal = waagrächte Linie
    .vertical = senkrächte Linie
    .diagonal = diagonale Linie
    .backdiagonal = gägeläufige diagonale Linie
    .dots = Pünkt
    .diamonds = Ruute
noun =
    .line = Linie
    .line-segment = Strecke
    .ray = Straal
    .vector = Vektor
    .curve = Kurve
    .function = Funktion
    .slope-field = Steigigsfäld
    .vector-field = Vektorfäld
    .parabola = Parabel
    .polyline = Streckezug
    .polygon = Vileck
    .triangle = Drüüeck
    .rectangle = Rächteck
    .circle = Chreis
    .region = Beriich
    .point = Punkt
    .square = Quadraat
    .diamond = Ruute
    .cross = Chrüz
    .plus = Pluszeiche
# Like German, Swiss German keeps the side count in front of the noun as a
# compound, so the whole thing is one head and there is no tail.
noun-regular-polygon =
    { $part ->
        [tail] { "" }
       *[head] regelmässigs { $numSides }-Eck
    }
# Besides the nouns above, `$noun` can be `regular-polygon` (which is
# `{ $numSides }-Eck`, neuter) or the head of a phrase the description never
# names. Those four: `border` is «de Rand», masculine; `fill` is «d Füllig»,
# feminine; `text` is «de Täxt», masculine; `background` is «de Hindergrund»,
# masculine. Three of the four are masculine, which is what the default answers,
# so only `fill` needs a branch of its own.
noun-gender =
    { $noun ->
        [border] m
        [line] f
        [curve] f
        [function] f
        [parabola] f
        [diamond] f
        [fill] f
        [line-segment] f
        [polygon] n
        [triangle] n
        [rectangle] n
        [square] n
        [cross] n
        [plus] n
        [slope-field] n
        [vector-field] n
        [region] m
        [regular-polygon] n
       *[other] m
    }

## Style composition

style-stroke =
    { $parts ->
        [width-style-color] { $width } { $lineStyle } { $color }
        [width-color] { $width } { $color }
        [style-color] { $lineStyle } { $color }
        [width-style] { $width } { $lineStyle }
        [width] { $width }
        [style] { $lineStyle }
       *[color] { $color }
    }
# The adjectives lead and the noun closes the phrase, as in German and in
# English: «dicki roti Linie».
style-with-noun =
    { $parts ->
        [noun-tail] { $description } { $noun } { $nounTail }
       *[noun] { $description } { $noun }
    }
# Only ever said of the shape itself, so it is standalone in every description
# and takes no `$role` branch.
style-filled-word =
    { $gender ->
        [f] gfülleti
        [n] gfüllts
       *[m] gfüllte
    }
style-filled =
    { $parts ->
        [pattern] { $filled } { $color } mit { $pattern }
       *[plain] { $filled } { $color }
    }
style-filled-with-noun =
    { $parts ->
        [pattern] { $filled } { $color } { $noun } mit { $pattern }
        [plain-tail] { $filled } { $color } { $noun } { $nounTail }
        [pattern-tail] { $filled } { $color } { $noun } { $nounTail } mit { $pattern }
       *[plain] { $filled } { $color } { $noun }
    }
# «Rand» is masculine, so the border's adjectives agree with it and not with
# the shape it surrounds. «mit» and «und» govern the dative, which is the
# `border-clause` branch of every adjective — a flat `-e` here, because Swiss
# German has no strong dative `-em` and uses the article instead. Every branch
# therefore takes «eme», including the two English leaves the article off:
# a bare dative is not available to write, so keeping the article in all four
# collapses the distinction rather than getting one of them wrong.
style-border-clause =
    { $parts ->
        [with-article] mit eme { $border } Rand
        [and] und eme { $border } Rand
        [and-article] und eme { $border } Rand
       *[with] mit eme { $border } Rand
    }
# The fill-pattern words are dative plurals, because their other use is the
# «mit { $pattern }» clause in `style-filled`. So this message supplies a noun
# for them to hang off — «Füllig», feminine, which is the gender `noun-gender`
# answers for `fill`, so the colour agrees with it in both variants.
style-fill =
    { $parts ->
        [pattern] { $color } Füllig mit { $pattern }
       *[plain] { $color } Füllig
    }
style-unfilled = ungfüllt
# «uf eme» governs the dative, which is the `background-clause` ending; the
# text colour beside it is predicative, which here is the bare stem. So this
# reads «rot uf eme gääle Hindergrund», where the `textColor` and
# `backgroundColor` variables — the standalone side of the same two words —
# read «rote» and «gääle».
style-text =
    { $parts ->
        [background] { $color } uf eme { $background } Hindergrund
       *[plain] { $color }
    }
style-background-none = keine

## Boolean words

boolean-true = wahr
boolean-false = falsch

## Answer buttons

answer-submit-label = Prüefe
answer-submit-label-no-correctness = Antwort schicke

## Sectional blocks

section-name =
    .activity = Aktivität
    .aside = Iischub
    .cascade = Kaskade
    .definition = Definition
    .example = Bispil
    .exercise = Uebig
    .exercises = Uebige
    .given-answer = Antwort
    .note = Aamerkig
    .objectives = Lernziel
    .paragraphs = Absätz
    .part = Teil
    .problem = Ufgab
    .problems = Ufgabe
    .proof = Bewiis
    .question = Frog
    .section = Abschnitt
    .solution = Lösig
    .task = Ufgab
    .theorem = Satz
section-title-prefix =
    { $parts ->
        [name] { $sectionName }
        [number] { $sectionNumber }
        [name-title] { $sectionName }{ ": " }
        [number-title] { $sectionNumber }{ ". " }
        [name-number-title] { $sectionName } { $sectionNumber }{ ": " }
       *[name-number] { $sectionName } { $sectionNumber }
    }
hint-title = Tipp

## Tables and figures

table-name =
    { $parts ->
        [numbered] Tabälle { $enumeration }
        [numbered-title] Tabälle { $enumeration }{ ": " }
        [unnumbered-title] Tabälle{ ": " }
       *[unnumbered] Tabälle
    }
figure-name =
    { $parts ->
        [numbered] Abbildig { $enumeration }
        [numbered-caption] Abbildig { $enumeration }{ ": " }
        [unnumbered-caption] Abbildig{ ": " }
       *[unnumbered] Abbildig
    }

## Paginator controls

paginator-previous = Zrugg
paginator-next = Wiiter
paginator-page = Siite
paginator-page-status = { $pageLabel } { $currentPage } vo { $numPages }

## Piecewise functions

piecewise-condition-or = oder
piecewise-condition-if = wänn
piecewise-condition-otherwise = suscht

## Chemistry
##
## `element-name` and `element-anion-name` are deliberately absent: they fall
## back to English, and `locales/de` is the parallel text a reviewer should
## copy from. See the header.

ion-name-oxidation-state = { $name } ({ $numeral })
chemistry-invalid-symbol = Ungültigs chemischs Symbol
chemistry-invalid-ionic-compound = Ungültigi Ioneverbindig

## Inputs embedded in math

math-embedded-input-blank = Lücke
math-embedded-input-blank-ordinal = Lücke { $ordinal } vo { $total }
