# Swiss German (Schwiizertüütsch) diagnostics. Translated from
# `locales/en/diagnostics.ftl`, which is the source of truth: `lint:i18n`
# rejects a key that does not exist there, and reports a key that exists there
# but not here as missing coverage.
#
# UNREVIEWED SEED. Machine-generated, pending review by a speaker (#1521).
# Correct anything here freely; nothing in it was written by a translator.
#
# **Orthography.** The Dieth-Schreibung, the convention Swiss German publishing
# uses: long vowels written double («Siite», «wiiss», «Fääler», «Chreis»), and
# **no ß anywhere** — «ss» in every position. That is the sharpest visible
# break from `locales/de`; see `chrome.ftl` for the full note.
#
# **This is a written standard over a spread of dialects**, and this file uses
# the Zurich-based koine rather than Bernese, Basel or Valais — the trade
# `locales/sc` and `locales/rm` already record. A deployment that wants a
# particular dialect supplies its own catalog as `localeResources`.
#
# **Do not edit this file toward Standard German**: «nöd» for «nicht», «chan»
# for «kann», «gseh» for «sehen», «Fähler» for «Fehler», «Siite» for «Seite»,
# «lueg» for «schau» are the catalog, not mistakes.
#
# **There is no simple past.** Swiss German lost the preterite entirely and
# uses the perfect throughout, which is why every past-tense sentence here
# reads as a perfect: «hät nöd chöne bestimmt werde», never a preterite.
#
# **Number.** CLDR *does* have plural rules for `gsw` — `one` and `other` — so
# a category branch is selected by Swiss German's own rules, unlike the six
# catalogs of this batch CLDR has no data for and where everything falls
# through to `other`. There is no `zero`, `two`, `few` or `many` category, so
# never write one; the branch is written wherever the noun actually changes.
#
# Attribute names, element names and every other DoenetML identifier —
# `through`, `endpoint`, `midpointOffset`, `numDimensions`, `styleNumber`,
# `selectFromSequence`, `<answer>`, `maxNumAttempts`, `sectionWideCheckWork` —
# are part of the language, not prose, and stay in English exactly as written.
# So does anything quoted back from the author's own source, and so do
# `WCAG AA`, `DoenetML`, `PreFigure`, `prefigure`, `XML`, `mathjs` and `Dast`,
# which are names. Every **symbolic** selector — `$type`, `$mode`, `$reason`,
# `$context`, `$suggestion`, `$alternative`, `$fallback`, `$expected`,
# `$labelKind`, `$isList`, `$componentType` — is kept byte for byte from
# English, keys included.


## `<lineSegment>`

line-segment-attributes-ignored-with-endpoints =
    { $attributesCount ->
        [one] { $attributes } wird ignoriert, wänn zwee Ändpünkt aagäh sind
       *[other] { $attributes } wärded ignoriert, wänn zwee Ändpünkt aagäh sind
    }

line-segment-attributes-ignored-with-endpoint-and-midpoint =
    { $attributesCount ->
        [one] { $attributes } wird ignoriert, wänn en Ändpunkt und en Mittelpunkt beedi aagäh sind
       *[other] { $attributes } wärded ignoriert, wänn en Ändpunkt und en Mittelpunkt beedi aagäh sind
    }

line-segment-midpoint-offset-without-midpoint = midpointOffset hät kei Wirkig ohni en Mittelpunkt

## `<line>`

line-points-undetermined-dimensions = Grad dur Pünkt mit unbestimmte Dimensione.

line-points-too-few-dimensions = D Grad mues dur Pünkt mit mindeschtens zwo Dimensione goo.

line-points-depend-on-variables = D Grad goot dur Pünkt, wo vo Variable abhänged: { $variables }.

line-equation-invalid-format = Ungültigs Format für d Gliichig vo de Grad i de Variable { $variable1 } und { $variable2 }.

## `<ray>`

ray-overprescribed-through = De Strahl isch dur through, endpoint und direction festgleit.  Es aagäh through wird ignoriert.

ray-dimension-mismatch = numDimensions passt im Strahl nöd zäme.

## `<vector>`

vector-overprescribed-head = De Vektor isch dur head, tail und displacement festgleit.  Es aagäh head wird ignoriert.

vector-dimension-mismatch = numDimensions passt im Vektor nöd zäme.

## Attracting and constraining

attract-to-without-nearest-point = Cha nöd uf es `<{ $component }>` aazoge werde, wil s kei nearestPoint-Zuestandsvariable hät.

constrain-to-without-nearest-point = Cha nöd uf es `<{ $component }>` iigschränkt werde, wil s kei nearestPoint-Zuestandsvariable hät.

constrain-to-interior-without-nearest-point = Cha nöd uf s Inneri vom ene `<{ $component }>` iigschränkt werde, wil s kei nearestPoint-Zuestandsvariable hät.

## `<choiceInput>`

choice-input-label-position-ignored = labelPosition wird bi eme nöd-inline choiceInput ignoriert

## Ordering children by index

choice-input-indices-count-mismatch = D Indize für choiceInput wärded ignoriert, wil d Aazahl Indize nöd zur Aazahl vo de Uuswahl-Chinder passt.

pretzel-indices-count-mismatch = D Indize für problem wärded ignoriert, wil d Aazahl Indize nöd zur Aazahl vo de problem-Chinder passt.

shuffle-indices-count-mismatch = D Indize für shuffle wärded ignoriert, wil d Aazahl Indize nöd zur Aazahl vo de Komponänte passt.

indices-ignored-out-of-range = D Indize für { $component } wärded ignoriert, wil es Indize usserhalb vom Beriich hät.

pretzel-indices-repeated = D Indize für pretzel wärded ignoriert, wil es Indize doppelt hät.

pretzel-circuit-first-index = D Indize für pretzel im circuit-Modus wärded ignoriert, wil de erscht Index 1 sii mues.

## `<shuffle>` and `<sort>`

string-children-need-type = Damit `<{ $component }>` mit Zeichechette-Chinder funktioniert, mues es `type`-Attribut aagäh sii.

invalid-type-defaulting-to-math = Ungültige type { $type } für d Komponänte { $component }. Mues eis vo math, text, number oder boolean sii. Es wird math gnoh.

string-not-valid-component-to-arrange = D Zeichechette "{ $value }" isch kei gültigi Komponänte für { $component }. Wird ignoriert.

## Types and variables

invalid-type-defaulting-to-number = Ungültige type { $type }, de Typ wird uf number gsetzt.

invalid-variable-value = Ungültige Wärt vo ere Variable: `{ $value }`

## Variants

variant-index-must-be-number = De Variante-Index { $index } mues e Zahl sii

variant-index-must-be-integer = De Variante-Index { $index } mues e ganzi Zahl sii

## `<sideBySide>`

side-by-side-absolute-widths = `<{ $component }>` isch für absoluti Mäss nöd umgsetzt. D Breiti wird uf relativ gsetzt.

side-by-side-absolute-margins = `<{ $component }>` isch für absoluti Mäss nöd umgsetzt. D Ränder wärded uf relativ gsetzt.

side-by-side-no-block-child = Ungültigs `<{ $component }>`: es mues mindeschtens es Block-Chind ha.

## `<label>`

label-for-ignored-on-graphical = S `for`-Attribut a mene grafische `<label>` wird ignoriert.

label-for-must-resolve-to-one = S `for`-Attribut a mene `<label>` mues genau ei Komponänte ergäh.

label-for-unresolved = S `for`-Attribut a mene `<label>` hät nöd chöne uf e Komponänte ufglöst werde.

label-for-answer-with-authored-inputs = S `for`-Attribut a mene `<label>` verwiist uf es `<answer>` mit uusdrücklich gschribne Iigabe; verwiis direkt uf d Iigab.

label-for-answer-without-input = S `for`-Attribut a mene `<label>` verwiist uf es `<answer>` ohni Iigab zum Bschrifte.

label-for-must-reference-input-or-answer = S `for`-Attribut a mene `<label>` mues uf e Iigab oder es answer verwiise.

## Accessibility

accessibility-short-description-or-decorative = Für d Barrierefreiheit mues `<{ $component }>` entweder e churzi Bschriibig ha oder als dekorativ aagäh sii.

accessibility-video-short-description = Für d Barrierefreiheit mues `<video>` e churzi Bschriibig ha.

accessibility-input-short-description-or-label = Für d Barrierefreiheit mues `<{ $component }>` e churzi Bschriibig oder es Label ha.

accessibility-answer-input-short-description-or-label = Für d Barrierefreiheit mues es `<answer>`, wo e Iigab erstellt, e churzi Bschriibig oder es Label ha.

accessibility-short-description-contains-math = Churzi Bschriibige söttet kei Mathe-Komponänte wie `<{ $component }>` dinn ha. Schriib d Mathematik mit Wört uus.

accessibility-section-title-insufficient-contrast =
    { $mode ->
        [dark] { $colorName } hät z wenig Kontrascht für de Täxt vom Abschnitts-Titel (dunkle Modus) ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindeschtens { $threshold }:1).
       *[other] { $colorName } hät z wenig Kontrascht für de Täxt vom Abschnitts-Titel ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindeschtens { $threshold }:1).
    }

## `<circle>`

circle-through-points-non-numerical = En `<circle>` dur { $count } Pünkt isch nöd umgsetzt für de Fall, wo d Pünkt kei numerischi Wärt händ.

circle-too-many-through-points = En Chreis dur meh als 3 Pünkt cha nöd brächnet werde.

circle-overprescribed-radius-center-points = En Chreis mit aagähem Radius, Mittelpunkt und Durchgangspünkt cha nöd brächnet werde.

circle-center-with-multiple-points = En Chreis mit aagähem Mittelpunkt dur meh als 1 Punkt cha nöd brächnet werde.

circle-radius-too-small = De Chreis cha nöd brächnet werde: wil de Abstand zwüsched de zwee Pünkt { $distance } isch, isch de aagäh Radius { $radius } z chlii.

circle-radius-with-many-points = En Chreis dur meh als zwee Pünkt mit eme aagähne Radius cha nöd erstellt werde.

circle-invalid-center-or-through-points = Ungültige Mittelpunkt oder ungültigi Durchgangspünkt vom Chreis.

circle-radius-center-with-multiple-points = De Radius vom ene Chreis mit aagähem Mittelpunkt dur meh als 1 Punkt cha nöd brächnet werde.

circle-change-radius-non-numerical = De Radius vom ene Chreis mit nöd-numerische Durchgangspünkt cha nöd gänderet werde

circle-radius-with-points-non-numerical = En Chreis dur meh als ei Punkt mit eme aagähne Radius cha nöd erstellt werde, wänn kei numerischi Wärt do sind.

circle-change-center-non-numerical = S Ändere vom Mittelpunkt vom ene Chreis dur Pünkt ohni numerischi Wärt isch nöd umgsetzt.

## `<function>`

function-domain-insufficient-dimensions =
    { $intervals ->
        [one] Z wenig Dimensione für de Definitionsberiich vo de Funktion. De Beriich hät { $intervals } Intervall, aber d Funktion hät { $inputs ->
            [one] { $inputs } Iigab
           *[other] { $inputs } Iigabe
        }.
       *[other] Z wenig Dimensione für de Definitionsberiich vo de Funktion. De Beriich hät { $intervals } Intervall, aber d Funktion hät { $inputs ->
            [one] { $inputs } Iigab
           *[other] { $inputs } Iigabe
        }.
    }

function-domain-invalid-format = Ungültigs Format für de Definitionsberiich vo de Funktion.

function-ignoring-non-numerical =
    { $type ->
        [maximum] S nöd-numerische Maximum vo de Funktion wird ignoriert.
        [minimum] S nöd-numerische Minimum vo de Funktion wird ignoriert.
        [extremum] S nöd-numerische Extremum vo de Funktion wird ignoriert.
        [point] De nöd-numerisch Punkt vo de Funktion wird ignoriert.
        [slope] D nöd-numerischi Steigig vo de Funktion wird ignoriert.
       *[other] S nöd-numerische { $type } vo de Funktion wird ignoriert.
    }

function-ignoring-empty =
    { $type ->
        [maximum] S leere Maximum vo de Funktion wird ignoriert.
        [minimum] S leere Minimum vo de Funktion wird ignoriert.
        [extremum] S leere Extremum vo de Funktion wird ignoriert.
        [point] De leer Punkt vo de Funktion wird ignoriert.
       *[other] S leere { $type } vo de Funktion wird ignoriert.
    }

function-points-too-close = D Funktion hät zwee Pünkt, wo z nooch binenand ligged. D Funktion cha nöd definiert werde.

function-iterates-input-output-mismatch =
    { $inputs ->
        [one] Iterierte vo ere Funktion sind nu möglich, wänn d Aazahl Iigabe glich isch wie d Aazahl Uusgabe. Die Funktion hät { $inputs } Iigab und { $outputs ->
            [one] { $outputs } Uusgab
           *[other] { $outputs } Uusgabe
        }.
       *[other] Iterierte vo ere Funktion sind nu möglich, wänn d Aazahl Iigabe glich isch wie d Aazahl Uusgabe. Die Funktion hät { $inputs } Iigabe und { $outputs ->
            [one] { $outputs } Uusgab
           *[other] { $outputs } Uusgabe
        }.
    }

## `<sequence>`

sequence-invalid-length = Ungültigi Läng vo de Folg.  Mues e nöd-negativi ganzi Zahl sii.

sequence-invalid-step = Ungültige Schritt vo de Folg.  Mues e Zahl sii für e Folg vom Typ { $type }.

sequence-invalid-endpoint-number = Ungültigs "{ $attribute }" vo ere Zahlefolg.  Mues e Zahl sii.

sequence-invalid-endpoint-letters = Ungültigs "{ $attribute }" vo ere Buechstabefolg.  Mues e Buechstabe-Kombination sii.

sequence-invalid-endpoint = Ungültigs "{ $attribute }" vo de Folg.

select-from-sequence-coprime-not-numbers = coprime wird ignoriert, wil kei Zahle uusgwählt wärded

select-from-sequence-coprime-with-exclude-combinations = coprime wird ignoriert, wil excludeCombinations aagäh isch

## Resolving a `target`

target-not-found = Ungültigs target für `<{ $source }>`: s Ziil cha nöd gfunde werde.

target-state-variable-not-found = Ungültigs target für `<{ $source }>`: es git kei Zuestandsvariable mit em Name "{ $property }" a mene `<{ $component }>`.

## `<odeSystem>`

ode-system-variables-match-independent = D Variable vom ene `<odeSystem>` müend anderi sii als d unabhängig Variable.

ode-system-duplicate-variable-names = ODE-RHS-Funktione mit doppelte abhängige Variablenäme chönd nöd definiert werde.

ode-system-rhs-function-error = D ODE-RHS-Funktion cha nöd definiert werde.  Fähler bim Erstelle vo de mathjs-Funktion.

## `<angle>`, `<parabola>`, and `<intersection>`

angle-too-many-lines = En Winkel zwüsched { $count } Grade cha nöd definiert werde

angle-invalid-through-point = Ungültige Punkt im through vom ene `<angle>`

parabola-vertex-too-many-points = E Parabel mit Schitelpunkt dur meh als 1 Punkt isch nöd umgsetzt.

parabola-too-many-points = E Parabel dur meh als 3 Pünkt isch nöd umgsetzt.

intersection-too-many-items = De Schnitt vo meh als zwee Elemänt isch nöd umgsetzt

## Other math components

ionic-compound-not-two-ions = Ioneverbindige mit öppis anderem als zwee Ione sind nöd umgsetzt.

ionic-compound-needs-cation-and-anion = D Ioneverbindig isch nu für es Kation und es Anion umgsetzt.

solve-equations-cannot-evaluate = D Gliichig cha nöd glöst werde, wil si nöd hät chöne uusgwertet werde: { $equation }

math-operators-operand-number-required = Es mues e operandNumber aagäh werde, wänn en Mathe-Operand usezoge wird.

eigen-decomposition-failed = D Eigewärt vo de Matrix händ nöd chöne brächnet werde

## `<matchesPattern>`

matches-pattern-parameter-not-in-pattern =
    { $parametersCount ->
        [one] `<matchesPattern>`: de Parameter { $parameters } chunt im Muschter nöd vor, drum passt er immer uf e Lücke.
       *[other] `<matchesPattern>`: d Parameter { $parameters } chömed im Muschter nöd vor, drum passed si immer uf e Lücke.
    }

## `<graph>`

graph-grid-invalid = `<graph>`: grid="{ $grid }" cha nöd interpretiert werde. Es mues none, medium, dense oder zwo positivi Zahle mit eme Läärschlag drzwüsched sii, zum Bispil grid="1 0.5". Es wird kes Gitter zeichnet.

## `<slopeField>` and `<vectorField>`

field-function-wrong-num-outputs =
    `<{ $component }>` bruucht e Funktion mit { $expected ->
        [one] einere Uusgab, de Steigig y' a jedem Punkt, zum Bispil `y - x`
       *[other] zwo Uusgabe, em Vektor a jedem Punkt, zum Bispil `(y, -x)`
    }, aber die gäh Funktion hät { $found ->
        [one] { $found } Uusgab
       *[other] { $found } Uusgabe
    }. { $alternative ->
        [none] Es wird nüüt zeichnet.
       *[other] `<{ $alternative }>` isch d Komponänte für die Funktion. Es wird nüüt zeichnet.
    }

field-function-attribute-ignored-with-child = S `function`-Attribut wird ignoriert, wil d Funktion au inneren i de Komponänte gäh isch; die inneri wird bruucht. Gib d Funktion nu uf einere vo de zwo Arte aa.

field-variables-ignored =
    `<{ $component }>`: s `variables`-Attribut nänt d Variable vom ene Uusdruck, wo direkt inneren i de Komponänte gschribe isch. { $reason ->
        [function-child] D Funktion isch do als `<function>`-Chind gäh, wo sini eigene Variable nänt, drum wird `variables` ignoriert.
       *[no-expression] Es git do kein settige Uusdruck, drum wird `variables` ignoriert.
    }

## PreFigure renderer

prefigure-x-label-position-unsupported = `<graph>`: xLabelPosition="left" wird im prefigure-Renderer nöd unterstützt; es wird s Verhalte vo de rächte Position bruucht.

prefigure-y-label-position-unsupported = `<graph>`: yLabelPosition="bottom" wird im prefigure-Renderer nöd unterstützt; es wird s Verhalte vo de obere Position bruucht.

prefigure-invalid-axis-bounds = `<graph>`: ungültigi Achsegränze für d prefigure-Umwandlig; es wird d Standard-bbox (-10,-10,10,10) bruucht.

prefigure-invalid-width = `<graph>`: ungültigi Breiti für d prefigure-Umwandlig; es wird d Standard-Diagrammbreiti 425 bruucht.

prefigure-invalid-aspect-ratio = `<graph>`: ungültigs aspectRatio für d prefigure-Umwandlig; es wird s Standard-Sitteverhältnis 1 bruucht.

prefigure-grid-spacing-too-fine = `<graph>`: d Gitterwiiti isch z fii für d Achsegränze; s Gitter wird im prefigure-Renderer wägglo.

prefigure-annotations-not-rendered = `<graph>`: Aamerkige wärded nöd dargstellt, wänn nöd de PreFigure-Renderer bruucht wird.

multiple-annotations-children = Es sind mehreri `<annotations>`-Chinder im `<graph>` gfunde worde; alli usser em letschte wärded ignoriert.

## Referring to other components

copy-unrecognized-component-type = En unbekannte Komponänte-Typ cha nöd erwiiteret oder kopiert werde: { $type }.

copy-prop-not-found = De prop { $property } isch a mene Komponänte vom Typ { $component } nöd gfunde worde

collect-no-source = Für collect isch kei Quelle gfunde worde.

collect-invalid-component-type = Komponänte vom Typ `<{ $component }>` chönd nöd gsammlet werde, wil das kein gültige Komponänte-Typ isch.

reference-index-unavailable = De Index `{ $reference }` cha nöd referenziert werde

## `<callAction>`

component-action-unavailable = { $action } cha uf de Komponänte `{ $reference }` nöd ufgruefe werde

## `<dataFrame>`

data-frame-inconsistent-row-lengths = D Date händ e ungültigi Form.  D Ziile händ ungliichi Länge. Gfunde im componentIdx :{ $componentIdx }

data-frame-duplicate-column-names = D Date händ doppelti Spaltenäme.  Gfunde im componentIdx :{ $componentIdx }

data-frame-missing-column-name = De Date fählt en Spaltename.  Gfunde im componentIdx :{ $componentIdx }

## `<answer>` and scoring

answer-award-depends-on-own-response = Es award vo dere Antwort baut uf de eigene gschickte Antwort vom answer-Tag uf, was zu unerwartetem Verhalte füert.

answer-max-num-attempts-in-section-wide-check-work = `maxNumAttempts` a mene `<answer>` inneren i eme Behälter mit `sectionWideCheckWork` z setze hät kei Wirkig, wil d Aazahl Versuech vom Behälter gsteuret wird. Setz `maxNumAttempts` stattdesse am Behälter.

nested-section-wide-check-work-max-num-attempts = `maxNumAttempts` a mene Behälter mit `sectionWideCheckWork` z setze, wo inneren i eme andere Behälter mit `sectionWideCheckWork` isch, hät kei Wirkig, wil d Aazahl Versuech vom üssere Behälter gsteuret wird. Setz `maxNumAttempts` stattdesse am üssere Behälter.

answer-attributes-need-symbolic-equality =
    { $attributesCount ->
        [one] S Attribut { $attributes } hät kei Wirkig, wänn symbolicEquality nöd gsetzt isch.
       *[other] D Attribut { $attributes } händ kei Wirkig, wänn symbolicEquality nöd gsetzt isch.
    }

answer-invalid-type = Ungültige Typ für d Antwort: { $type }

## `<module>`, `<conditionalContent>`, `<slider>`, `<pretzel>`

module-attribute-child-needs-name = Wil d Komponänte `<{ $component }>` kein Name hät, cha si nöd für es Modul-Attribut bruucht werde

module-attribute-name-already-defined = D Komponänte `<{ $component } name="{ $name }">` cha nöd als Attribut für es Modul bruucht werde, wil de Komponänte-Typ `<module>` scho es Attribut "{ $name }" definiert hät.

conditional-content-condition-ignored = S Attribut `condition` wird a mene `<conditionalContent>` mit case- oder else-Chinder ignoriert.

slider-markers-type-mismatch = De Typ vo de Marker passt nöd zum Typ vom Schieber.

pretzel-problem-needs-statement-and-answer = Ungültigs pretzel: jedes `<problem>` mues ei `<statement>` und ei `<answer>` ha.

pretzel-circuit-first-problem-distractor = Ungültigs pretzel: im mode="circuit" cha s erscht `<problem>` kein Distraktor sii.

## Attribute values

attribute-invalid-values =
    { $valuesCount ->
        [one] Ungültige Wärt { $values } für s Attribut `{ $attribute }`; wird ignoriert.
       *[other] Ungültigi Wärt { $values } für s Attribut `{ $attribute }`; wärded ignoriert.
    }

attribute-must-be-references = Ungültige Wärt `{ $value }` für s Attribut `{ $attribute }`. S Attribut mues us Referenze bestoo, wo mit eme `$` aafanged.

math-input-invalid-function-names = <mathInput>: ungültigi Funktionsnäme i { $attribute } sind ignoriert worde: { $names }. Jede Name mues im aazeigte Teil mindeschtens 2 Zeiche ha (Buechstabe oder Bindestrich); es cha en optionale `|<mathspeak alternative>`-Aahang folge.

## Building components from the source

component-type-invalid = Ungültige Komponänte-Typ: `<{ $componentType }>`

attribute-repeated = S Attribut { $attribute } cha nöd wiederholt werde.

attribute-invalid-for-component = Ungültigs Attribut "{ $attribute }" für e Komponänte vom Typ `<{ $componentType }>`.

## Style definition contrast

style-definition-insufficient-contrast =
    D Stildefinition { $styleNumber } hät z wenig Kontrascht für { $context ->
        [text-on-background] d Täxtfarb gägenüber de Hindergrundfarb
        [high-contrast] d Farb mit hohem Kontrascht gägenüber de Zeichefläche
        [line] d Liniefarb gägenüber de Zeichefläche
        [marker] d Markerfarb gägenüber de Zeichefläche
       *[text-on-canvas] d Täxtfarb gägenüber de Zeichefläche
    }{ $mode ->
        [dark] { " (dunkle Modus)" }
       *[light] { "" }
    } ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindeschtens { $threshold }:1).

style-definition-dark-mode-text-background-contrast =
    Au wänn d Stildefinition { $styleNumber } Farbe aagäh hät, wo im helle Modus gnueg Kontrascht händ, händ die drus abgleitete Farbe für de dunkel Modus z wenig Kontrascht vo de Täxtfarb gägenüber de Hindergrundfarb ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindeschtens { $threshold }:1). { $suggestion ->
        [available] Für gnueg Kontrascht im dunkle Modus entweder de Kontrascht im helle Modus erhöhe (z. B. { $lightAttribute }="{ $lightColor }" setze) oder d Farb für de dunkel Modus überschriibe (z. B. { $darkAttribute }="{ $darkColor }" setze).
       *[none] Für gnueg Kontrascht im dunkle Modus de Kontrascht im helle Modus erhöhe oder d abgleitete Farbe mit textColorDarkMode und/oder backgroundColorDarkMode überschriibe.
    }

style-definition-dark-mode-text-canvas-contrast =
    Au wänn d Stildefinition { $styleNumber } e Täxtfarb aagäh hät, wo im helle Modus gnueg Kontrascht hät, hät die drus abgleiteti Täxtfarb für de dunkel Modus z wenig Kontrascht gägenüber de Zeichefläche ({ NUMBER($ratio, minimumFractionDigits: 2, maximumFractionDigits: 2) }:1; verlangt mindeschtens { $threshold }:1). { $suggestion ->
        [available] Für gnueg Kontrascht im dunkle Modus entweder de Kontrascht im helle Modus erhöhe (z. B. textColor="{ $lightColor }" setze) oder d Farb für de dunkel Modus überschriibe (z. B. textColorDarkMode="{ $darkColor }" setze).
       *[none] Für gnueg Kontrascht im dunkle Modus de Kontrascht im helle Modus erhöhe oder d abgleiteti Farb mit textColorDarkMode überschriibe.
    }

section-multiple-style-palettes = En Abschnitt cha nu ei <stylePalette> uuswähle; es wird die letscht gnoh.

## Unique variants

variant-num-to-select-not-non-negative-integer = d eindütige Variante vo { $component } chönd nöd bestimmt werde, wil numToSelect kei nöd-negativi ganzi Zahl isch.

variant-num-to-select-not-constant-number = d eindütige Variante vo { $component } chönd nöd bestimmt werde, wil numToSelect kei konstanti Zahl isch.

variant-with-replacement-not-constant-boolean = d eindütige Variante vo { $component } chönd nöd bestimmt werde, wil withReplacement kein konstante Boolean isch.

variant-select-weight-disables-unique = Eindütigi Variante für select sind abgschaltet, wänn e Option mit selectWeight oder selectForVariants aagäh isch

variant-coprime-undetermined = d eindütige Variante vo { $component } chönd nöd bestimmt werde, wil nöd bestimmt werde cha, öb coprime immer falsch isch.

variant-attribute-not-constant = d eindütige Variante vo { $component } chönd nöd bestimmt werde, wil { $attribute } kei Konstante isch.

variant-attribute-not-number = d eindütige Variante vo { $component } chönd nöd bestimmt werde, wil { $attribute } kei Zahl isch.

variant-attribute-wrong-type-for-sequence =
    d eindütige Variante vo { $component } vom Typ { $type } chönd nöd bestimmt werde, wil { $attribute } nöd { $expected ->
        [letters-combination] e Kombination vo Buechstabe
        [math-expression] en gültige mathematische Uusdruck
        [integer] e ganzi Zahl
       *[number] e Zahl
    } isch.

variant-length-not-integer = d eindütige Variante vo { $component } chönd nöd bestimmt werde, wil length kei ganzi Zahl isch.

variant-sort-not-implemented = eindütigi Variante vo eme { $component } mit sort sind nöd umgsetzt

variant-exclude-combinations-not-implemented = eindütigi Variante vo eme { $component } mit excludeCombinations sind nöd umgsetzt

variant-math-exclude-not-implemented = eindütigi Variante vo eme { $component } vom Typ math mit exclude sind nöd umgsetzt

variant-non-constant-exclude-not-implemented = eindütigi Variante vo eme { $component } mit nöd-konstantem exclude sind nöd umgsetzt

## PreFigure conversion

prefigure-descendant-unsupported = { $subject }: wird im prefigure-Renderer vom graph nöd unterstützt; de Nochfahr wird übersprunge.

prefigure-descendant-invalid-geometry = { $subject }: nöd-endlichi oder unvollständigi Geometrie; de Nochfahr wird übersprunge.

prefigure-curve-label-omitted = { $subject }: Beschriftige wärded a umgwandlete Kurve-Elemänt nöd unterstützt; s Label wird wägglo.

prefigure-curve-unsupported-definition-type = { $subject }: de Definitionstyp '{ $definitionType }' vo de Kurvefunktion wird nöd unterstützt; de Nochfahr wird übersprunge.

prefigure-region-flip-functions-unsupported = { $subject }: s flipFunctions-Attribut a regionBetweenCurves wird nöd unterstützt; de Nochfahr wird übersprunge.

prefigure-region-non-formula-child = { $subject }: a regionBetweenCurves wärded nu Chindfunktione vom Typ Formle unterstützt; de Nochfahr wird übersprunge.

prefigure-label-position-unsupported =
    { $subject }: labelPosition '{ $labelPosition }' wird für es { $labelKind ->
        [line-family] Label us de Grade-Familie
       *[point] Punkt-Label
    } nöd unterstützt; es wird d Standard-Uusrichtig vo PreFigure bruucht.

prefigure-fill-style-unsupported = { $subject }: de Füllstil '{ $fillStyle }' wird vo PreFigure nöd unterstützt; es wird uf e volli Füllig zrugggriffe.

prefigure-line-style-unknown = { $subject }: de unbekannt Linieschtil '{ $lineStyle }' wird i de PreFigure-Uusgab wägglo.

prefigure-marker-style-mapped-to-diamond = { $subject }: de Markerstil '{ $markerStyle }' isch uf de PreFigure-Stil 'diamond' abbildet worde.

prefigure-marker-style-unsupported = { $subject }: de Markerstil '{ $markerStyle }' wird vo PreFigure nöd unterstützt; es wird de Standardstil bruucht.

## PreFigure annotations

annotation-ref-unresolvable = `<annotation>`: ungültige `ref`; s Ziil cha nöd ufglöst werde. D Aamerkig wird wägglo.

annotation-ref-multiple-targets = `<annotation>`: `ref` hät mehreri Ziil ergäh; es wird s erschte gnoh.

annotation-ref-outside-graph = `<annotation>`: ungültige `ref`; s Ziil isch usserhalb vom umgäbende graph. D Aamerkig wird wägglo.

annotation-ref-unsupported-target = `<annotation>`: ungültige `ref`; s Ziil isch i de prefigure-Umwandlig kes unterstützts grafischs Objekt. D Aamerkig wird wägglo.

annotation-text-missing = `<annotation>`: `text` fählt oder isch leer; es wird leere Täxt uusgäh.

## Composites and references

composite-circular-dependency =
    { $componentType ->
        [none] Es isch e zirkuläri Abhängigkeit gfunde worde.
       *[other] Es isch e zirkuläri Abhängigkeit mit ere `<{ $componentType }>`-Komponänte gfunde worde.
    }

reference-no-referent = Kein Bezug für d Referenz gfunde: `{ $reference }`

reference-multiple-referents = Mehreri Bezüg für d Referenz gfunde: `{ $reference }`

## Children that do not match

children-invalid-attribute-format = Ungültigs Format für s Attribut { $attribute } vom ene `<{ $componentType }>`.

children-invalid = Ungültigi Chinder für `<{ $componentType }>`: ungültigi Chinder gfunde: { $children }

## Falling back to a default

attribute-value-invalid-using-default = Ungültige Wärt `{ $value }` für s Attribut `{ $attribute }`, es wird de Wärt `{ $default }` bruucht

## Loading a DoenetML version

doenetml-version-not-found =
    { $fallback ->
        [none] D DoenetML-Version { $version } isch nöd gfunde worde.
       *[other] D DoenetML-Version { $version } isch nöd gfunde worde. Es wird uf d Version { $fallback } zrugggriffe
    }

## Reading the DoenetML

parse-invalid-doenetml = Ungültigs DoenetML: { $content }

parse-tag-missing-close-tag = Ungültigs DoenetML: De Tag `{ $tag }` hät kein Schlusstag. Erwartet isch en sälbschtschliessende Tag oder en `</{ $tagName }>`-Tag.

parse-tag-error = Ungültigs DoenetML: Fähler im Tag `<{ $tagName }>`

parse-attribute-missing-value = Ungültigs DoenetML: Em ungültige Attribut `{ $attribute }` fählt schiins en Wärt.

parse-attribute-invalid = Ungültigs DoenetML: Ungültigs Attribut `{ $attribute }`

parse-attribute-value-invalid = Ungültigs DoenetML: Ungültige Attributwärt `{ $value }`

parse-attribute-value-quote-mismatch = Ungültigs DoenetML: Ungültige Attributwärt `{ $value }`. D Aaführigszeiche passed nöd zäme. Es fählt schiins es `{ $quote }`

parse-open-tag-name-missing = Ungültigs DoenetML: Es isch en Tag ohni Tag-Name gfunde worde, zum Bispil `<`

parse-tag-not-closed = Ungültigs DoenetML: De Tag `{ $tag }` isch nöd gschlosse worde (es `>` fählt schiins).

parse-self-closing-tag-name-missing = Ungültigs DoenetML: Es isch en Tag ohni Tag-Name gfunde worde `<{ $content }>`

parse-self-closing-tag-not-closed = Ungültigs DoenetML: De Tag `{ $tag }` isch nöd gschlosse worde (`/>` fählt schiins).

parse-tag-invalid-attributes = Ungültigs DoenetML: De Tag `{ $tag }` isch nöd gültig. Villicht händ d Attribut Fähler.

parse-close-tag-name-missing = Ungültigs DoenetML: Es isch en Schlusstag ohni Tag-Name gfunde worde, zum Bispil `</`

parse-attribute-value-unquoted = Attributwärt müend i Aaführigszeiche stoo: `{ $attribute }="{ $value }"`

parse-close-tag-without-open-tag = Ungültigs DoenetML: De Schlusstag `{ $tag }` isch gfunde worde, aber es git kein zueghörige Öffnigstag

parse-close-tag-mismatched = Ungültigs DoenetML: De Schlusstag passt nöd. Erwartet isch `</{ $expected }>`. Gfunde isch `{ $found }`

parser-node-unconvertible = De Chnoten { $node } hät nöd chöne i en Dast-Chnote umgwandlet werde.

## Names

name-attribute-invalid =
    Ungültige Attributname name='{ $name }'. { $reason ->
        [characters] Näme dörfed nu Buechstabe, Zahle, Understrich oder Bindestrich enthalte.
       *[start] Näme müend mit eme Buechstabe aafange.
    }

component-name-invalid-start = Ungültige Komponänte-Name "{ $name }". Näme müend mit eme Buechstabe aafange.

## `<answer>` sugar

answer-video-watched-missing-video = E Antwort vom Typ videoWatched mues es video-Attribut ha

answer-video-watched-video-not-reference = E Antwort vom Typ videoWatched mues es video-Attribut ha, wo e Referenz isch

answer-name-not-single-text = S name-Attribut vo ere Antwort mues genau ei Täxt-Chind ha

## Referencing another document

external-doenetml-recursion-limit = S externe DoenetML hät wäge z vil Rekursionsstufe nöd chöne ghole werde. Git s do e zirkuläri Referenz?

external-doenetml-unavailable = S DoenetML vo { $attribute }="{ $uri }" hät nöd chöne ghole werde

external-doenetml-type-mismatch = Ungültigs DoenetML vo { $attribute }="{ $uri }" ghole: es passt nöd zum Komponänte-Typ "{ $componentType }"

## Deprecated syntax

deprecated-attribute-renamed =
    { $component ->
        [none] [deprecation] S Attribut `{ $from }` isch veraltet; bruuch stattdesse `{ $to }`.
       *[other] [deprecation] S Attribut `{ $from }` a `<{ $component }>` isch veraltet; bruuch stattdesse `{ $to }`.
    }

deprecated-attribute-renamed-conflict =
    { $component ->
        [none] [deprecation] S Attribut `{ $from }` isch veraltet und wird ignoriert, wil au `{ $to }` aagäh isch.
       *[other] [deprecation] S Attribut `{ $from }` a `<{ $component }>` isch veraltet und wird ignoriert, wil au `{ $to }` aagäh isch.
    }

deprecated-attribute-ignored = [deprecation] S Attribut `{ $attribute }` a `<{ $component }>` isch veraltet und wird ignoriert.

deprecated-attribute-to-child = [deprecation] S Attribut `{ $attribute }` a `<{ $component }>` isch veraltet; bruuch stattdesse es `<{ $child }>`-Chind.

deprecated-attribute-value-renamed = [deprecation] De Wärt `{ $value }` vom Attribut `{ $attribute }` a `<{ $component }>` isch veraltet; bruuch stattdesse `{ $to }`.


## Language coverage

pluralize-english-only = `<pluralize>` cha nu Änglisch i d Meerzahl setze, drum bliibt de Täxt i eme Dokumänt uf { $locale } so, wie ne de Autor gschribe hät. Schriib d Meerzahlform direkt hi oder setz si mit em `pluralForm`-Attribut.


## Checking against the schema

schema-element-unrecognized = S Elemänt `<{ $tag }>` isch kes bekannts Doenet-Elemänt.

schema-element-not-allowed-at-root = S Elemänt `<{ $tag }>` isch a de Wurzle vom Dokumänt nöd erlaubt.

schema-element-not-allowed-inside = S Elemänt `<{ $tag }>` isch inneren i `<{ $parent }>` nöd erlaubt.

schema-attribute-unrecognized = S Elemänt `<{ $tag }>` hät kes Attribut mit em Name `{ $attribute }`.

schema-attribute-value-not-allowed =
    { $isList ->
        [true] S Attribut `{ $attribute }` vom Elemänt `<{ $tag }>` mues e Lischte sii, wo jedes Element eis vo dene isch: { $allowed }
       *[other] S Attribut `{ $attribute }` vom Elemänt `<{ $tag }>` mues eis vo dene sii: { $allowed }
    }


## The `<select>` family's error boxes

select-variant-name-option-count-mismatch = Ungültige Variantename für select.  De Variantename { $variantName } chunt i { $numOptions } Optione vor, aber d Aazahl zum Uuswähle isch { $numToSelect }.

select-variant-name-without-options = Für select sind Variante aagäh, aber für de möglich Variantename { $variantName } git s kei Optione.

select-variant-name-not-possible = De Variantename { $variantName }, wo für select aagäh isch, isch kein möglich Variantename.

select-too-few-options = { $numToSelect } Komponänte chönd nöd us nume { $numOptions } uusgwählt werde.

select-from-sequence-too-few-values = { $numToSelect } Wärt chönd nöd us ere Folg vo de Läng { $length } uusgwählt werde.

select-from-sequence-indices-count-mismatch = D Aazahl vo de für select aagähne Indize mues zur Aazahl zum Uuswähle passe

select-from-sequence-indices-not-integers = Alli für select aagähne Indize müend ganzi Zahle sii

select-from-sequence-index-excluded = Es isch en Index vo selectfromsequence aagäh, wo uusgschlosse isch

select-from-sequence-indices-excluded-combination = Es sind Indize vo selectfromsequence aagäh, wo e uusgschlossni Kombination sind

select-from-sequence-coprime-not-positive-integers = Teilerfremdi Kombinatione chönd nöd uusgwählt werde, wil kei positivi ganzi Zahle uusgwählt wärded.

select-from-sequence-coprime-common-factor = Teilerfremdi Zahle chönd nöd uusgwählt werde. Alli mögliche Wärt händ en gmeinsame Teiler. (D aagähne Wärt vo "from" oder "to" müend teilerfremd zu "step" sii.)

select-from-sequence-coprime-single-number = Teilerfremdi Kombinatione chönd nöd us ere einzige Zahl uusgwählt werde, wo nöd 1 isch.

select-from-sequence-excluded-too-many-combinations = Über 70 % vo de Kombinatione i selectFromSequence sind uusgschlosse

select-from-sequence-coprime-none-found = Teilerfremdi Zahle händ nöd chöne uusgwählt werde. Alli mögliche Wärt händ en gmeinsame Teiler.

select-from-sequence-too-few-unique-values = { $numToSelect } eindütigi Wärt chönd nöd us ere Folg vo de Läng { $numPossibleValues } uusgwählt werde

select-prime-numbers-too-few-values = { $numToSelect } Wärt chönd nöd us ere Lischte vo Primzahle vo de Läng { $numValues } uusgwählt werde

select-prime-numbers-values-count-mismatch = D Aazahl vo de für select aagähne Wärt mues zur Aazahl zum Uuswähle passe

select-prime-numbers-values-not-prime = Alli Wärt, wo für select prime number aagäh sind, müend i de Lischte vo de Primzahle sii

select-prime-numbers-values-excluded-combination = Die aagähne Wärt vo selectPrimeNumbers sind e uusgschlossni Kombination

select-prime-numbers-excluded-too-many-combinations = Über 70 % vo de Kombinatione i selectPrimeNumbers sind uusgschlosse

select-random-combination-fluke = Dur en usserordentlich unwahrschiinliche Zuefall hät kei Kombination vo zuefällige Wärt chöne uusgwählt werde

select-random-value-fluke = Dur en usserordentlich unwahrschiinliche Zuefall hät kein zuefällige Wärt chöne uusgwählt werde

## Inputs embedded in math

math-embedded-input-shape-unsuitable =
    `<{ $component }>` wird nöd inneren i de Mathematik zeichnet; de Uusdruck wird so gsetzt, wie er vor de iibettete Iigabe gsetzt worde isch. { $reason ->
        [not-inline] Nu e `inline` Uuswahl-Iigab passt inneren i en Uusdruck; ohni `inline` isch si en Block vo Chnöpf.
        [expanded] E `expanded` Täxt-Iigab isch es mehrziiligs Fäld, wo z gross isch zum inneren i eme Uusdruck z sitze.
        [on-graph] Uf eme Graph wird de Uusdruck als eis einzigs Bild zeichnet, wo kein Platz für es Bedienelemänt hät.
       *[relative-width] Sini `width` isch relativ (e Prozäntzahl oder `em`), wo inneren i eme Uusdruck nüüt zum Mässe hät. Gib d Breiti stattdesse i absolute Eiheite aa, zum Bispil `px`.
    }
