# Swiss German (Schwiizertüütsch) editor and language-server surfaces: the
# footer, the diagnostics panel, the variant picker, the accessibility button
# and the context-help panel. Selected by `uiLocale`.
#
# UNREVIEWED SEED. Machine-generated, pending review by a speaker (#1521).
# Correct anything here freely; nothing in it was written by a translator.
#
# **Orthography.** The Dieth-Schreibung, with double vowels for length
# («Siite», «wiiss», «Fääler») and **no ß anywhere**; see `chrome.ftl` for the
# full note. The missing ß is the sharpest visible break from `locales/de`.
#
# **This is a written standard over a spread of dialects**, and this file uses
# the Zurich-based koine rather than Bernese, Basel or Valais — the same trade
# `locales/sc` and `locales/rm` record. A deployment that wants a particular
# dialect supplies its own catalog as `localeResources`.
#
# **Do not edit this file toward Standard German**: «nöd» for «nicht», «chan»
# for «kann», «gseh» for «sehen», «Fähler» for «Fehler», «Siite» for «Seite»,
# «Chreis» for «Kreis» are the catalog, not typos.
#
# **There is no simple past** in Swiss German — the perfect does all of that
# work — which is why the past-tense sentences here read as perfects: «es sind
# kei Verstöss gfunde worde», never a preterite.
#
# **Number.** CLDR *does* have plural rules for `gsw` — `one` and `other` — so
# a category branch here is selected by Swiss German's own rules, unlike the
# seven catalogs of this batch CLDR has no data for. There is no `zero`, `two`,
# `few` or `many` category, so never write one; the branch is written wherever
# the noun actually changes («Verstoss» / «Verstöss»).
#
# **`WCAG`, `WCAG AA`, `DoenetML` and `XML` are names**, not words, and stay in
# English exactly as `locales/en` writes them. So do the DoenetML identifiers
# `styleNumber` and the attribute names in `help-reset-overrides`. Every
# symbolic selector — `$action`, `$status`, `$shortcut`, `$reason`,
# `$location`, `$allowed`, `$line`, `$perItem` — is kept byte for byte from
# English.


## The viewer's controls

editor-update-viewer =
    { $action ->
        [reset] Zrugsetze
       *[update] Aktualisiere
    }

# Swiss German puts the verb last, so the word arrives after the noun it acts
# on, the same shape `locales/de` uses.
editor-update-viewer-title =
    { $shortcut ->
        [none] D Aazeig { $word }
       *[other] D Aazeig { $word } { $shortcut }
    }


## The variant picker

editor-variant = Variante
editor-variant-filter = Filtere …
editor-variant-next = Nächscht Variante uuswähle
editor-variant-previous = Vorherigi Variante uuswähle


## The accessibility status button

editor-accessibility-title =
    { $status ->
        [violations] Es isch en Verstoss gäge WCAG AA gfunde worde. Klicke, zum de Bricht zur Barrierefreiheit { $action ->
            [close] zuemache
           *[open] uufmache
        }.
        [advisories] Klicke, zum de Bricht zur Barrierefreiheit { $action ->
            [close] zuemache
           *[open] uufmache
        }. Es sind kei WCAG-AA-Verstöss gfunde worde, aber es git wiiteri Empfählige zur Barrierefreiheit.
       *[clean] Klicke, zum de Bricht zur Barrierefreiheit { $action ->
            [close] zuemache
           *[open] uufmache
        }. Es sind kei Probläm mit de Barrierefreiheit gfunde worde.
    }

editor-accessibility-label =
    { $status ->
        [violations] Es isch en Verstoss gäge WCAG AA gfunde worde. Es sind { $count ->
            [one] { $count } WCAG-AA-Verstoss
           *[other] { $count } WCAG-AA-Verstöss
        } gfunde worde. Klicke, zum de Bricht zur Barrierefreiheit { $action ->
            [close] zuemache
           *[open] uufmache
        }.
        [advisories] Es sind kei WCAG-AA-Verstöss gfunde worde. Es sind { $count ->
            [one] { $count } wiiteri Empfählig zur Barrierefreiheit
           *[other] { $count } wiiteri Empfählige zur Barrierefreiheit
        } gfunde worde. Klicke, zum de Bricht zur Barrierefreiheit { $action ->
            [close] zuemache
           *[open] uufmache
        }.
       *[clean] Es sind kei WCAG-AA-Verstöss gfunde worde. Klicke, zum de Bricht zur Barrierefreiheit { $action ->
            [close] zuemache
           *[open] uufmache
        }.
    }

editor-accessibility-badge = WCAG


## The footer

editor-version-title = DoenetML-Version { $version }

editor-tab-help = Hilf zum Kontext
editor-tab-help-short = Kontext
editor-tab-errors = Fähler
editor-tab-warnings = Warnige
editor-tab-info = Info
editor-tab-accessibility = Barrierefreiheit
editor-tab-responses = Gschickti Antworte

editor-tab-with-count = { $label }: { $count }

editor-options = Editor-Optione
editor-format-as-doenetml = Als DoenetML formatiere
editor-format-as-xml = Als XML formatiere


## The diagnostics panel

editor-diagnostic-line = Ziile #{ $line }

editor-no-errors = Kei Fähler
editor-no-warnings = Kei Warnige
editor-no-info = Kei Info-Diagnose

editor-show-info-annotations = Info-Diagnose im Editor zeige
editor-show-accessibility-annotations = Diagnose zur Barrierefreiheit im Editor zeige

editor-accessibility-learn-more = Wie Doenet d Barrierefreiheit aagoot

editor-accessibility-violations-heading = Verstöss gäge d Barrierefreiheit ({ $standard })

editor-accessibility-other-heading = Anderi Probläm mit de Barrierefreiheit
editor-none-found = Nüüt gfunde


## Submitted responses

editor-no-responses = No kei Antworte gschickt
editor-response-answer-id = Antwort-Id
editor-response-response = Antwort
editor-response-credit = Aarächnig
editor-response-submitted = Gschickt


## The context-help panel

help-placeholder = De Cursor uf en Tag-Name, es Attribut oder { $ref } setze für d Dokumäntation.

help-unsupported-ref-chain = Hilf zu mehrteilige Referenze wie { $example } git s no nöd.

help-unresolved-ref =
    { $reason ->
        [notFound] Kein Bezug für d Referenz gfunde: { $ref }.
        [multiple] Mehreri Bezüg für d Referenz gfunde: { $ref }.
       *[indeterminate] En Bezug für { $ref } hät sich nöd chöne bestimme.
    }

help-learn-about-references = Meh über Referenze erfahre →
help-reference-page = Referenzsiite →

help-suggestions-header =
    { $location ->
        [inside] Inneren vo { $element }
       *[top] Uf de oberschte Ebeni
    }{ $allowed ->
        [none] { " — do ghört nüüt ane." }
        [text] { " — do Täxt iigeh." }
        [text-and-components] { " — do Täxt iigeh, oder das probiere:" }
       *[components] { " — zum Probiere:" }
    }

help-suggestions-footer = { $shortcut } drucke, zum alli { $total } Komponänte gseh.

help-name-summary = { $name } — { $summary }

help-ref-is-reference =
    { $line ->
        [none] { $ref } isch e Referenz uf { $target }.
       *[other] { $ref } isch e Referenz uf { $target } (Ziile { $line }).
    }

help-ref-derived-from =
    { $line ->
        [none] Iigfüehrt vo { $owner } als { $role }.
       *[other] Iigfüehrt vo { $owner } uf de Ziile { $line } als { $role }.
    }

help-property-is-reference =
    { $line ->
        [none] { $ref } isch e Referenz uf d Eigeschaft { $property } vo { $element }.
       *[other] { $ref } isch e Referenz uf d Eigeschaft { $property } vo { $element } (Ziile { $line }).
    }

help-kind-attribute = Attribut
help-kind-snippet = Täxtbaustei
help-kind-array-entry = Array-Iitrag

help-default = Standardwärt:
help-active-default = Aktive Standardwärt:

help-style-number-annotation = { " " }(styleNumber { $styleNumber })

help-allowed-values =
    { $perItem ->
        [true] Zueglassni Wärt (eine pro Element):
       *[other] Zueglassni Wärt:
    }

help-suggested-values = Vorgschlageni Wärt:

help-inserts = Füegt ii:

help-coordinates =
    { $count ->
        [one] Koordinate:
       *[other] Koordinate:
    }

help-type = Typ:

help-resolved-style = Ufglöste Stil (styleNumber { $styleNumber }):

help-resolved-function-names = Ufglöschti Funktionsnäme:
help-reset-list = Zrugsetz-Lischte a dere Iigab:
help-added-on-input = A dere Iigab zuegfüegt:
help-removed-on-input = A dere Iigab ewägnoh:

help-reset-overrides = { $reset } goot vor { $additional } und { $removed }.
