import { split } from "postcss/lib/list";

export default {
    componentIndex: "Alphabetical Index",
    componentTypes: "Index by Component Type",
    abs: { title: "abs" },
    activity: { title: "activity" },
    alert: { title: "alert" },
    and: { title: "and" },
    angle: { title: "angle" },
    animateFromSequence: { title: "animateFromSequence" },
    answer1: { title: "answer (Basic Use)" },
    answer2a: { title: "answer (Attributes 1)" },
    answer2b: { title: "answer (Attributes 2)" },
    answer3: { title: "answer (Properties)" },
    answer4: { title: "answer (Advanced Use)" },
    asList: { title: "asList" },
    aside: { title: "aside" },
    atom: { title: "atom" },
    attr: { title: "attr" },
    attractTo: { title: "attractTo" },
    attractToConstraint: { title: "attractToConstraint" },
    attractToGrid: { title: "attractToGrid" },
    award: { title: "award (Basic Use)" },
    award2a: { title: "award (Attributes 1)" },
    award2b: { title: "award (Attributes 2)" },
    award3: { title: "award (Properties)" },
    bestFitLine: { title: "bestFitLine" },
    bezierControls: { title: "bezierControls" },
    blockQuote: { title: "blockQuote" },
    boolean: { title: "boolean" },
    booleanInput: { title: "booleanInput" },
    booleanList: { title: "booleanList" },
    br: { title: "br" },
    c: { title: "c" },
    callAction: { title: "callAction" },
    caption: { title: "caption" },
    case: { title: "case" },
    ceil: { title: "ceil" },
    cell: { title: "cell" },
    choice: { title: "choice" },
    choiceInput: { title: "choiceInput" },
    circle: { title: "circle" },
    clampNumber: { title: "clampNumber" },
    cobwebPolyline: { title: "cobwebPolyline" },
    collect: { title: "collect" },
    conclusion: { title: "conclusion" },
    conditionalContent: { title: "conditionalContent" },
    considerAsResponses: { title: "considerAsResponses" },
    constrainTo: { title: "constrainTo" },
    constrainToGraph: { title: "constrainToGraph" },
    constrainToGrid: { title: "constrainToGrid" },
    constrainToInterior: { title: "constrainToInterior" },
    constraintUnion: { title: "constraintUnion" },
    controlVectors: { title: "controlVectors" },
    convertSetToList: { title: "convertSetToList" },
    coords: { title: "coords" },
    count: { title: "count" },
    curve: { title: "curve" },
    curve2: { title: "curve (Attributes)" },
    curve3: { title: "curve (Properties)" },
    definition: { title: "definition" },
    derivative: { title: "derivative" },
    description: { title: "description" },
    div: { title: "div" },
    document: { title: "document" },
    eigenDecomposition: { title: "eigenDecomposition" },
    electronConfiguration: { title: "electronConfiguration" },
    ellipsis: { title: "ellipsis" },
    else: { title: "else" },
    em: { title: "em" },
    endpoint: { title: "endpoint" },
    equilibriumCurve: { title: "equilibriumCurve" },
    equilibriumLine: { title: "equilibriumLine" },
    equilibriumPoint: { title: "equilibriumPoint" },
    evaluate: { title: "evaluate" },
    example: { title: "example" },
    exercise: { title: "exercise" },
    exercises: { title: "exercises" },
    extractMath: { title: "extractMath" },
    feedback: { title: "feedback" },
    figure: { title: "figure" },
    floor: { title: "floor" },
    footnote: { title: "footnote" },
    function: { title: "function (Basic Use)" },
    function2: { title: "function (Attributes 1)" },
    function3: { title: "function (Attributes 2)" },
    function4: { title: "function (Properties)" },
    functionIterates: { title: "functionIterates" },
    gcd: { title: "gcd" },
    graph: { title: "graph (Page 1)" },
    graph2: { title: "graph (Page 2)" },
    group: { title: "group" },
    hasSameFactoring: { title: "hasSameFactoring" },
    hint: { title: "hint" },
    hr: { title: "hr" },
    image: { title: "image" },
    intComma: { title: "intComma" },
    integer: { title: "integer" },
    intersection: { title: "intersection" },
    interval: { title: "interval" },
    intervalList: { title: "intervalList" },
    introduction: { title: "introduction" },
    ion: { title: "ion" },
    ionicCompound: { title: "ionicCompound" },
    isBetween: { title: "isBetween" },
    isInteger: { title: "isInteger" },
    isNumber: { title: "isNumber" },
    label: { title: "label" },
    legend: { title: "legend" },
    li: { title: "li" },
    line: { title: "line" },
    lineSegment: { title: "lineSegment" },
    lorem: { title: "lorem" },
    lq: { title: "lq" },
    lsq: { title: "lsq" },
    m: { title: "m" },
    matchesPattern: { title: "matchesPattern" },
    math: { title: "math (Page 1)" },
    math2: { title: "math (Page 2)" },
    mathInput: { title: "mathInput" },
    mathList: { title: "mathList" },
    matrix: { title: "matrix" },
    matrixInput: { title: "matrixInput" },
    max: { title: "max" },
    md: { title: "md" },
    mdash: { title: "mdash" },
    mdn: { title: "mdn" },
    me: { title: "me" },
    mean: { title: "mean" },
    median: { title: "median" },
    men: { title: "men" },
    min: { title: "min" },
    mod: { title: "mod" },
    module: { title: "module" },
    moduleAttributes: { title: "moduleAttributes" },
    mrow: { title: "mrow" },
    nbsp: { title: "nbsp" },
    ndash: { title: "ndash" },
    not: { title: "not" },
    number: { title: "number" },
    numberList: { title: "numberList" },
    objectives: { title: "objectives" },
    odeSystem: { title: "odeSystem" },
    ol: { title: "ol" },
    option: { title: "option" },
    or: { title: "or" },
    orbitalDiagram: { title: "orbitalDiagram" },
    orbitalDiagramInput: { title: "orbitalDiagramInput" },
    p: { title: "p" },
    paginator: { title: "paginator" },
    paginatorControls: { title: "paginatorControls" },
    parabola: { title: "parabola" },
    paragraphs: { title: "paragraphs" },
    part: { title: "part" },
    pegboard: { title: "pegboard" },
    piecewiseFunction: { title: "piecewiseFunction" },
    point: { title: "point" },
    pointList: { title: "pointList" },
    polygon: { title: "polygon" },
    polyline: { title: "polyline" },
    pre: { title: "pre" },
    pretzel: { title: "pretzel" },
    problem: { title: "problem" },
    problems: { title: "problems" },
    product: { title: "product" },
    proof: { title: "proof" },
    q: { title: "q" },
    question: { title: "question" },
    ray: { title: "ray" },
    rectangle: { title: "rectangle" },
    ref: { title: "ref" },
    regionBetweenCurves: { title: "regionBetweenCurves" },
    regionBetweenCurveXAxis: { title: "regionBetweenCurveXAxis" },
    regionHalfPlane: { title: "regionHalfPlane" },
    regularPolygon: { title: "regularPolygon (Page 1)" },
    regularPolygon2: { title: "regularPolygon (Page 2)" },
    repeat: { title: "repeat" },
    repeatForSequence: { title: "repeatForSequence" },
    rightHandSide: { title: "rightHandSide" },
    round: { title: "round" },
    row_matrix: { title: "row (for matrix)" },
    row_table: { title: "row (for table)" },
    rq: { title: "rq" },
    rsq: { title: "rsq" },
    samplePrimeNumbers: { title: "samplePrimeNumbers" },
    sampleRandomNumbers: { title: "sampleRandomNumbers" },
    sbsGroup: { title: "sbsGroup" },
    section: { title: "section" },
    select: { title: "select" },
    selectFromSequence: { title: "selectFromSequence" },
    selectPrimeNumbers: { title: "selectPrimeNumbers" },
    selectRandomNumbers: { title: "selectRandomNumbers" },
    sequence: { title: "sequence" },
    setSmallToZero: { title: "setSmallToZero" },
    setup: { title: "setup" },
    shortDescription: { title: "shortDescription" },
    shuffle: { title: "shuffle" },
    sideBySide: { title: "sideBySide" },
    sign: { title: "sign" },
    slider: { title: "slider" },
    solution: { title: "solution" },
    sort: { title: "sort" },
    span: { title: "span" },
    split: { title: "split" },
    spreadsheet: { title: "spreadsheet" },
    sq: { title: "sq" },
    stack: { title: "stack" },
    standardDeviation: { title: "standardDeviation" },
    statement: { title: "statement" },
    stickyGroup: { title: "stickyGroup" },
    styleDefinition: { title: "styleDefinition" },
    subsection: { title: "subsection" },
    subsetOfReals: { title: "subsetOfReals" },
    subsetOfRealsInput: { title: "subsetOfRealsInput" },
    substitute: { title: "substitute" },
    subsubsection: { title: "subsubsection" },
    sum: { title: "sum" },
    table: { title: "table" },
    tabular: { title: "tabular" },
    tag: { title: "tag, tage" },
    task: { title: "task" },
    term: { title: "term" },
    text: { title: "text" },
    textInput: { title: "textInput" },
    textList: { title: "textList" },
    theorem: { title: "theorem" },
    title: { title: "title" },
    triangle: { title: "triangle" },
    triggerSet: { title: "triggerSet" },
    tupleList: { title: "tupleList" },
    ul: { title: "ul" },
    updateValue: { title: "updateValue" },
    variance: { title: "variance" },
    vector: { title: "vector" },
    vectorList: { title: "vectorList" },
    video: { title: "video" },
    when: { title: "when" },
    wrapNumberPeriodic: { title: "wrapNumberPeriodic" },
    xLabel: { title: "xLabel" },
    xor: { title: "xor" },
    yLabel: { title: "yLabel" },
    Sample_Component: {
        display: "hidden",
    },
};
